!@descr: module defining the user interfaces for volume processing programs in the simple_exec suite
module simple_ui_volume
use simple_ui_modules
implicit none

type(ui_program), target :: center
type(ui_program), target :: reproject
type(ui_program), target :: volops
type(ui_program), target :: reconstruct3D_pcg

contains

    subroutine construct_volume_programs(prgtab)
        class(ui_hash), intent(inout) :: prgtab
        call new_center(prgtab)
        call new_reproject(prgtab)
        call new_volops(prgtab)
        call new_reconstruct3D_pcg(prgtab)
    end subroutine construct_volume_programs

    subroutine print_volume_programs(logfhandle)
        integer, intent(in) :: logfhandle
        write(logfhandle,'(A)') format_str('VOLUME PROCESSING:', C_UNDERLINED)
        write(logfhandle,'(A)') center%name%to_char()
        write(logfhandle,'(A)') reproject%name%to_char()
        write(logfhandle,'(A)') volops%name%to_char()
        write(logfhandle,'(A)') reconstruct3D_pcg%name%to_char()
        write(logfhandle,'(A)') ''
    end subroutine print_volume_programs

    subroutine new_center( prgtab )
        class(ui_hash), intent(inout) :: prgtab
        ! PROGRAM SPECIFICATION
        call center%new(&
        &'center',&                    ! name
        &'Center volume',&             ! descr_short
        &'is a program for centering a volume and mapping the shift parameters back to the particle images',& ! descr_long
        &'simple_exec',&               ! executable
        &.false.)                      ! requires sp_project
        ! INPUT PARAMETER SPECIFICATIONS
        ! image input/output
        call center%add_input(UI_IMG, 'vol1', 'file', 'Volume', 'Volume to center', &
        & 'input volume e.g. vol.mrc', .false., '')
        call center%add_input(UI_IMG, stk)
        ! parameter input/output
        call center%add_input(UI_PARM, smpd)
        call center%add_input(UI_PARM, oritab)
        call center%add_input(UI_PARM, outfile)
        ! alternative inputs
        ! <empty>
        ! search controls
        ! <empty>
        ! filter controls
        call center%add_input(UI_FILT, 'cenlp', 'num', 'Centering low-pass limit', 'Limit for low-pass filter used in binarisation &
        &prior to determination of the center of gravity of the reference volume(s) and centering', 'centering low-pass limit in &
        &Angstroms{30}', .false., 30.)
        ! mask controls
        ! <empty>
        ! computer controls
        call center%add_input(UI_COMP, nthr)
        ! add to ui_hash
        call add_ui_program('center', center, prgtab)
    end subroutine new_center

    subroutine new_reproject( prgtab )
        class(ui_hash), intent(inout) :: prgtab
        ! PROGRAM SPECIFICATION
        call reproject%new(&
        &'reproject',&                         ! name
        &'Re-project volume',&                 ! descr_short
        &'is a program for re-projecting a volume using Fourier interpolation. Input is a SPIDER or &
        &MRC volume. Output is a stack of projection images of the same format as the inputted volume. Projections &
        &are generated by extracting central sections from the Fourier volume and back transforming the 2D FTs. &
        &nspace controls the number of projection directions. The  oritab parameter allows you to input the orientations &
        &that you wish to have your volume projected in. pgrp controls the point-group symmetry &
        &c (rotational), d (dihedral), t (tetrahedral), o (octahedral) or i (icosahedral). The point-group symmetry is &
        &used to restrict the set of projections to within the asymmetric unit. &
        &neg inverts the contrast of the projections',&
        &'simple_exec',&                       ! executable
        &.false.)                              ! requires sp_project
        ! INPUT PARAMETER SPECIFICATIONS
        ! image input/output
        call reproject%add_input(UI_IMG, 'vol1', 'file', 'Volume', 'Volume for creating 2D central &
        & sections', 'input volume e.g. vol.mrc', .true., 'vol1.mrc')
        call reproject%add_input(UI_IMG, outstk)
        ! parameter input/output
        call reproject%add_input(UI_PARM, smpd)
        call reproject%add_input(UI_PARM, oritab)
        call reproject%add_input(UI_PARM, neg)
        ! alternative inputs
        ! <empty>
        ! search controls
        call reproject%add_input(UI_SRCH, nspace, required_override=.true.)
        call reproject%add_input(UI_SRCH, pgrp,   required_override=.true.)
        ! filter controls
        ! <empty>
        ! mask controls
        call reproject%add_input(UI_MASK, mskdiam, required_override=.false.)
        ! computer controls
        call reproject%add_input(UI_COMP, nthr)
        ! add to ui_hash
        call add_ui_program('reproject', reproject, prgtab)
    end subroutine new_reproject

    subroutine new_volops( prgtab )
        class(ui_hash), intent(inout) :: prgtab
        ! PROGRAM SPECIFICATION
        call volops%new(&
        &'volops',&                                                                               ! name
        &'Standard volume editing',&                                                              ! descr_short
        &'is a program that provides standard single-particle image processing routines for MRC or SPIDER volumes',& ! descr_long
        &'simple_exec',&                                                                          ! executable
        &.false.)                                                                                 ! requires sp_project
        ! INPUT PARAMETER SPECIFICATIONS
        ! image input/output
        call volops%add_input(UI_IMG, 'vol1', 'file', 'Volume', 'Volume to mask', &
        & 'input volume e.g. vol.mrc', .true., '')
        call volops%add_input(UI_IMG, outvol)
        ! ! parameter input/output
        call volops%add_input(UI_PARM, smpd, required_override=.false.)
        call volops%add_input(UI_PARM, 'guinier', 'binary', 'Guinier plot','calculate Guinier plot(yes|no){no}', '(yes|no){no}', .false., 'no')
        call volops%add_input(UI_PARM, neg)
        call volops%add_input(UI_PARM, 'snr', 'num', 'SNR','Adds noise to the volume', 'signal-to-noise ratio(0.)', .false., 0.)
        call volops%add_input(UI_PARM, mirr)
        call volops%add_input(UI_PARM, e1)
        call volops%add_input(UI_PARM, e2)
        call volops%add_input(UI_PARM, e3)
        call volops%add_input(UI_PARM, 'xsh', 'num', 'Translation along x-axis','Shift along X in pixels', 'in pixels', .false., 0.)
        call volops%add_input(UI_PARM, 'ysh', 'num', 'Translation along y-axis','Shift along Y in pixels', 'in pixels', .false., 0.)
        call volops%add_input(UI_PARM, 'zsh', 'num', 'Translation along z-axis','Shift along Z in pixels', 'in pixels', .false., 0.)
        call volops%add_input(UI_PARM, outfile)
        call volops%add_input(UI_PARM, mul)
        ! alternative inputs
        ! <empty>
        ! search controls
        ! <empty>
        ! filter controls
        call volops%add_input(UI_FILT, lp, required_override=.false.)
        call volops%add_input(UI_FILT, hp)
        call volops%add_input(UI_FILT, bfac)
        ! mask controls
        call volops%add_input(UI_MASK, mskdiam, required_override=.false.)
        ! computer controls
        call volops%add_input(UI_COMP, nthr)
        ! add to ui_hash
        call add_ui_program('volops', volops, prgtab)
    end subroutine new_volops

    subroutine new_reconstruct3D_pcg( prgtab )
        class(ui_hash), intent(inout) :: prgtab
        ! PROGRAM SPECIFICATION
        call reconstruct3D_pcg%new(&
        &'reconstruct3D_pcg',&                 ! name
        &'Experimental CTF/sigma-weighted PCG 3D reconstruction',&
        &'is an experimental single-state 3D reconstruction program using a matrix-free, '//&
        &'preconditioned-conjugate-gradient solver instead of Fourier gridding (doc/policies/'//&
        &'reconstruct3D_pcg_policy.md). Reads a project and reconstructs one volume for one '//&
        &'state from its current particle orientations, CTF, and shifts; orientations are inputs, not '//&
        &'optimized. objfun=euclid requires sigma2 files and weights the fit by them; objfun=cc runs '//&
        &'unweighted. nparts=1, no even/odd split, no distributed execution. Point-group symmetry '//&
        &'is applied by coordinate replication (pgrp=c1 is a no-op). Writes to a new '//&
        &'experimental output directory and never modifies the project.',&
        &'simple_exec',&                       ! executable
        &.true.)                                ! requires sp_project
        ! INPUT PARAMETER SPECIFICATIONS
        ! parameter input/output
        ! NOTE: projfile is deliberately NOT declared -- requires_sp_project
        ! above makes params%new auto-discover a unique *.simple in the cwd,
        ! exactly as reconstruct3D does. Declaring it would force the user to
        ! pass it and defeat that discovery.
        call reconstruct3D_pcg%add_input(UI_PARM, oritype)
        call reconstruct3D_pcg%add_input(UI_PARM, objfun)
        call reconstruct3D_pcg%add_input(UI_PARM, 'state', 'num', 'State to reconstruct', &
            &'Index of the single state to reconstruct', 'state index{1}', .false., 1.)
        ! search controls
        call reconstruct3D_pcg%add_input(UI_SRCH, pgrp)
        call reconstruct3D_pcg%add_input(UI_SRCH, 'pcgop', 'multi', 'PCG normal operator', &
            &'Normal-operator implementation: kernel is the section-8.1 Toeplitz operator, whose '//&
            &'per-iteration cost is independent of particle count and is roughly 7x faster per '//&
            &'iteration; matrixfree is the exact reference operator, slower but free of the '//&
            &'kernel shift-invariance approximation(matrixfree|kernel){kernel}', &
            &'(matrixfree|kernel){kernel}', .false., 'kernel')
        ! filter controls
        call reconstruct3D_pcg%add_input(UI_FILT, maxits, required_override=.false.)
        call reconstruct3D_pcg%add_input(UI_FILT, 'rtol', 'num', 'PCG relative residual tolerance', &
            &'Stop when the relative preconditioned residual falls below this', 'tolerance{0.001}', &
            &.false., 0.001)
        ! mask controls
        call reconstruct3D_pcg%add_input(UI_MASK, mskdiam, required_override=.false.)
        ! computer controls
        call reconstruct3D_pcg%add_input(UI_COMP, nthr)
        ! add to ui_hash
        call add_ui_program('reconstruct3D_pcg', reconstruct3D_pcg, prgtab)
    end subroutine new_reconstruct3D_pcg

end module simple_ui_volume
