!@descr: module defining the user interfaces for volume processing programs in the simple_exec suite
module simple_ui_volume
use simple_ui_modules
implicit none

type(category_descriptor), parameter :: UI_CATEGORY = category_descriptor('volume', 'Volume Processing', 180)
type(ui_program), target :: center
type(ui_program), target :: reproject
type(ui_program), target :: volops

contains

    subroutine construct_volume_programs(prgtab)
        class(ui_hash), intent(inout) :: prgtab
        call new_center(prgtab)
        call new_reproject(prgtab)
        call new_volops(prgtab)
    end subroutine construct_volume_programs

subroutine new_center( prgtab )
        class(ui_hash), intent(inout) :: prgtab
        ! PROGRAM SPECIFICATION
        call center%new(&
        &'center',&                    ! name
        &'Center a volume and propagate shifts to particle images',& ! summary
        &'is a program for centering a volume and mapping the shift parameters back to the particle images',& ! help
        &'simple_exec',&               ! executable
        &.false.)                      ! requires sp_project
        ! INPUT PARAMETER SPECIFICATIONS
        ! image input/output
        call center%add_input(UI_IMG, 'vol1', 'file', 'Volume', 'Volume to center', &
        & 'input volume e.g. vol.mrc', .false., '', &
        &visibility=UI_VIS_DEVELOPER)
        call center%add_input(UI_IMG, stk, &
        &visibility=UI_VIS_DEVELOPER)
        ! parameter input/output
        call center%add_input(UI_PARM, smpd, &
        &visibility=UI_VIS_STANDARD)
        call center%add_input(UI_FILE, oritab, &
        &visibility=UI_VIS_DEVELOPER)
        call center%add_input(UI_FILE, outfile, &
        &visibility=UI_VIS_DEVELOPER)
        ! <no additional inputs>
        ! <empty>
        ! search controls
        ! <empty>
        ! filter controls
        call center%add_input(UI_FILT, 'cenlp', 'num', 'Centering low-pass limit', 'Limit for low-pass filter used in binarisation &
        &prior to determination of the center of gravity of the reference volume(s) and centering', 'centering low-pass limit in &
        &Angstroms{30}', .false., 30., &
        &visibility=UI_VIS_DEVELOPER)
        ! mask controls
        ! <empty>
        ! computer controls
        call center%add_input(UI_COMP, nthr, &
        &visibility=UI_VIS_STANDARD)
        ! add to ui_hash
        call add_ui_program('center', center, prgtab, UI_CATEGORY)
    end subroutine new_center

    subroutine new_reproject( prgtab )
        class(ui_hash), intent(inout) :: prgtab
        ! PROGRAM SPECIFICATION
        call reproject%new(&
        &'reproject',&                         ! name
        &'Generate projections from a 3D volume at chosen orientations',& ! summary
        &'is a program for re-projecting a volume using Fourier interpolation. Input is a SPIDER or &
        &MRC volume. Output is a stack of projection images of the same format as the inputted volume. Projections &
        &are generated by extracting central sections from the Fourier volume and back transforming the 2D FTs. &
        &nspace controls the number of projection directions. The  oritab parameter allows you to input the orientations &
        &that you wish to have your volume projected in. pgrp controls the point-group symmetry &
        &c (rotational), d (dihedral), t (tetrahedral), o (octahedral) or i (icosahedral). The point-group symmetry is &
        &used to restrict the set of projections to within the asymmetric unit. &
        &neg inverts the contrast of the projections',&
        &'simple_exec',&                       ! executable
        &.false., &
        &visibility=UI_VIS_ADVANCED)                              ! requires sp_project
        ! INPUT PARAMETER SPECIFICATIONS
        ! image input/output
        call reproject%add_input(UI_IMG, 'vol1', 'file', 'Volume', 'Volume for creating 2D central &
        & sections', 'input volume e.g. vol.mrc', .true., 'vol1.mrc', &
        &visibility=UI_VIS_STANDARD)
        call reproject%add_input(UI_IMG, outstk, &
        &visibility=UI_VIS_ADVANCED)
        ! parameter input/output
        call reproject%add_input(UI_PARM, smpd, &
        &visibility=UI_VIS_STANDARD)
        call reproject%add_input(UI_FILE, oritab, &
        &visibility=UI_VIS_ADVANCED)
        call reproject%add_input(UI_PARM, neg, &
        &visibility=UI_VIS_ADVANCED)
        ! <no additional inputs>
        ! <empty>
        ! search controls
        call reproject%add_input(UI_SRCH, nspace, required_override=.true., &
        &visibility=UI_VIS_STANDARD)
        call reproject%add_input(UI_SRCH, pgrp,   required_override=.true., &
        &visibility=UI_VIS_STANDARD)
        ! filter controls
        ! <empty>
        ! mask controls
        call reproject%add_input(UI_MASK, mskdiam, required_override=.false., &
        &visibility=UI_VIS_ADVANCED)
        ! computer controls
        call reproject%add_input(UI_COMP, nthr, &
        &visibility=UI_VIS_STANDARD)
        ! add to ui_hash
        call add_ui_program('reproject', reproject, prgtab, UI_CATEGORY)
    end subroutine new_reproject

    subroutine new_volops( prgtab )
        class(ui_hash), intent(inout) :: prgtab
        ! PROGRAM SPECIFICATION
        call volops%new(&
        &'volops',&                                                                               ! name
        &'Edit, filter, transform, or resample a 3D volume',& ! summary
        &'is a program that provides standard single-particle image processing routines for MRC or SPIDER volumes',& ! help
        &'simple_exec',&                                                                          ! executable
        &.false., &
        &visibility=UI_VIS_ADVANCED)                                                                                 ! requires sp_project
        ! INPUT PARAMETER SPECIFICATIONS
        ! image input/output
        call volops%add_input(UI_IMG, 'vol1', 'file', 'Volume', 'Volume to mask', &
        & 'input volume e.g. vol.mrc', .true., '', &
        &visibility=UI_VIS_STANDARD)
        call volops%add_input(UI_IMG, outvol, &
        &visibility=UI_VIS_ADVANCED)
        ! ! parameter input/output
        call volops%add_input(UI_PARM, smpd, required_override=.false., &
        &visibility=UI_VIS_ADVANCED)
        call volops%add_input(UI_PARM, 'guinier', 'binary', 'Guinier plot','calculate Guinier plot(yes|no){no}','', .false., 'no', &
        &choices=ui_choices([character(len=3) :: 'yes', 'no']), &
        &visibility=UI_VIS_ADVANCED)
        call volops%add_input(UI_PARM, neg, &
        &visibility=UI_VIS_ADVANCED)
        call volops%add_input(UI_PARM, 'snr', 'num', 'SNR','Adds noise to the volume', 'signal-to-noise ratio(0.)', .false., 0., &
        &visibility=UI_VIS_ADVANCED)
        call volops%add_input(UI_PARM, mirr, &
        &visibility=UI_VIS_ADVANCED)
        call volops%add_input(UI_PARM, e1, &
        &visibility=UI_VIS_ADVANCED)
        call volops%add_input(UI_PARM, e2, &
        &visibility=UI_VIS_ADVANCED)
        call volops%add_input(UI_PARM, e3, &
        &visibility=UI_VIS_ADVANCED)
        call volops%add_input(UI_PARM, 'xsh', 'num', 'Translation along x-axis','Shift along X in pixels', 'in pixels', .false., 0., &
        &visibility=UI_VIS_ADVANCED)
        call volops%add_input(UI_PARM, 'ysh', 'num', 'Translation along y-axis','Shift along Y in pixels', 'in pixels', .false., 0., &
        &visibility=UI_VIS_ADVANCED)
        call volops%add_input(UI_PARM, 'zsh', 'num', 'Translation along z-axis','Shift along Z in pixels', 'in pixels', .false., 0., &
        &visibility=UI_VIS_ADVANCED)
        call volops%add_input(UI_FILE, outfile, &
        &visibility=UI_VIS_ADVANCED)
        call volops%add_input(UI_PARM, mul, &
        &visibility=UI_VIS_ADVANCED)
        ! <no additional inputs>
        ! <empty>
        ! search controls
        ! <empty>
        ! filter controls
        call volops%add_input(UI_FILT, lp, required_override=.false., &
        &visibility=UI_VIS_ADVANCED)
        call volops%add_input(UI_FILT, hp, &
        &visibility=UI_VIS_ADVANCED)
        call volops%add_input(UI_FILT, bfac, &
        &visibility=UI_VIS_ADVANCED)
        ! mask controls
        call volops%add_input(UI_MASK, mskdiam, required_override=.false., &
        &visibility=UI_VIS_ADVANCED)
        ! computer controls
        call volops%add_input(UI_COMP, nthr, &
        &visibility=UI_VIS_STANDARD)
        ! add to ui_hash
        call add_ui_program('volops', volops, prgtab, UI_CATEGORY)
    end subroutine new_volops

end module simple_ui_volume
