module simple_ui_api
use simple_ui_program, only: ui_program
implicit none
type(ui_program), target :: abinitio2D
type(ui_program), target :: abinitio3D
type(ui_program), target :: abinitio3D_cavgs
type(ui_program), target :: auto_spher_mask
type(ui_program), target :: automask
type(ui_program), target :: automask2D
type(ui_program), target :: binarize
type(ui_program), target :: center
type(ui_program), target :: check_refpick
type(ui_program), target :: clin_fsc
type(ui_program), target :: cleanup2D
type(ui_program), target :: cluster2D
type(ui_program), target :: cluster2D_subsets
type(ui_program), target :: cluster_cavgs
type(ui_program), target :: cluster_cavgs_selection
type(ui_program), target :: cluster_stack
type(ui_program), target :: convert
type(ui_program), target :: ctf_estimate
type(ui_program), target :: ctf_phaseflip
type(ui_program), target :: ctfops
type(ui_program), target :: dock_volpair
type(ui_program), target :: estimate_lpstages
type(ui_program), target :: export_relion
type(ui_program), target :: export_starproject
type(ui_program), target :: extract
type(ui_program), target :: extract_subproj
type(ui_program), target :: filter
type(ui_program), target :: fsc
type(ui_program), target :: gen_pspecs_and_thumbs
type(ui_program), target :: icm2D
type(ui_program), target :: icm3D
type(ui_program), target :: import_boxes
type(ui_program), target :: import_cavgs
type(ui_program), target :: import_movies
type(ui_program), target :: import_particles
type(ui_program), target :: import_starproject
type(ui_program), target :: info_image
type(ui_program), target :: info_stktab
type(ui_program), target :: make_cavgs
type(ui_program), target :: make_oris
type(ui_program), target :: map_cavgs_selection
type(ui_program), target :: mask
type(ui_program), target :: match_cavgs
type(ui_program), target :: merge_projects
type(ui_program), target :: mini_stream
type(ui_program), target :: model_validation
type(ui_program), target :: motion_correct
type(ui_program), target :: multivol_assign
type(ui_program), target :: new_project
type(ui_program), target :: noisevol
type(ui_program), target :: orisops
type(ui_program), target :: oristats
type(ui_program), target :: pdb2mrc
type(ui_program), target :: pick
type(ui_program), target :: postprocess
type(ui_program), target :: ppca_denoise
type(ui_program), target :: ppca_denoise_classes
type(ui_program), target :: ppca_volvar
type(ui_program), target :: preprocess
type(ui_program), target :: print_dose_weights
type(ui_program), target :: print_fsc
type(ui_program), target :: print_magic_boxes
type(ui_program), target :: print_project_field
type(ui_program), target :: print_project_info
type(ui_program), target :: prune_project
type(ui_program), target :: reconstruct3D
type(ui_program), target :: reextract
type(ui_program), target :: refine3D
type(ui_program), target :: refine3D_auto
type(ui_program), target :: reproject
type(ui_program), target :: sample_classes
type(ui_program), target :: scale
type(ui_program), target :: select_
type(ui_program), target :: select_clusters
type(ui_program), target :: selection
type(ui_program), target :: simulate_movie
type(ui_program), target :: simulate_noise
type(ui_program), target :: simulate_particles
type(ui_program), target :: split_stack
type(ui_program), target :: stack
type(ui_program), target :: stackops
type(ui_program), target :: symaxis_search
type(ui_program), target :: symmetrize_map
type(ui_program), target :: symmetry_test
type(ui_program), target :: uniform_filter2D
type(ui_program), target :: uniform_filter3D
type(ui_program), target :: update_project
type(ui_program), target :: vizoris
type(ui_program), target :: volanalyze
type(ui_program), target :: volops
type(ui_program), target :: write_classes
type(ui_program), target :: write_mic_filetab
type(ui_program), target :: zero_project_shifts

! NOTE: also declared but not in simple_exec list (kept SIMPLE by your “SIMPLE wins” policy):
type(ui_program), target :: assign_optics_groups
type(ui_program), target :: replace_project_field
end module simple_ui_api
