"""JobModel definition."""

from django.db       import models
from .workspacemodel import WorkspaceModel

class JobModel(models.Model):
    """Primary stream-job record and per-stage execution state."""

    disp                       = models.IntegerField(default=0)
    dset                       = models.ForeignKey(WorkspaceModel, on_delete=models.CASCADE)
    name                       = models.CharField(max_length=200, default='')
    desc                       = models.CharField(max_length=200, default='')
    dirc                       = models.CharField(max_length=200, default='')
    cdat                       = models.DateTimeField()
    args                       = models.JSONField(default=dict)
    status                     = models.CharField(max_length=20, default='unknown')
    master_stats               = models.JSONField(default=dict, null=True, blank=True)
    master_status              = models.CharField(max_length=20, default='unknown')
    master_update              = models.JSONField(default=dict, null=True, blank=True)
    master_heartbeat           = models.IntegerField(default=0)
    preprocessing_stats        = models.JSONField(default=dict)
    preprocessing_status       = models.CharField(max_length=20, default='unknown')
    preprocessing_update       = models.JSONField(default=dict)
    preprocessing_heartbeat    = models.IntegerField(default=0)
    optics_assignment_stats    = models.JSONField(default=dict)
    optics_assignment_status   = models.CharField(max_length=20, default='unknown')
    optics_assignment_update   = models.JSONField(default=dict)
    optics_assignment_heartbeat = models.DateTimeField(auto_now_add=True, blank=True)
    initial_picking_stats      = models.JSONField(default=dict)
    initial_picking_status     = models.CharField(max_length=20, default='unknown')
    initial_picking_update     = models.JSONField(default=dict)
    initial_picking_heartbeat = models.DateTimeField(auto_now_add=True, blank=True)
    generate_pickrefs_stats    = models.JSONField(default=dict)
    generate_pickrefs_status   = models.CharField(max_length=20, default='unknown')
    generate_pickrefs_update   = models.JSONField(default=dict)
    generate_pickrefs_heartbeat = models.DateTimeField(auto_now_add=True, blank=True)
    reference_picking_stats    = models.JSONField(default=dict)
    reference_picking_status   = models.CharField(max_length=20, default='unknown')
    reference_picking_update   = models.JSONField(default=dict)
    reference_picking_heartbeat = models.DateTimeField(auto_now_add=True, blank=True)
    particle_sieving_stats     = models.JSONField(default=dict)
    particle_sieving_status    = models.CharField(max_length=20, default='unknown')
    particle_sieving_update    = models.JSONField(default=dict)
    particle_sieving_heartbeat = models.DateTimeField(auto_now_add=True, blank=True)
    classification_2D_stats    = models.JSONField(default=dict)
    classification_2D_status   = models.CharField(max_length=20, default='unknown')
    classification_2D_update   = models.JSONField(default=dict)
    classification_2D_heartbeat = models.DateTimeField(auto_now_add=True, blank=True)
    particle_sets_stats        = models.JSONField(default=dict)
