!==Program simple_automask
!
! <automask/begin> is a program for solvent flattening of a volume (MRC or SPIDER). The algorithm 
! for background removal is based on low-pass filtering and binarization. First, the volume is low-pass
! filtered to \texttt{amsklp}. A binary volume is then generated by assigning foreground pixels 
! (=1) based on the volume calculated from the molecular weight, assuming a protein density of 1.43 g/mL. 
! A real-space low-pass filter softens the edge of the resulting binary volume before multiplying it with 
! the unmasked input volume to generate the flattened map. <automask/end>
!
! The code is distributed with the hope that it will be useful, but _WITHOUT_ _ANY_ _WARRANTY_.
! Redistribution and modification is regulated by the GNU General Public License.
! *Author:* Hans Elmlund 2011
!
program simple_automask3D
use simple_defs    ! singleton
use simple_jiffys, ! singleton
use simple_cmdline, only: cmdline
use simple_masker,  only: automask
use simple_build,   only: build
use simple_params,  only: params
implicit none
type(params)  :: p
type(build)   :: b
type(cmdline) :: cline
integer       :: s
if( command_argument_count() < 4 )then
    write(*,'(a)', advance='no') 'SIMPLE_AUTOMASK3D vol1=<invol.ext> [vol2=<invol2.ext> etc.]'
    write(*,'(a)', advance='no') ' smpd=<sampling distance(in A)> msk=<mask radius(in pixels)>'
    write(*,'(a)') ' mw=<molecular weight(in kD)> [amsklp=<low-pass limit(in A){20}>]'
    write(*,'(a)') '**less commonly used**'
    write(*,'(a)', advance='no') ' [edge=<edge size for softening molecular envelope(in pixels){14}>]'
    write(*,'(a)') ' [binwidth=<number of layers before softening molecular envelope(in pixels){1}>]'
    stop
endif
call cline%parse
call cline%checkvar('vol1',        1)
call cline%checkvar('smpd',        2)
call cline%checkvar('msk',         3)
call cline%checkvar('mw',          4)
call cline%set('automsk', 'yes')
call cline%check
p = params(cline)                 ! constants & derived constants produced
call b%build_general_tbox(p,cline)
write(*,'(A,F14.1,A)') '>>> AUTOMASK LOW-PASS:',            p%amsklp,  ' ANGSTROMS'
write(*,'(A,I7,A)')    '>>> AUTOMASK SOFT EDGE WIDTH:',     p%edge,    ' PIXEL(S)'
write(*,'(A,I3,A)')    '>>> AUTOMASK BINARY LAYERS WIDTH:', p%binwidth,' PIXEL(S)'
do s=1,p%nstates
    p%masks(s) = 'automask_state'//int2str_pad(s,2)//p%ext
    p%vols_msk(s) = add2fbody(p%vols(s), p%ext, 'msk')
    call b%vol%read(p%vols(s))
    call automask(b, p, cline, b%vol,  b%mskvol, p%vols_msk(s), p%masks(s))
end do
call simple_end('**** SIMPLE_AUTOMASK3D NORMAL STOP ****')
end program