!==Program simple_automask2D
!
! <automask2D/begin> is a program for solvent flattening of class averages (MRC or SPIDER). The algorithm 
! for background removal is based on low-pass filtering and binarization. First, the class averages are 
! low-pass filtered to \texttt{amsklp}. Binary representatives are then generated by assigning foreground pixels 
! using sortmeans. A real-space low-pass filter softens the edge of the resulting binary averages before 
! multiplying it with the unmasked input averages to accomplish flattening. <automask/end>
!
! The code is distributed with the hope that it will be useful, but _WITHOUT_ _ANY_ _WARRANTY_.
! Redistribution and modification is regulated by the GNU General Public License.
! *Author:* Hans Elmlund 2011
!
program simple_automask2D
use simple_defs    ! singleton
use simple_jiffys, ! singleton
use simple_masker  ! singleton
use simple_cmdline, only: cmdline
use simple_build,   only: build
use simple_params,  only: params
implicit none
type(params)       :: p
type(build)        :: b
type(cmdline)      :: cline 
integer            :: iptcl
if( command_argument_count() < 3 )then
    write(*,'(a)', advance='no') 'SIMPLE_AUTOMASK2D stk=<input_stack.ext> smpd=<sampling distance(in A)>'
    write(*,'(a)', advance='no') ' msk=<mask radius(in pixels)> [amsklp=<low-pass limit(in A){25}>]'
    write(*,'(a)') ' [edge=<edge size for softening molecular envelope(in pixels){20}>]'
    stop
endif
call cline%parse
call cline%checkvar('stk',         1)
call cline%checkvar('smpd',        2)
call cline%checkvar('msk',         3)
if( .not. cline%defined('amsklp') )then
    call cline%set('amsklp', 25.)
endif
if( .not. cline%defined('edge') )then
    call cline%set('edge', 20.)
endif
call cline%set('automsk', 'yes')
call cline%check
call cline%set('prg', 'automask2D')
p = params(cline)                  ! constants & derived constants produced
call b%build_general_tbox(p,cline)
write(*,'(A,F8.2,A)') '>>> AUTOMASK LOW-PASS:',        p%amsklp, ' ANGSTROMS'
write(*,'(A,I3,A)')   '>>> AUTOMASK SOFT EDGE WIDTH:', p%edge,   ' PIXELS'
p%outstk = add2fbody(p%stk, p%ext, 'msk') 
do iptcl=1,p%nptcls
    call b%img%read(p%stk, iptcl)
    call automask2D(b%img, p, b%img_msk)
    call b%img_msk%write('automasks2D'//p%ext, iptcl)
    call b%img%write(p%outstk, iptcl)
end do
call simple_end('**** SIMPLE_AUTOMASK2D NORMAL STOP ****')
end program
