# Generated by Django 5.2.5 on 2025-08-21 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nice_lite', '0002_datasetmodel_dirc_jobmodel_dirc_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectmodel',
            name='desc',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='projectmodel',
            name='dirc',
            field=models.CharField(default='', max_length=200),
        ),
    ]
