# Generated by Django 5.2.5 on 2025-08-21 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nice_lite', '0004_datasetmodel_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datasetmodel',
            name='date',
        ),
    ]
