# Generated by Django 5.2.5 on 2025-08-22 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nice_lite', '0009_jobmodel_args'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobmodel',
            name='args',
            field=models.JSONField(default=dict),
        ),
    ]
