# Generated by Django 5.2.5 on 2025-08-26 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nice_lite', '0016_rename_preprocessing_jobmodel_preprocessing_stats_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobmodel',
            name='preprocessing_update',
            field=models.JSONField(default=dict),
        ),
    ]
