# Generated by Django 5.2.5 on 2025-08-27 15:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nice_lite', '0020_jobmodel_generate_pickrefs_heartbeat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobmodel',
            name='reference_picking_heartbeat',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jobmodel',
            name='reference_picking_stats',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='jobmodel',
            name='reference_picking_status',
            field=models.CharField(default='unknown', max_length=20),
        ),
        migrations.AddField(
            model_name='jobmodel',
            name='reference_picking_update',
            field=models.JSONField(default=dict),
        ),
    ]
