# Generated by Django 5.2.5 on 2025-09-05 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nice_lite', '0023_jobmodel_classification_2d_heartbeat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobmodel',
            name='particle_sets_stats',
            field=models.JSONField(default=dict),
        ),
    ]
