# Generated by Django 5.2.5 on 2025-10-01 14:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nice_lite', '0034_datasetmodel_disp_jobmodel_disp_workspacemodel_disp'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobclassicmodel',
            name='heartbeat',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jobclassicmodel',
            name='update',
            field=models.JSONField(default=dict),
        ),
    ]
