# 2D ANALYSIS
suite_id = "single_exec"
group_id = "2d-analysis"
group_title = "2D ANALYSIS"
group_order = 30

[[program]]
name = "analysis2D_nano"
executable = "single_exec"
display_name = "2D analysis (centering, diameter estimation & clustering) for nanocrystal time-series"
summary = "2D analysis (centering, diameter estimation & clustering) for nanocrystal time-series"
help = "is a program for 2D analysis for nanycrystal time-series"

[[program.input]]
key = "element"
label = "Atom element name: Au, Pt etc."
help = "Atom element name: Au, Pt etc."
placeholder = "atom composition e.g. Pt"
visibility = "developer"

[[program.input]]
key = "nptcls_per_cls"
label = "Number of particles per cluster"
help = "Initial number of particles per cluster{35}"
placeholder = "# initial particles per cluster{35}"
visibility = "developer"

[[program.input]]
key = "nthr"
label = "Number of threads per computing node, give 0 if unsure"
help = "Number of shared-memory OpenMP threads with close affinity per partition. Typically the same as the number of logical threads in a socket."
placeholder = "# shared-memory CPU threads"
visibility = "developer"

[[program.input]]
key = "script"
label = "Generate script for shared-mem exec on cluster"
help = "Generate script for shared-mem exec on cluster(yes|no){no}"
placeholder = "(yes|no){no}"
visibility = "developer"
choices = ["yes", "no"]

[[program]]
name = "center2D_nano"
executable = "single_exec"
display_name = "Simultaneous 2D alignment and clustering of nanoparticle images"
summary = "Simultaneous 2D alignment and clustering of nanoparticle images"
help = "is a distributed workflow implementing a reference-free 2D alignment/clustering algorithm suitable for the first pass of cleanup after time-series tracking"

[[program.input]]
key = "ncls"
label = "Number of 2D clusters"
help = "Number of groups to sort the particles into prior to averaging to create 2D class averages with improved SNR"
placeholder = "# 2D clusters"
visibility = "developer"

[[program.input]]
key = "trs"
label = "Maximum translational shift"
help = "Maximum half-width for bund-constrained search of rotational origin shifts"
placeholder = "max shift per iteration in pixels{5}"
visibility = "developer"

[[program.input]]
key = "nthr"
label = "Number of threads per computing node, give 0 if unsure"
help = "Number of shared-memory OpenMP threads with close affinity per partition. Typically the same as the number of logical threads in a socket."
placeholder = "# shared-memory CPU threads"
visibility = "developer"

[[program.input]]
key = "script"
label = "Generate script for shared-mem exec on cluster"
help = "Generate script for shared-mem exec on cluster(yes|no){no}"
placeholder = "(yes|no){no}"
visibility = "developer"
choices = ["yes", "no"]

[[program]]
name = "cluster2D_nano"
executable = "single_exec"
display_name = "Simultaneous 2D alignment and clustering of time-series of nanoparticle images"
summary = "Simultaneous 2D alignment and clustering of time-series of nanoparticle images"
help = "is a distributed workflow implementing a reference-free 2D alignment/clustering algorithm for time-series of nanoparticle images"

[[program.input]]
key = "moldiam"
label = "Molecular diameter"
help = "Molecular diameter(in Angstroms)"
placeholder = "In Angstroms"
visibility = "developer"

[[program.input]]
key = "nptcls_per_cls"
label = "Number of particles per cluster"
help = "Initial number of particles per cluster{35}"
placeholder = "# initial particles per cluster{35}"
visibility = "developer"

[[program.input]]
key = "center"
label = "Center class averages"
help = "Center class averages by their center of gravity and map shifts back to the particles(yes|no){yes}"
placeholder = "(yes|no){yes}"
visibility = "developer"
choices = ["yes", "no"]

[[program.input]]
key = "winsz"
label = "Half-window size"
help = "Half-window size(frames)"
placeholder = "winsz in # frames"
visibility = "developer"

[[program.input]]
key = "maxits"
label = "Max iterations"
help = "Maximum number of iterations"
placeholder = "Max # iterations"
visibility = "developer"

[[program.input]]
key = "trs"
label = "Maximum translational shift"
help = "Maximum half-width for bund-constrained search of rotational origin shifts"
placeholder = "max shift per iteration in pixels{5}"
visibility = "developer"

[[program.input]]
key = "hp"
label = "High-pass limit"
help = "High-pass resolution limit"
placeholder = "high-pass limit in Angstroms"
visibility = "developer"

[[program.input]]
key = "cenlp"
label = "Centering low-pass limit"
help = "Limit for low-pass filter used in binarisation prior to determination of the center of gravity of the class averages and centering"
placeholder = "centering low-pass limit in Angstroms{5.0}"
visibility = "developer"

[[program.input]]
key = "lp"
label = "Static low-pass limit"
help = "Static low-pass limit{1.0}"
placeholder = "low-pass limit in Angstroms"
visibility = "developer"

[[program.input]]
key = "lpstart"
label = "Initial low-pass limit"
help = "Initial low-pass limit"
placeholder = "initial low-pass limit in Angstroms"
visibility = "developer"

[[program.input]]
key = "lpstop"
label = "Final low-pass limit"
help = "Final low-pass limit{1.0}"
placeholder = "final low-pass limit in Angstroms"
visibility = "developer"

[[program.input]]
key = "mskdiam"
label = "Mask diameter"
help = "Mask diameter (in A) for application of a soft-edged circular mask to remove background noise"
placeholder = "mask diameter in A"
visibility = "developer"

[[program.input]]
key = "nparts"
label = "Number of computing nodes"
help = "Number of partitions for distributed memory execution. One part typically corresponds to one CPU socket in the distributed system. On a single-socket machine there may be speed benefits to dividing the jobs into a few (2-4) partitions, depending on memory capacity"
placeholder = "divide job into # parts"
visibility = "developer"

[[program.input]]
key = "nthr"
label = "Number of threads per computing node, give 0 if unsure"
help = "Number of shared-memory OpenMP threads with close affinity per partition. Typically the same as the number of logical threads in a socket."
placeholder = "# shared-memory CPU threads"
visibility = "developer"

[[program.input]]
key = "script"
label = "Generate script for shared-mem exec on cluster"
help = "Generate script for shared-mem exec on cluster(yes|no){no}"
placeholder = "(yes|no){no}"
visibility = "developer"
choices = ["yes", "no"]

[[program]]
name = "estimate_diam"
executable = "single_exec"
display_name = "Estimation of a suitable mask diameter for nanoparticle time-series"
summary = "Estimation of a suitable mask diameter for nanoparticle time-series"
help = "is a program for estimation of a suitable mask diameter for spherical masking of nanoparticle time-series"

[[program.input]]
key = "stk"
label = "Particle image stack"
help = "Particle image stack"
placeholder = "xxx.mrc file with particles"
visibility = "developer"

[[program.input]]
key = "smpd"
label = "Sampling distance"
help = "Distance between neighbouring pixels in Angstroms"
placeholder = "pixel size in Angstroms"
visibility = "developer"

[[program.input]]
key = "roavg"
label = "Rotationally average"
help = "Rotationally average before diam estimate(yes|no){no}"
placeholder = "(yes|no){no}"
visibility = "developer"
choices = ["yes", "no"]

[[program.input]]
key = "lp"
label = "low-pass limit in Angstroms{7.}"
help = "Low-pass resolution limit"
placeholder = "low-pass limit in Angstroms"
visibility = "developer"

[[program.input]]
key = "mskdiam"
label = "Mask diameter"
help = "Mask diameter (in A) for application of a soft-edged circular mask to remove background noise"
placeholder = "mask diameter in A"
visibility = "developer"

[[program.input]]
key = "nthr"
label = "Number of threads per computing node, give 0 if unsure"
help = "Number of shared-memory OpenMP threads with close affinity per partition. Typically the same as the number of logical threads in a socket."
placeholder = "# shared-memory CPU threads"
visibility = "developer"
