# 3D RECONSTRUCTION
suite_id = "single_exec"
group_id = "3d-reconstruction"
group_title = "3D RECONSTRUCTION"
group_order = 40

[[program]]
name = "abinitio3D_nano"
executable = "single_exec"
display_name = "ab initio 3D (nano defaults)"
summary = "ab initio 3D (nano defaults)"
help = "is a wrapper around abinitio3D that applies nanoparticle-oriented defaults while allowing overrides"

[[program.input]]
key = "nsample"
label = "Number of particles to sample"
help = "Number of particles to sample each iteration"
placeholder = "# particles to sample"
visibility = "developer"

[[program.input]]
key = "hp"
label = "High-pass limit"
help = "High-pass resolution limit"
placeholder = "high-pass limit in Angstroms"
visibility = "developer"

[[program.input]]
key = "cenlp"
label = "Centering low-pass limit"
help = "Limit for low-pass filter used in binarisation prior to determination of the center of gravity of the reference volume(s) and centering"
placeholder = "centering low-pass limit in Angstroms{5}"
visibility = "developer"

[[program.input]]
key = "lpstart"
label = "Starting low-pass limit"
help = "Starting low-pass limit"
placeholder = "low-pass limit in Angstroms{3}"
visibility = "developer"

[[program.input]]
key = "lpstop"
label = "Final low-pass limit"
help = "Final low-pass limit"
placeholder = "low-pass limit in Angstroms{1}"
visibility = "developer"

[[program.input]]
key = "mskdiam"
label = "Mask diameter"
help = "Mask diameter (in A) for application of a soft-edged circular mask to remove background noise"
placeholder = "mask diameter in A"
visibility = "developer"

[[program.input]]
key = "nparts"
label = "Number of computing nodes"
help = "Number of partitions for distributed memory execution. One part typically corresponds to one CPU socket in the distributed system. On a single-socket machine there may be speed benefits to dividing the jobs into a few (2-4) partitions, depending on memory capacity"
placeholder = "divide job into # parts"
visibility = "developer"

[[program.input]]
key = "nthr"
label = "Number of threads per computing node, give 0 if unsure"
help = "Number of shared-memory OpenMP threads with close affinity per partition. Typically the same as the number of logical threads in a socket."
placeholder = "# shared-memory CPU threads"
visibility = "developer"

[[program]]
name = "autorefine3D_nano"
executable = "single_exec"
display_name = "auto 3D refinement of metallic nanoparticles"
summary = "auto 3D refinement of metallic nanoparticles"
help = "is a distributed workflow for automated 3D refinement of metallic nanoparticles based on probabilistic projection matching"

[[program.input]]
key = "vol1"
label = "FCC reference volume"
help = "FCC lattice reference volume for creating polar 2D central  sections for nanoparticle image matching"
placeholder = "input volume e.g. vol.mrc"
visibility = "developer"

[[program.input]]
key = "smpd"
label = "Sampling distance"
help = "Distance between neighbouring pixels in Angstroms"
placeholder = "pixel size in Angstroms"
visibility = "developer"

[[program.input]]
key = "element"
label = "Atom element name: Au, Pt etc."
help = "Atom element name: Au, Pt etc."
placeholder = "atom composition e.g. Pt"
visibility = "developer"

[[program.input]]
key = "nspace"
label = "Number of projection directions"
help = "Number of projection directions used"
placeholder = "# projections"
visibility = "developer"

[[program.input]]
key = "trs"
label = "Maximum translational shift"
help = "Maximum half-width for bund-constrained search of rotational origin shifts"
placeholder = "max shift per iteration in pixels{5}"
visibility = "developer"

[[program.input]]
key = "center"
label = "Center reference volume(s)"
help = "Center reference volume(s) by their center of gravity and map shifts back to the particles(yes|no){yes}"
placeholder = "(yes|no){yes}"
visibility = "developer"
choices = ["yes", "no"]

[[program.input]]
key = "maxits"
label = "Max iterations"
help = "Maximum number of iterations"
placeholder = "Max # iterations{5}"
visibility = "developer"

[[program.input]]
key = "pgrp"
label = "Point-group symmetry"
help = "Point-group symmetry of particle(cn|dn|t|o|i){c1}"
placeholder = "point-group(cn|dn|t|o|i){c1}"
visibility = "developer"

[[program.input]]
key = "nrestarts"
label = "Number of restarts"
help = "Number of program restarts to execute{1}"
placeholder = "# restarts{1}"
visibility = "developer"

[[program.input]]
key = "hp"
label = "High-pass limit"
help = "High-pass resolution limit"
placeholder = "high-pass limit in Angstroms"
visibility = "developer"

[[program.input]]
key = "cenlp"
label = "Centering low-pass limit"
help = "Limit for low-pass filter used in binarisation prior to determination of the center of gravity of the reference volume(s) and centering"
placeholder = "centering low-pass limit in Angstroms{5}"
visibility = "developer"

[[program.input]]
key = "lp"
label = "Initial low-pass limit"
help = "Initial low-pass limit"
placeholder = "low-pass limit in Angstroms{1.5}"
visibility = "developer"

[[program.input]]
key = "icm"
label = "Whether to perform ICM filtering of reference(s)"
help = "Whether to perform ICM filtering of reference(s)(yes|no){no}"
placeholder = "(yes|no){no}"
visibility = "developer"
choices = ["yes", "no"]

[[program.input]]
key = "mskdiam"
label = "Mask diameter"
help = "Mask diameter (in A) for application of a soft-edged circular mask to remove background noise"
placeholder = "mask diameter in A"
visibility = "developer"

[[program.input]]
key = "mskdiam_detect"
label = "Detect-atoms mask diameter"
help = "Optional mask diameter in Angstroms passed only to detect_atoms"
placeholder = "mask diameter in Angstroms{0}"
visibility = "developer"

[[program.input]]
key = "nthr"
label = "Number of threads per computing node, give 0 if unsure"
help = "Number of shared-memory OpenMP threads with close affinity per partition. Typically the same as the number of logical threads in a socket."
placeholder = "# shared-memory CPU threads"
visibility = "developer"

[[program.input]]
key = "script"
label = "Generate script for shared-mem exec on cluster"
help = "Generate script for shared-mem exec on cluster(yes|no){no}"
placeholder = "(yes|no){no}"
visibility = "developer"
choices = ["yes", "no"]

[[program]]
name = "refine3D_nano"
executable = "single_exec"
display_name = "3D refinement of metallic nanoparticles"
summary = "3D refinement of metallic nanoparticles"
help = "is a distributed workflow for 3D refinement of metallic nanoparticles based on probabilistic projection matching"

[[program.input]]
key = "vol1"
label = "FCC reference volume"
help = "FCC lattice reference volume for creating polar 2D central  sections for nanoparticle image matching"
placeholder = "input volume e.g. vol.mrc"
visibility = "developer"

[[program.input]]
key = "vol_odd"
label = "Odd volume"
help = "Odd volume"
placeholder = "vol1.mrc file"
visibility = "developer"

[[program.input]]
key = "vol_even"
label = "Even volume"
help = "Even volume"
placeholder = "vol2.mrc file"
visibility = "developer"

[[program.input]]
key = "nspace"
label = "Number of projection directions"
help = "Number of projection directions used"
placeholder = "# projections"
visibility = "developer"

[[program.input]]
key = "trs"
label = "Maximum translational shift"
help = "Maximum half-width for bund-constrained search of rotational origin shifts"
placeholder = "max shift per iteration in pixels{5}"
visibility = "developer"

[[program.input]]
key = "center"
label = "Center reference volume(s)"
help = "Center reference volume(s) by their center of gravity and map shifts back to the particles(yes|no){yes}"
placeholder = "(yes|no){yes}"
visibility = "developer"
choices = ["yes", "no"]

[[program.input]]
key = "maxits"
label = "Max iterations"
help = "Maximum number of iterations"
placeholder = "Max # iterations"
visibility = "developer"

[[program.input]]
key = "update_frac"
label = "Fractional update per iteration"
help = "Fraction of particles to update per iteration in incremental learning scheme for accelerated convergence rate(0.1-0.5){1.}"
placeholder = "update this fraction per iter(0.1-0.5){1.0}"
visibility = "developer"

[[program.input]]
key = "pgrp"
label = "Point-group symmetry"
help = "Point-group symmetry of particle(cn|dn|t|o|i){c1}"
placeholder = "point-group(cn|dn|t|o|i){c1}"
visibility = "developer"

[[program.input]]
key = "continue"
label = "Continue previous refinement"
help = "Continue previous refinement(yes|no){no}"
placeholder = "(yes|no){no}"
visibility = "developer"
choices = ["yes", "no"]

[[program.input]]
key = "hp"
label = "High-pass limit"
help = "High-pass resolution limit"
placeholder = "high-pass limit in Angstroms"
visibility = "developer"

[[program.input]]
key = "cenlp"
label = "Centering low-pass limit"
help = "Limit for low-pass filter used in binarisation prior to determination of the center of gravity of the reference volume(s) and centering"
placeholder = "centering low-pass limit in Angstroms{5}"
visibility = "developer"

[[program.input]]
key = "lp"
label = "Static low-pass limit"
help = "Static low-pass limit"
placeholder = "low-pass limit in Angstroms{1.0}"
visibility = "developer"

[[program.input]]
key = "icm"
label = "Whether to perform ICM filtering of reference(s)"
help = "Whether to perform ICM filtering of reference(s)(yes|no){no}"
placeholder = "(yes|no){no}"
visibility = "developer"
choices = ["yes", "no"]

[[program.input]]
key = "mskdiam"
label = "Mask diameter"
help = "Mask diameter (in A) for application of a soft-edged circular mask to remove background noise"
placeholder = "mask diameter in A"
visibility = "developer"

[[program.input]]
key = "nparts"
label = "Number of computing nodes"
help = "Number of partitions for distributed memory execution. One part typically corresponds to one CPU socket in the distributed system. On a single-socket machine there may be speed benefits to dividing the jobs into a few (2-4) partitions, depending on memory capacity"
placeholder = "divide job into # parts"
visibility = "developer"

[[program.input]]
key = "nthr"
label = "Number of threads per computing node, give 0 if unsure"
help = "Number of shared-memory OpenMP threads with close affinity per partition. Typically the same as the number of logical threads in a socket."
placeholder = "# shared-memory CPU threads"
visibility = "developer"
