# ATOM ANALYSIS
suite_id = "single_exec"
group_id = "atom-analysis"
group_title = "ATOM ANALYSIS"
group_order = 50

[[program]]
name = "atoms_register"
executable = "single_exec"
display_name = "Registration of two nanoparticles"
summary = "Registration of two nanoparticles"
help = "is a program that registers two nanoparticles given the maps and the atom position maps."

[[program.input]]
key = "fname"
label = "PDB file list"
help = "PDB file list"
placeholder = "e.g. pdb_files.txt"
visibility = "developer"

[[program.input]]
key = "nthr"
label = "Number of threads per computing node, give 0 if unsure"
help = "Number of shared-memory OpenMP threads with close affinity per partition. Typically the same as the number of logical threads in a socket."
placeholder = "# shared-memory CPU threads"
visibility = "developer"

[[program]]
name = "atoms_rmsd"
executable = "single_exec"
display_name = "Analysis of results obtained with trajectory_reconstruct3D and detect_atoms"
summary = "Analysis of results obtained with trajectory_reconstruct3D and detect_atoms"
help = "is a program that analyzes atomic time-series coordinates"

[[program.input]]
key = "smpd"
label = "Sampling distance"
help = "Distance between neighbouring pixels in Angstroms"
placeholder = "pixel size in Angstroms"
visibility = "developer"

[[program.input]]
key = "pdbfiles"
label = "txt"
help = "List of PDB format coords files"
placeholder = "List of input coords files in PDB format"
visibility = "developer"

[[program.input]]
key = "frac_diam"
label = "Fraction of atomic diameter"
help = "Fraction of atomic diameter used for thresholding{0.5}"
placeholder = "{0.5}"
visibility = "developer"

[[program.input]]
key = "element"
label = "Atom element name: Au, Pt etc."
help = "Atom element name: Au, Pt etc."
placeholder = "atom composition e.g. Pt"
visibility = "developer"

[[program]]
name = "atoms_stats"
executable = "single_exec"
display_name = "Statistical test for radial dependent symmetry"
summary = "Statistical test for radial dependent symmetry"
help = "is a program that generates statistics at different radii and across the whole nano map."

[[program.input]]
key = "vol1"
label = "Raw volume"
help = "Raw volume of grey valued pixel intensities"
placeholder = "input volume e.g. vol.mrc"
visibility = "developer"

[[program.input]]
key = "vol2"
label = "Connected components volume"
help = "Connected components volume produced by detect atoms"
placeholder = "input volume e.g. *CC.mrc"
visibility = "developer"

[[program.input]]
key = "vol3"
label = "Volume"
help = "Nanoparticle volume to use for lattice fitting"
placeholder = "input volume 4 lattice fit e.g. vol3.mrc"
visibility = "developer"

[[program.input]]
key = "smpd"
label = "Sampling distance"
help = "Distance between neighbouring pixels in Angstroms"
placeholder = "pixel size in Angstroms"
visibility = "developer"

[[program.input]]
key = "pdbfile"
label = "PDB"
help = "Input coords file in PDB format"
placeholder = "Input coords file in PDB format"
visibility = "developer"

[[program.input]]
key = "pdbfile2"
label = "PDB"
help = "subset coords for stats calc"
placeholder = "subset coords file in PDB format for stats calc"
visibility = "developer"

[[program.input]]
key = "rmsd_file"
label = "bin"
help = "per-atom e/o rmsd:s"
placeholder = "per-atom e/o rmsd:s from CS model building"
visibility = "developer"

[[program.input]]
key = "element"
label = "Atom element name: Au, Pt etc."
help = "Atom element name: Au, Pt etc."
placeholder = "atom composition e.g. Pt"
visibility = "developer"

[[program.input]]
key = "nthr"
label = "Number of threads per computing node, give 0 if unsure"
help = "Number of shared-memory OpenMP threads with close affinity per partition. Typically the same as the number of logical threads in a socket."
placeholder = "# shared-memory CPU threads"
visibility = "developer"

[[program]]
name = "core_atoms_analysis"
executable = "single_exec"
display_name = "Analysis of results obtianed with trajectory_reconstruct3D and detect_atoms"
summary = "Analysis of results obtianed with trajectory_reconstruct3D and detect_atoms"
help = "is a program that analysis atomic time-series coordinates"

[[program.input]]
key = "smpd"
label = "Sampling distance"
help = "Distance between neighbouring pixels in Angstroms"
placeholder = "pixel size in Angstroms"
visibility = "developer"

[[program.input]]
key = "pdbfiles"
label = "txt"
help = "List of PDB format coords files"
placeholder = "List of input coords files in PDB format"
visibility = "developer"

[[program.input]]
key = "frac_diam"
label = "Fraction of atomic diameter"
help = "Fraction of atomic diameter used for thresholding{0.5}"
placeholder = "{0.5}"
visibility = "developer"

[[program.input]]
key = "element"
label = "Atom element name: Au, Pt etc."
help = "Atom element name: Au, Pt etc."
placeholder = "atom composition e.g. Pt"
visibility = "developer"

[[program]]
name = "crys_score"
executable = "single_exec"
display_name = "Computing crystal score"
summary = "Computing crystal score"
help = "is a program that computes crystal score."

[[program.input]]
key = "fname"
label = "PDB file list"
help = "PDB file list"
placeholder = "e.g. np_pdbs.txt"
visibility = "developer"

[[program.input]]
key = "smpd"
label = "Sampling distance"
help = "Distance between neighbouring pixels in Angstroms"
placeholder = "pixel size in Angstroms"
visibility = "developer"

[[program.input]]
key = "box"
label = "Particle box size"
help = "Particle box size(in pixels)"
placeholder = "# pixels of box"
visibility = "developer"

[[program.input]]
key = "element"
label = "Atom element name: Au, Pt etc."
help = "Atom element name: Au, Pt etc."
placeholder = "atom composition e.g. Pt"
visibility = "developer"

[[program.input]]
key = "nthr"
label = "Number of threads per computing node, give 0 if unsure"
help = "Number of shared-memory OpenMP threads with close affinity per partition. Typically the same as the number of logical threads in a socket."
placeholder = "# shared-memory CPU threads"
visibility = "developer"

[[program]]
name = "detect_atoms"
executable = "single_exec"
display_name = "Detect atoms in atomic-resolution nanoparticle map"
summary = "Detect atoms in atomic-resolution nanoparticle map"
help = "is a program for identifying atoms in atomic-resolution nanoparticle maps and generating bin and connected-components map"

[[program.input]]
key = "vol1"
label = "Volume"
help = "Nanoparticle volume to analyse"
placeholder = "input volume e.g. vol.mrc"
visibility = "developer"

[[program.input]]
key = "smpd"
label = "Sampling distance"
help = "Distance between neighbouring pixels in Angstroms"
placeholder = "pixel size in Angstroms"
visibility = "developer"

[[program.input]]
key = "element"
label = "Atom element name: Au, Pt etc."
help = "Atom element name: Au, Pt etc."
placeholder = "atom composition e.g. Pt"
visibility = "developer"

[[program.input]]
key = "mskdiam"
label = "Mask diameter"
help = "Mask diameter (in A) for application of a soft-edged circular mask to remove background noise"
placeholder = "mask diameter in A"
visibility = "developer"

[[program.input]]
key = "nthr"
label = "Number of threads per computing node, give 0 if unsure"
help = "Number of shared-memory OpenMP threads with close affinity per partition. Typically the same as the number of logical threads in a socket."
placeholder = "# shared-memory CPU threads"
visibility = "developer"

[[program]]
name = "simulate_nanoparticle"
executable = "single_exec"
display_name = "Simulate nanoparticle for lattice density"
summary = "Simulate nanoparticle for lattice density"
help = "is a program for simulation of nanoparticle for lattice density"

[[program.input]]
key = "pdbfile"
label = "PDB"
help = "Input coordinates file in PDB format"
placeholder = "Input coordinates file"
visibility = "developer"

[[program.input]]
key = "outvol"
label = "Output volume name"
help = "Output volume name"
placeholder = "e.g. outvol.mrc"
visibility = "developer"

[[program.input]]
key = "smpd"
label = "Sampling distance"
help = "Distance between neighbouring pixels in Angstroms"
placeholder = "pixel size in Angstroms"
visibility = "developer"

[[program.input]]
key = "box"
label = "Particle box size"
help = "Particle box size(in pixels)"
placeholder = "# pixels of box"
visibility = "developer"

[[program.input]]
key = "element"
label = "Atom element name: Au, Pt etc."
help = "Atom element name: Au, Pt etc."
placeholder = "atom composition e.g. Pt"
visibility = "developer"

[[program.input]]
key = "moldiam"
label = "Molecular diameter"
help = "Molecular diameter(in Angstroms)"
placeholder = "In Angstroms"
visibility = "developer"

[[program.input]]
key = "nthr"
label = "Number of threads per computing node, give 0 if unsure"
help = "Number of shared-memory OpenMP threads with close affinity per partition. Typically the same as the number of logical threads in a socket."
placeholder = "# shared-memory CPU threads"
visibility = "developer"
