/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * SimplePreProcPanel.java
 *
 * Created on 16/11/2015, 10:55:59 PM
 */

package edu.kit.gridbeans.simplepreproc.plugin;

import com.intel.gpe.clients.api.Client;
import com.intel.gpe.gridbeans.plugins.DataSetException;
import com.intel.gpe.gridbeans.plugins.swing.panels.GridBeanPanel;
import com.intel.gpe.util.defaults.preferences.INode;

/**
 *
 * @author Frederic Bonnet
 * @Data 16th of November 2015
 * 
 */
public class SimplePreProcPanel extends GridBeanPanel {

    /**
	 * Add UID
	 */
	private static final long serialVersionUID = -802581495982322685L;


	/** Creates new form SimplePreProcPanel */
    public SimplePreProcPanel(Client client, INode node) {
    	super(client, "SimplePreProc", node);
    	  initComponents();
    	  try {
    	  initTab();
    	  } catch (DataSetException e) {
    		  getClient().showException("error creating SimplePreProc Panel", e);
    	  }
    }
    
    private void initTab() throws DataSetException{
		// TODO Auto-generated method stub
		WelcomePreProcJPanel welcomePreProcjpanel = new WelcomePreProcJPanel(this);
		PreProcJPanel preProcPanel = new PreProcJPanel(this);
		
		mainSimplePreProcjTabbedPanel.addTab("0. Start here, general options", welcomePreProcjpanel);
		mainSimplePreProcjTabbedPanel.addTab("1. Pre-Processing Panel", preProcPanel);
	}

	/** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainSimplePreProcjTabbedPanel = new javax.swing.JTabbedPane();

        setLayout(new java.awt.BorderLayout());
        add(mainSimplePreProcjTabbedPanel, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane mainSimplePreProcjTabbedPanel;
    // End of variables declaration//GEN-END:variables

}
