/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * WelcomeJPanel.java
 *
 * Created on 18/11/2015, 1:51:13 PM
 */

package edu.kit.gridbeans.simplepreproc.plugin;

import java.awt.event.ItemEvent;

import javax.swing.JPanel;

import com.intel.gpe.gridbeans.parameters.EnvironmentVariableParameterValue;
import com.intel.gpe.gridbeans.plugins.DataSetException;
import com.intel.gpe.gridbeans.plugins.swing.panels.GridBeanPanel;

import edu.kit.gridbeans.simplepreproc.SimplePreProcGridBean;

/**
 *
 * @author frederic
 */
public class WelcomePreProcJPanel extends JPanel {
    private GridBeanPanel parentPanel;

    /**
     * Add UID
     */
    private static final long serialVersionUID = 768688909032151147L;
    /** Creates new form WelcomeJPanel */
    public WelcomePreProcJPanel(GridBeanPanel parentpanel) throws DataSetException {
        this.parentPanel = parentpanel;
        initComponents();
        initCustomComponents();
        bindComponents();
    }

    private void initCustomComponents() {
        // TODO Auto-generated method stub
        haveBoxfilebuttonGroup.add(haveBoxfileRadioButton);
        haveBoxfilebuttonGroup.add(noBoxfileRadioButton);
    }

    private void bindComponents() {
        // TODO Auto-generated method stub
        
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        haveBoxfilebuttonGroup = new javax.swing.ButtonGroup();
        mainWelcomePreProcScrollPanel = new javax.swing.JScrollPane();
        mainWelcomePreProcPanel = new javax.swing.JPanel();
        graphicWelcomPreProcPanel = new javax.swing.JPanel();
        generalOptionsPreProcPanel = new javax.swing.JPanel();
        haveBoxfileRadioButton = new javax.swing.JRadioButton();
        noBoxfileRadioButton = new javax.swing.JRadioButton();
        infoWelcomePreProcScrollPanel = new javax.swing.JScrollPane();
        infoWelcomeTextArea = new javax.swing.JTextArea();
        contributorsButton = new javax.swing.JButton();
        refreshTextAreaButton = new javax.swing.JButton();
        helpWelcomeButton = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout());

        graphicWelcomPreProcPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(-16777216,true)));

        javax.swing.GroupLayout graphicWelcomPreProcPanelLayout = new javax.swing.GroupLayout(graphicWelcomPreProcPanel);
        graphicWelcomPreProcPanel.setLayout(graphicWelcomPreProcPanelLayout);
        graphicWelcomPreProcPanelLayout.setHorizontalGroup(
            graphicWelcomPreProcPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 533, Short.MAX_VALUE)
        );
        graphicWelcomPreProcPanelLayout.setVerticalGroup(
            graphicWelcomPreProcPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 47, Short.MAX_VALUE)
        );

        haveBoxfileRadioButton.setText("Have the Boxfile");
        haveBoxfileRadioButton.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                haveBoxfileRadioButtonItemStateChanged(evt);
            }
        });
        haveBoxfileRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                haveBoxfileRadioButtonActionPerformed(evt);
            }
        });

        noBoxfileRadioButton.setText("Do not have Boxfile");
        noBoxfileRadioButton.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                noBoxfileRadioButtonItemStateChanged(evt);
            }
        });
        noBoxfileRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                noBoxfileRadioButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout generalOptionsPreProcPanelLayout = new javax.swing.GroupLayout(generalOptionsPreProcPanel);
        generalOptionsPreProcPanel.setLayout(generalOptionsPreProcPanelLayout);
        generalOptionsPreProcPanelLayout.setHorizontalGroup(
            generalOptionsPreProcPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(generalOptionsPreProcPanelLayout.createSequentialGroup()
                .addComponent(haveBoxfileRadioButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(noBoxfileRadioButton)
                .addContainerGap(296, Short.MAX_VALUE))
        );
        generalOptionsPreProcPanelLayout.setVerticalGroup(
            generalOptionsPreProcPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(generalOptionsPreProcPanelLayout.createSequentialGroup()
                .addGroup(generalOptionsPreProcPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(haveBoxfileRadioButton)
                    .addComponent(noBoxfileRadioButton))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        infoWelcomeTextArea.setColumns(20);
        infoWelcomeTextArea.setRows(5);
        infoWelcomePreProcScrollPanel.setViewportView(infoWelcomeTextArea);

        contributorsButton.setText("Contributors");
        contributorsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contributorsButtonActionPerformed(evt);
            }
        });

        refreshTextAreaButton.setText("Refresh");
        refreshTextAreaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshTextAreaButtonActionPerformed(evt);
            }
        });

        helpWelcomeButton.setText("Help");
        helpWelcomeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                helpWelcomeButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout mainWelcomePreProcPanelLayout = new javax.swing.GroupLayout(mainWelcomePreProcPanel);
        mainWelcomePreProcPanel.setLayout(mainWelcomePreProcPanelLayout);
        mainWelcomePreProcPanelLayout.setHorizontalGroup(
            mainWelcomePreProcPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainWelcomePreProcPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(mainWelcomePreProcPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mainWelcomePreProcPanelLayout.createSequentialGroup()
                        .addComponent(contributorsButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(refreshTextAreaButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 369, Short.MAX_VALUE)
                        .addComponent(helpWelcomeButton))
                    .addComponent(generalOptionsPreProcPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(infoWelcomePreProcScrollPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 535, Short.MAX_VALUE)
                    .addComponent(graphicWelcomPreProcPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(218, 218, 218))
        );
        mainWelcomePreProcPanelLayout.setVerticalGroup(
            mainWelcomePreProcPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainWelcomePreProcPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(graphicWelcomPreProcPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(generalOptionsPreProcPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(infoWelcomePreProcScrollPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(mainWelcomePreProcPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(contributorsButton)
                    .addComponent(refreshTextAreaButton)
                    .addComponent(helpWelcomeButton))
                .addContainerGap(119, Short.MAX_VALUE))
        );

        mainWelcomePreProcScrollPanel.setViewportView(mainWelcomePreProcPanel);

        add(mainWelcomePreProcScrollPanel, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void haveBoxfileRadioButtonItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_haveBoxfileRadioButtonItemStateChanged
        if (evt.getStateChange() == ItemEvent.SELECTED) {
            infoWelcomeTextArea.append("Starting wiht the Boxfile in dir Boxfile.");
            infoWelcomeTextArea.append("\n");
        } else if (evt.getStateChange() == ItemEvent.DESELECTED ) {
            infoWelcomeTextArea.append("Will not be starting wiht the Boxfile you need to particle pick and create the *.box and then copy those in a directory called Boxfile.");
            infoWelcomeTextArea.append("\n");
        }
    }//GEN-LAST:event_haveBoxfileRadioButtonItemStateChanged
    private void haveBoxfileRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_haveBoxfileRadioButtonActionPerformed
        EnvironmentVariableParameterValue value = new EnvironmentVariableParameterValue("1");
        parentPanel.getGridBeanModel().set(SimplePreProcGridBean.HAVE_BOXFILE, value);
    }//GEN-LAST:event_haveBoxfileRadioButtonActionPerformed
    private void noBoxfileRadioButtonItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_noBoxfileRadioButtonItemStateChanged
        if (evt.getStateChange() == ItemEvent.SELECTED) {
            infoWelcomeTextArea.append("Starting without the Boxfile, the first step the still frames will be rotated by 90 degrees to match the movies orientations.");
            infoWelcomeTextArea.append("\n");
        } else if (evt.getStateChange() == ItemEvent.DESELECTED ) {
            infoWelcomeTextArea.append("Will be starting with the Boxfiles, make sure that the files have been saved in a directory called Boxfile.");
            infoWelcomeTextArea.append("\n");
        }
    }//GEN-LAST:event_noBoxfileRadioButtonItemStateChanged
    private void noBoxfileRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_noBoxfileRadioButtonActionPerformed
        EnvironmentVariableParameterValue value = new EnvironmentVariableParameterValue("0");
        parentPanel.getGridBeanModel().set(SimplePreProcGridBean.HAVE_BOXFILE, value);
    }//GEN-LAST:event_noBoxfileRadioButtonActionPerformed
    private void contributorsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contributorsButtonActionPerformed
        /**
         * Add a contributor splash screen
         */
        ContributorSplashScreen contributors = new ContributorSplashScreen();
        contributors.setVisible(true);
    }//GEN-LAST:event_contributorsButtonActionPerformed
    private void refreshTextAreaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshTextAreaButtonActionPerformed
        infoWelcomeTextArea.setText("");
    }//GEN-LAST:event_refreshTextAreaButtonActionPerformed
    private void helpWelcomeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_helpWelcomeButtonActionPerformed
        /**
         * add the help window in the welcome Panel
         */
        HelpWelcomeSimple helpwindowinWelcomePanel = new HelpWelcomeSimple();
        helpwindowinWelcomePanel.setVisible(true);
    }//GEN-LAST:event_helpWelcomeButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton contributorsButton;
    private javax.swing.JPanel generalOptionsPreProcPanel;
    private javax.swing.JPanel graphicWelcomPreProcPanel;
    private javax.swing.JRadioButton haveBoxfileRadioButton;
    private javax.swing.ButtonGroup haveBoxfilebuttonGroup;
    private javax.swing.JButton helpWelcomeButton;
    private javax.swing.JScrollPane infoWelcomePreProcScrollPanel;
    private javax.swing.JTextArea infoWelcomeTextArea;
    private javax.swing.JPanel mainWelcomePreProcPanel;
    private javax.swing.JScrollPane mainWelcomePreProcScrollPanel;
    private javax.swing.JRadioButton noBoxfileRadioButton;
    private javax.swing.JButton refreshTextAreaButton;
    // End of variables declaration//GEN-END:variables

}
