# OTHER UTILITIES
suite_id = "simple_exec"
group_id = "other-utilities"
group_title = "OTHER UTILITIES"
group_order = 190

[[program]]
name = "cif2pdb"
executable = "simple_exec"
display_name = "convert PDBx/mmCIF to PDB"
summary = "convert PDBx/mmCIF to PDB"
help = "is a program for converting PDBx/mmCIF to PDB"
visibility = "developer"

[[program.input]]
key = "ciffile"
label = "PDBx/mmCIF input coordinates file"
help = "Input coordinates file in PDBx/mmCIF format"
placeholder = "PDBx/mmCIF file e.g. molecule.cif"
visibility = "developer"

[[program]]
name = "fractionate_movies"
executable = "simple_exec"
display_name = "Re-generate micrographs from selected movie frames"
summary = "Re-generate micrographs from selected movie frames"
help = "is a distributed program for re-generating micrographs from a subset of movie frames"
visibility = "developer"

[[program.input]]
key = "fromf"
label = "Starting frame"
help = "Starting movie frame for micrograph re-generation"
placeholder = "frame index{1}"
visibility = "developer"

[[program.input]]
key = "tof"
label = "Final frame"
help = "Final movie frame for micrograph re-generation(0=all)"
placeholder = "frame index{0}"
visibility = "developer"

[[program.input]]
key = "flipgain"
label = "Flip the gain reference"
help = "Flip the gain reference along the provided axis(no|x|y|xy|yx){no}"
placeholder = "(no|x|y|xy|yx){no}"
visibility = "developer"
choices = ["no", "x", "y", "xy", "yx"]

[[program.input]]
key = "mcconvention"
label = "Movie alignment convention"
help = "Movie alignment and naming convention(simple|unblur|relion|motioncorr|cryosparc|cs){simple}"
placeholder = "(simple|unblur|relion|motioncorr|cryosparc|cs){simple}"
visibility = "developer"

[[program.input]]
key = "nparts"
label = "Number of computing nodes"
help = "Number of partitions for distributed memory execution. One part typically corresponds to one CPU socket in the distributed system. On a single-socket machine there may be speed benefits to dividing the jobs into a few (2-4) partitions, depending on memory capacity"
placeholder = "divide job into # parts"
visibility = "developer"

[[program.input]]
key = "nthr"
label = "Number of threads per computing node, give 0 if unsure"
help = "Number of shared-memory OpenMP threads with close affinity per partition. Typically the same as the number of logical threads in a socket."
placeholder = "# shared-memory CPU threads"
visibility = "developer"

[[program]]
name = "split"
executable = "simple_exec"
display_name = "Split stack into substacks"
summary = "Split stack into substacks"
help = "is a program for splitting a stack into evenly partitioned substacks"
visibility = "developer"

[[program.input]]
key = "stk"
label = "Particle image stack"
help = "Particle image stack"
placeholder = "xxx.mrc file with particles"
visibility = "developer"

[[program.input]]
key = "smpd"
label = "Sampling distance"
help = "Distance between neighbouring pixels in Angstroms"
placeholder = "pixel size in Angstroms"
visibility = "developer"

[[program.input]]
key = "nparts"
label = "Number of computing nodes"
help = "Number of partitions for distributed memory execution. One part typically corresponds to one CPU socket in the distributed system. On a single-socket machine there may be speed benefits to dividing the jobs into a few (2-4) partitions, depending on memory capacity"
placeholder = "divide job into # parts"
visibility = "developer"

[[program]]
name = "split_stack"
executable = "simple_exec"
display_name = "split stack in project"
summary = "split stack in project"
help = "is a program for splitting a stack into nparts substacks"
visibility = "developer"

[[program.input]]
key = "nparts"
label = "Number of parts balanced splitting of the stack"
help = "# parts"
placeholder = "# parts"
visibility = "developer"
