/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * SimpleStackopsPanel.java
 *
 * Created on 17/11/2015, 1:34:28 PM
 */

package edu.kit.gridbeans.simplestackops.plugin;

import com.intel.gpe.clients.api.Client;
import com.intel.gpe.gridbeans.plugins.DataSetException;
import com.intel.gpe.gridbeans.plugins.swing.panels.GridBeanPanel;
import com.intel.gpe.util.defaults.preferences.INode;

/**
 *
 * @author Frederic Bonnet
 * @Date 17th of November 2015
 */
public class SimpleStackopsPanel extends GridBeanPanel {

    /**
	 * Add UID
	 */
	private static final long serialVersionUID = 2731158914213264827L;

	/** Creates new form SimpleStackopsPanel */
    public SimpleStackopsPanel(Client client, INode node) {
    	super(client, "SimpleStackops", node);
        initComponents();
        try {
			initTab();
		} catch (DataSetException e) {
			getClient().showException("error creating Simple Stackops Panel", e);
			e.printStackTrace();
		}
    }

    private void initTab() throws DataSetException {
		// TODO Auto-generated method stub
		WelcomeStackopsJPanel welcomeStackopspanel = new WelcomeStackopsJPanel(this);
		SimpleStackopsJPanel simpleStackopspanel = new SimpleStackopsJPanel(this);
		PerformanceStackopsJPanel performanceStackopsPanel = new PerformanceStackopsJPanel(this);
		
		mainSimpleStackopsjTabbedPanel.addTab("0. Welcome stack operation panel", welcomeStackopspanel);
		mainSimpleStackopsjTabbedPanel.addTab("1. simple_stackops panel", simpleStackopspanel);
		mainSimpleStackopsjTabbedPanel.addTab("2. Performance stackops panel", performanceStackopsPanel);
	}

	/** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainSimpleStackopsjTabbedPanel = new javax.swing.JTabbedPane();

        setLayout(new java.awt.BorderLayout());
        add(mainSimpleStackopsjTabbedPanel, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane mainSimpleStackopsjTabbedPanel;
    // End of variables declaration//GEN-END:variables

}
