/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * WelcomeStackopsJPanel.java
 *
 * Created on 23/11/2015, 10:07:25 PM
 */

package edu.kit.gridbeans.simplestackops.plugin;

import com.intel.gpe.gridbeans.plugins.DataSetException;
import com.intel.gpe.gridbeans.plugins.swing.panels.GridBeanPanel;

/**
 *
 * @author frederic
 */
public class WelcomeStackopsJPanel extends javax.swing.JPanel {
    private GridBeanPanel parentPanel;
    /**
     * Add UID
     */
    private static final long serialVersionUID = -2565620642593238412L;
    /** Creates new form WelcomeStackopsJPanel */
    public WelcomeStackopsJPanel(GridBeanPanel parentpanel) throws DataSetException {
        this.parentPanel = parentpanel;
        initComponents();
        initCustomComponents();
        bindComponents();
    }

    private void initCustomComponents() {
        // TODO Auto-generated method stub
        
    }

    private void bindComponents() {
        // TODO Auto-generated method stub
        
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainWelcomeStackopsScrollPanel = new javax.swing.JScrollPane();
        mainWelcomeEoRecVolPanel = new javax.swing.JPanel();
        graphicWelcomEoRecVolPanel = new javax.swing.JPanel();
        generalOptionsEoRecVolPanel = new javax.swing.JPanel();
        infoWelcomeEoRecVolScrollPanel = new javax.swing.JScrollPane();
        infoWelcomeTextArea = new javax.swing.JTextArea();
        contributorsButton = new javax.swing.JButton();
        refreshTextAreaButton = new javax.swing.JButton();
        helpWelcomeEoRecVolButton = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout());

        graphicWelcomEoRecVolPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(-16777216,true)));

        javax.swing.GroupLayout graphicWelcomEoRecVolPanelLayout = new javax.swing.GroupLayout(graphicWelcomEoRecVolPanel);
        graphicWelcomEoRecVolPanel.setLayout(graphicWelcomEoRecVolPanelLayout);
        graphicWelcomEoRecVolPanelLayout.setHorizontalGroup(
            graphicWelcomEoRecVolPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 533, Short.MAX_VALUE)
        );
        graphicWelcomEoRecVolPanelLayout.setVerticalGroup(
            graphicWelcomEoRecVolPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 47, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout generalOptionsEoRecVolPanelLayout = new javax.swing.GroupLayout(generalOptionsEoRecVolPanel);
        generalOptionsEoRecVolPanel.setLayout(generalOptionsEoRecVolPanelLayout);
        generalOptionsEoRecVolPanelLayout.setHorizontalGroup(
            generalOptionsEoRecVolPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 535, Short.MAX_VALUE)
        );
        generalOptionsEoRecVolPanelLayout.setVerticalGroup(
            generalOptionsEoRecVolPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 36, Short.MAX_VALUE)
        );

        infoWelcomeTextArea.setColumns(20);
        infoWelcomeTextArea.setRows(5);
        infoWelcomeEoRecVolScrollPanel.setViewportView(infoWelcomeTextArea);

        contributorsButton.setText("Contributors");
        contributorsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contributorsButtonActionPerformed(evt);
            }
        });

        refreshTextAreaButton.setText("Refresh");
        refreshTextAreaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshTextAreaButtonActionPerformed(evt);
            }
        });

        helpWelcomeEoRecVolButton.setText("Help");
        helpWelcomeEoRecVolButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                helpWelcomeEoRecVolButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout mainWelcomeEoRecVolPanelLayout = new javax.swing.GroupLayout(mainWelcomeEoRecVolPanel);
        mainWelcomeEoRecVolPanel.setLayout(mainWelcomeEoRecVolPanelLayout);
        mainWelcomeEoRecVolPanelLayout.setHorizontalGroup(
            mainWelcomeEoRecVolPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainWelcomeEoRecVolPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(mainWelcomeEoRecVolPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mainWelcomeEoRecVolPanelLayout.createSequentialGroup()
                        .addComponent(contributorsButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(refreshTextAreaButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 369, Short.MAX_VALUE)
                        .addComponent(helpWelcomeEoRecVolButton))
                    .addComponent(generalOptionsEoRecVolPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(infoWelcomeEoRecVolScrollPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 535, Short.MAX_VALUE)
                    .addComponent(graphicWelcomEoRecVolPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(218, 218, 218))
        );
        mainWelcomeEoRecVolPanelLayout.setVerticalGroup(
            mainWelcomeEoRecVolPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainWelcomeEoRecVolPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(graphicWelcomEoRecVolPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(generalOptionsEoRecVolPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(infoWelcomeEoRecVolScrollPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(mainWelcomeEoRecVolPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(contributorsButton)
                    .addComponent(refreshTextAreaButton)
                    .addComponent(helpWelcomeEoRecVolButton))
                .addContainerGap(124, Short.MAX_VALUE))
        );

        mainWelcomeStackopsScrollPanel.setViewportView(mainWelcomeEoRecVolPanel);

        add(mainWelcomeStackopsScrollPanel, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void contributorsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contributorsButtonActionPerformed
        /**
         * Add a contributor splash screen
         */
        ContributorSplashScreen contributors = new ContributorSplashScreen();
        contributors.setVisible(true);
}//GEN-LAST:event_contributorsButtonActionPerformed

    private void refreshTextAreaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshTextAreaButtonActionPerformed
        infoWelcomeTextArea.setText("");
}//GEN-LAST:event_refreshTextAreaButtonActionPerformed

    private void helpWelcomeEoRecVolButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_helpWelcomeEoRecVolButtonActionPerformed
        /**
         * add the help window in the welcome Panel
         */
        HelpWelcomeStackopsSimple helpwindowinWelcomePanel = new HelpWelcomeStackopsSimple();
        helpwindowinWelcomePanel.setVisible(true);
}//GEN-LAST:event_helpWelcomeEoRecVolButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton contributorsButton;
    private javax.swing.JPanel generalOptionsEoRecVolPanel;
    private javax.swing.JPanel graphicWelcomEoRecVolPanel;
    private javax.swing.JButton helpWelcomeEoRecVolButton;
    private javax.swing.JScrollPane infoWelcomeEoRecVolScrollPanel;
    private javax.swing.JTextArea infoWelcomeTextArea;
    private javax.swing.JPanel mainWelcomeEoRecVolPanel;
    private javax.swing.JScrollPane mainWelcomeStackopsScrollPanel;
    private javax.swing.JButton refreshTextAreaButton;
    // End of variables declaration//GEN-END:variables

}
