package edu.kit.gridbeans.simpleeorecvol.plugin;

import com.intel.gpe.clients.api.Client;
import com.intel.gpe.gridbeans.plugins.DataSetException;
import com.intel.gpe.gridbeans.plugins.swing.panels.GridBeanPanel;
import com.intel.gpe.gridbeans.plugins.translators.StringValueTranslator;
import com.intel.gpe.gridbeans.plugins.validators.NonEmptyStringValidator;
import com.intel.gpe.util.defaults.preferences.INode;

import edu.kit.gridbeans.simpleeorecvol.SimpleEoRecVolGridBean;

public class ParameterPanel extends GridBeanPanel {

	/**
     * Add UID
     */
    private static final long serialVersionUID = 2277783033757788833L;
    public ParameterPanel(Client client, INode node) throws DataSetException {
		super(client, "Parameter", node);
		initComponents();
		linkComponents();
	}

	private void linkComponents() throws DataSetException {
		linkTextField(SimpleEoRecVolGridBean.TITLE, tfdTitle);
		setValueTranslator(SimpleEoRecVolGridBean.TITLE, new StringValueTranslator());
		setValueValidator(SimpleEoRecVolGridBean.TITLE, new NonEmptyStringValidator());
		
	}
	
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        tfdTitle = new javax.swing.JTextField();

        lblTitle.setText("Title");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tfdTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(260, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTitle)
                    .addComponent(tfdTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(269, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblTitle;
    private javax.swing.JTextField tfdTitle;
    // End of variables declaration//GEN-END:variables
}
