/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * PerformanceJPanel.java
 *
 * Created on 20/11/2015, 1:21:45 PM
 */

package edu.kit.gridbeans.simpleeorecvol.plugin;

import com.intel.gpe.gridbeans.plugins.DataSetException;
import com.intel.gpe.gridbeans.plugins.swing.panels.GridBeanPanel;

/**
 *
 * @author Frederic Bonnet
 * @date 20th of November 2015
 * 
 */
public class PerformanceJPanel extends javax.swing.JPanel {
    private GridBeanPanel parentPanel;
    /**
     * Add UID
     */
    private static final long serialVersionUID = 8281579346735804351L;
    /** Creates new form PerformanceJPanel */
    public PerformanceJPanel(GridBeanPanel parentpanel) throws DataSetException {
        this.parentPanel = parentpanel;
        initComponents();
        initCustomComponents();// custom code by us
        bindComponents();
    }

    private void initCustomComponents() {
        // TODO Auto-generated method stub
        
    }

    private void bindComponents() {
        // TODO Auto-generated method stub
        
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        openMPbuttonGroup = new javax.swing.ButtonGroup();
        gpubuttonGroup = new javax.swing.ButtonGroup();
        whichGPUEnvbuttonGroup = new javax.swing.ButtonGroup();
        mainPerformanceEoRecVolScrollPanel = new javax.swing.JScrollPane();
        mainPerformanceEoRecVolPanel = new javax.swing.JPanel();
        openMPPanel = new javax.swing.JPanel();
        useOpenMPRadioButton = new javax.swing.JRadioButton();
        threadsPerSocketLabel = new javax.swing.JLabel();
        nthrThreadsPerSocketTextField = new javax.swing.JTextField();
        GPUPanel = new javax.swing.JPanel();
        useGPURadioButton = new javax.swing.JRadioButton();
        gpuEnvPanel = new javax.swing.JPanel();
        useCUDACRadioButton = new javax.swing.JRadioButton();
        openCLRadioButton = new javax.swing.JRadioButton();
        dataDistributionPanel = new javax.swing.JPanel();
        npartLabel = new javax.swing.JLabel();
        npartTextField = new javax.swing.JTextField();

        setLayout(new java.awt.BorderLayout());

        openMPPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "OpenMP configuration...", 0, 0, null, new java.awt.Color(-16776961,true)));

        useOpenMPRadioButton.setText("Use OpenMP");

        threadsPerSocketLabel.setText("Threads/socket nthr:");

        javax.swing.GroupLayout openMPPanelLayout = new javax.swing.GroupLayout(openMPPanel);
        openMPPanel.setLayout(openMPPanelLayout);
        openMPPanelLayout.setHorizontalGroup(
            openMPPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(openMPPanelLayout.createSequentialGroup()
                .addComponent(useOpenMPRadioButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(threadsPerSocketLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nthrThreadsPerSocketTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        openMPPanelLayout.setVerticalGroup(
            openMPPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(openMPPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(useOpenMPRadioButton)
                .addComponent(threadsPerSocketLabel)
                .addComponent(nthrThreadsPerSocketTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        GPUPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "GPU details...", 0, 0, null, new java.awt.Color(-16776961,true)));

        useGPURadioButton.setText("Use GPU");

        gpuEnvPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "GPU environment...", 0, 0, null, new java.awt.Color(-65281,true)));

        useCUDACRadioButton.setText("CUDA C");

        openCLRadioButton.setText("OpenCL");

        javax.swing.GroupLayout gpuEnvPanelLayout = new javax.swing.GroupLayout(gpuEnvPanel);
        gpuEnvPanel.setLayout(gpuEnvPanelLayout);
        gpuEnvPanelLayout.setHorizontalGroup(
            gpuEnvPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(gpuEnvPanelLayout.createSequentialGroup()
                .addComponent(useCUDACRadioButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(openCLRadioButton)
                .addContainerGap(12, Short.MAX_VALUE))
        );
        gpuEnvPanelLayout.setVerticalGroup(
            gpuEnvPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(gpuEnvPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(useCUDACRadioButton)
                .addComponent(openCLRadioButton))
        );

        javax.swing.GroupLayout GPUPanelLayout = new javax.swing.GroupLayout(GPUPanel);
        GPUPanel.setLayout(GPUPanelLayout);
        GPUPanelLayout.setHorizontalGroup(
            GPUPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(GPUPanelLayout.createSequentialGroup()
                .addComponent(useGPURadioButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(gpuEnvPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(50, Short.MAX_VALUE))
        );
        GPUPanelLayout.setVerticalGroup(
            GPUPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(useGPURadioButton)
            .addGroup(GPUPanelLayout.createSequentialGroup()
                .addGap(3, 3, 3)
                .addComponent(gpuEnvPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        dataDistributionPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Data distribution over the resources...", 0, 0, null, new java.awt.Color(-16776961,true)));

        npartLabel.setText("Data distribution over the nodes npart:");

        javax.swing.GroupLayout dataDistributionPanelLayout = new javax.swing.GroupLayout(dataDistributionPanel);
        dataDistributionPanel.setLayout(dataDistributionPanelLayout);
        dataDistributionPanelLayout.setHorizontalGroup(
            dataDistributionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dataDistributionPanelLayout.createSequentialGroup()
                .addComponent(npartLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(npartTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
                .addContainerGap())
        );
        dataDistributionPanelLayout.setVerticalGroup(
            dataDistributionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dataDistributionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(npartLabel)
                .addComponent(npartTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout mainPerformanceEoRecVolPanelLayout = new javax.swing.GroupLayout(mainPerformanceEoRecVolPanel);
        mainPerformanceEoRecVolPanel.setLayout(mainPerformanceEoRecVolPanelLayout);
        mainPerformanceEoRecVolPanelLayout.setHorizontalGroup(
            mainPerformanceEoRecVolPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPerformanceEoRecVolPanelLayout.createSequentialGroup()
                .addGroup(mainPerformanceEoRecVolPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(GPUPanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(dataDistributionPanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(openMPPanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(345, Short.MAX_VALUE))
        );
        mainPerformanceEoRecVolPanelLayout.setVerticalGroup(
            mainPerformanceEoRecVolPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPerformanceEoRecVolPanelLayout.createSequentialGroup()
                .addComponent(dataDistributionPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(openMPPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(GPUPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(427, Short.MAX_VALUE))
        );

        mainPerformanceEoRecVolScrollPanel.setViewportView(mainPerformanceEoRecVolPanel);

        add(mainPerformanceEoRecVolScrollPanel, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel GPUPanel;
    private javax.swing.JPanel dataDistributionPanel;
    private javax.swing.JPanel gpuEnvPanel;
    private javax.swing.ButtonGroup gpubuttonGroup;
    private javax.swing.JPanel mainPerformanceEoRecVolPanel;
    private javax.swing.JScrollPane mainPerformanceEoRecVolScrollPanel;
    private javax.swing.JLabel npartLabel;
    private javax.swing.JTextField npartTextField;
    private javax.swing.JTextField nthrThreadsPerSocketTextField;
    private javax.swing.JRadioButton openCLRadioButton;
    private javax.swing.JPanel openMPPanel;
    private javax.swing.ButtonGroup openMPbuttonGroup;
    private javax.swing.JLabel threadsPerSocketLabel;
    private javax.swing.JRadioButton useCUDACRadioButton;
    private javax.swing.JRadioButton useGPURadioButton;
    private javax.swing.JRadioButton useOpenMPRadioButton;
    private javax.swing.ButtonGroup whichGPUEnvbuttonGroup;
    // End of variables declaration//GEN-END:variables

}
