/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * simpleEoRecVolPanel.java
 *
 * Created on 17/11/2015, 1:29:41 PM
 */

package edu.kit.gridbeans.simpleeorecvol.plugin;

import com.intel.gpe.clients.api.Client;
import com.intel.gpe.gridbeans.plugins.DataSetException;
import com.intel.gpe.gridbeans.plugins.swing.panels.GridBeanPanel;
import com.intel.gpe.util.defaults.preferences.INode;

/**
 *
 * @author Frederic Bonnet
 * @Date 17th of November 2015
 */
public class SimpleEoRecVolPanel extends GridBeanPanel {

    /**
	 * Add UID
	 */
	private static final long serialVersionUID = -3593651354760964982L;

	/** Creates new form simpleEoRecVolPanel */
    public SimpleEoRecVolPanel(Client client, INode node) {
    	super(client, "SimpleEoRecVol", node);
        initComponents();
        try {
			initTab();
		} catch (DataSetException e) {
            getClient().showException("error creating Simple EoRecVol Panel", e);
			e.printStackTrace();
		}
    }

    private void initTab() throws DataSetException {
		// TODO Auto-generated method stub
		WelcomeEoRecVolJPanel welcomeEoRecVolPanel = new WelcomeEoRecVolJPanel(this);
        SimpleEoRecVolJPanel simpleEoRecVolPanel = new SimpleEoRecVolJPanel(this);
		PerformanceJPanel performanceEoRevVolPanel = new PerformanceJPanel(this);

        mainSimpleEoRecVoljTabbedPanel.addTab("0. Welcome eo_recVol panel", welcomeEoRecVolPanel);
        mainSimpleEoRecVoljTabbedPanel.addTab("1. simple_eo_recVol panel", simpleEoRecVolPanel);
		mainSimpleEoRecVoljTabbedPanel.addTab("2. Performance panel", performanceEoRevVolPanel);
		
    }

	/** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainSimpleEoRecVoljTabbedPanel = new javax.swing.JTabbedPane();

        setLayout(new java.awt.BorderLayout());
        add(mainSimpleEoRecVoljTabbedPanel, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane mainSimpleEoRecVoljTabbedPanel;
    // End of variables declaration//GEN-END:variables

}
