/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * SimplePanel.java
 *
 * Created on 12/11/2015, 2:39:12 PM
 */

package edu.kit.gridbeans.simple.plugin;

import com.intel.gpe.clients.api.Client;
import com.intel.gpe.gridbeans.plugins.DataSetException;
import com.intel.gpe.gridbeans.plugins.swing.panels.GridBeanPanel;
import com.intel.gpe.util.defaults.preferences.INode;

/**
 *
 * @author Frederic Bonnet
 * @Date 12th of November 2015
 * 
 */
public class SimplePanel extends GridBeanPanel {

    /**
	 * Add UID
	 */
	private static final long serialVersionUID = 8475318621746055135L;

	/** Creates new form SimplePanel */
    public SimplePanel(Client client, INode node) {
    	super(client, "Simple", node);
    	initComponents();
    	try {
    		initTab();
    	} catch(DataSetException e){
    		getClient().showException("error creating Simple panel", e);
    	}
    }
    
    private void initTab() throws DataSetException  {
		// TODO Auto-generated method stub
		WelcomeJPanel welcomejpanel = new WelcomeJPanel(this);
		
		mainSimplejTabbedPanel.addTab("0. Start here, general options", welcomejpanel);
		
	}

	/** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainSimplejTabbedPanel = new javax.swing.JTabbedPane();

        setLayout(new java.awt.BorderLayout());
        add(mainSimplejTabbedPanel, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane mainSimplejTabbedPanel;
    // End of variables declaration//GEN-END:variables

}
