/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * WelcomeJPanel2.java
 *
 * Created on 12/11/2015, 6:34:55 PM
 */

package edu.kit.gridbeans.simple.plugin;

import java.awt.event.ItemEvent;

import javax.swing.JPanel;

import com.intel.gpe.gridbeans.parameters.EnvironmentVariableParameterValue;
import com.intel.gpe.gridbeans.plugins.DataSetException;
import com.intel.gpe.gridbeans.plugins.swing.panels.GridBeanPanel;

import edu.kit.gridbeans.simple.SimpleGridBean;

/**
 *
 * @author frederic
 */
public class WelcomeJPanel extends JPanel {
	private GridBeanPanel parentPanel;
    /**
	 * Add UID
	 */
	private static final long serialVersionUID = 1L;
	/** Creates new form WelcomeJPanel */

    public WelcomeJPanel(GridBeanPanel parentpanel) throws DataSetException {
    	this.parentPanel = parentpanel;
    	initComponents();
    	initCustomComponents();
    	bindComponents();
    }
    
	private void initCustomComponents() {
		// TODO Auto-generated method stub
		hotcoldbuttonGroup.add(coldStartRadioButton);
		hotcoldbuttonGroup.add(hotStartRadioButton);
		hotcoldbuttonGroup.add(randomStartRadioButton);
	}

	private void bindComponents() {
		// TODO Auto-generated method stub
		
	}

	/** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        hotcoldbuttonGroup = new javax.swing.ButtonGroup();
        mainWelcomeScrollPanel = new javax.swing.JScrollPane();
        mainWelcomePanel = new javax.swing.JPanel();
        graphicWelcomPanel = new javax.swing.JPanel();
        generalOptionsPanel = new javax.swing.JPanel();
        coldStartRadioButton = new javax.swing.JRadioButton();
        hotStartRadioButton = new javax.swing.JRadioButton();
        randomStartRadioButton = new javax.swing.JRadioButton();
        infoWelcomeScrollPanel = new javax.swing.JScrollPane();
        infoWelcomeTextArea = new javax.swing.JTextArea();
        contributorsButton = new javax.swing.JButton();
        refreshTextAreaButton = new javax.swing.JButton();
        helpWelcomeButton = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout());

        graphicWelcomPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(-16777216,true)));

        javax.swing.GroupLayout graphicWelcomPanelLayout = new javax.swing.GroupLayout(graphicWelcomPanel);
        graphicWelcomPanel.setLayout(graphicWelcomPanelLayout);
        graphicWelcomPanelLayout.setHorizontalGroup(
            graphicWelcomPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 497, Short.MAX_VALUE)
        );
        graphicWelcomPanelLayout.setVerticalGroup(
            graphicWelcomPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 47, Short.MAX_VALUE)
        );

        coldStartRadioButton.setText("Cold start");
        coldStartRadioButton.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                coldStartRadioButtonItemStateChanged(evt);
            }
        });
        coldStartRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                coldStartRadioButtonActionPerformed(evt);
            }
        });

        hotStartRadioButton.setText("Hot start (Read in)");
        hotStartRadioButton.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                hotStartRadioButtonItemStateChanged(evt);
            }
        });
        hotStartRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hotStartRadioButtonActionPerformed(evt);
            }
        });

        randomStartRadioButton.setText("Random start");
        randomStartRadioButton.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                randomStartRadioButtonItemStateChanged(evt);
            }
        });
        randomStartRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                randomStartRadioButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout generalOptionsPanelLayout = new javax.swing.GroupLayout(generalOptionsPanel);
        generalOptionsPanel.setLayout(generalOptionsPanelLayout);
        generalOptionsPanelLayout.setHorizontalGroup(
            generalOptionsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(generalOptionsPanelLayout.createSequentialGroup()
                .addComponent(coldStartRadioButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(hotStartRadioButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(randomStartRadioButton)
                .addContainerGap(196, Short.MAX_VALUE))
        );
        generalOptionsPanelLayout.setVerticalGroup(
            generalOptionsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(generalOptionsPanelLayout.createSequentialGroup()
                .addGroup(generalOptionsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(coldStartRadioButton)
                    .addComponent(hotStartRadioButton)
                    .addComponent(randomStartRadioButton))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        infoWelcomeTextArea.setColumns(20);
        infoWelcomeTextArea.setRows(5);
        infoWelcomeScrollPanel.setViewportView(infoWelcomeTextArea);

        contributorsButton.setText("Contributors");
        contributorsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contributorsButtonActionPerformed(evt);
            }
        });

        refreshTextAreaButton.setText("Refresh");
        refreshTextAreaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshTextAreaButtonActionPerformed(evt);
            }
        });

        helpWelcomeButton.setText("Help");
        helpWelcomeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                helpWelcomeButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout mainWelcomePanelLayout = new javax.swing.GroupLayout(mainWelcomePanel);
        mainWelcomePanel.setLayout(mainWelcomePanelLayout);
        mainWelcomePanelLayout.setHorizontalGroup(
            mainWelcomePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainWelcomePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(mainWelcomePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mainWelcomePanelLayout.createSequentialGroup()
                        .addComponent(contributorsButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(refreshTextAreaButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 333, Short.MAX_VALUE)
                        .addComponent(helpWelcomeButton))
                    .addComponent(generalOptionsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(infoWelcomeScrollPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 499, Short.MAX_VALUE)
                    .addComponent(graphicWelcomPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(218, 218, 218))
        );
        mainWelcomePanelLayout.setVerticalGroup(
            mainWelcomePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainWelcomePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(graphicWelcomPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(generalOptionsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(infoWelcomeScrollPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(mainWelcomePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(contributorsButton)
                    .addComponent(refreshTextAreaButton)
                    .addComponent(helpWelcomeButton))
                .addContainerGap(119, Short.MAX_VALUE))
        );

        mainWelcomeScrollPanel.setViewportView(mainWelcomePanel);

        add(mainWelcomeScrollPanel, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void coldStartRadioButtonItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_coldStartRadioButtonItemStateChanged
        if (evt.getStateChange() == ItemEvent.SELECTED) {
            infoWelcomeTextArea.append("Starting from a cold gauge field configuration i.e. U(x) = I.");
            infoWelcomeTextArea.append("\n");
        } else if (evt.getStateChange() == ItemEvent.DESELECTED ) {
            infoWelcomeTextArea.append("Will not be starting from a cold gauge field configuration i.e. U(x) = I.");
            infoWelcomeTextArea.append("\n");
        }
}//GEN-LAST:event_coldStartRadioButtonItemStateChanged

    private void coldStartRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_coldStartRadioButtonActionPerformed
        EnvironmentVariableParameterValue value = new EnvironmentVariableParameterValue("-1");
        parentPanel.getGridBeanModel().set(SimpleGridBean.ISTART, value);
}//GEN-LAST:event_coldStartRadioButtonActionPerformed

    private void hotStartRadioButtonItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_hotStartRadioButtonItemStateChanged
        if (evt.getStateChange() == ItemEvent.SELECTED) {
            infoWelcomeTextArea.append("Starting from a readin gauge field configuration i.e. U_{i}(x) = U_{i-1}(x)");
            infoWelcomeTextArea.append("\n");
        } else if (evt.getStateChange() == ItemEvent.DESELECTED ) {
            infoWelcomeTextArea.append("Will not be starting from a readin gauge field configuration i.e. U_{i}(x) = U_{i-1}(x)");
            infoWelcomeTextArea.append("\n");
        }
}//GEN-LAST:event_hotStartRadioButtonItemStateChanged

    private void hotStartRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hotStartRadioButtonActionPerformed
        EnvironmentVariableParameterValue value = new EnvironmentVariableParameterValue("1");
        parentPanel.getGridBeanModel().set(SimpleGridBean.ISTART, value);
}//GEN-LAST:event_hotStartRadioButtonActionPerformed

    private void randomStartRadioButtonItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_randomStartRadioButtonItemStateChanged
        if (evt.getStateChange() == ItemEvent.SELECTED) {
            infoWelcomeTextArea.append("Starting from a random gauge field configuration i.e. U_{i}(x) = U_{i-1}(x)");
            infoWelcomeTextArea.append("\n");
        } else if (evt.getStateChange() == ItemEvent.DESELECTED ) {
            infoWelcomeTextArea.append("Will not be starting from a random gauge field configuration i.e. U_{i}(x) = U_{i-1}(x)");
            infoWelcomeTextArea.append("\n");
        }
}//GEN-LAST:event_randomStartRadioButtonItemStateChanged

    private void randomStartRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_randomStartRadioButtonActionPerformed
        EnvironmentVariableParameterValue value = new EnvironmentVariableParameterValue("0");
        parentPanel.getGridBeanModel().set(SimpleGridBean.ISTART, value);
}//GEN-LAST:event_randomStartRadioButtonActionPerformed

    private void contributorsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contributorsButtonActionPerformed
        /**
         * Add a contributor splash screen
         */
        ContributorSplashScreen contributors = new ContributorSplashScreen();
        contributors.setVisible(true);
}//GEN-LAST:event_contributorsButtonActionPerformed

    private void refreshTextAreaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshTextAreaButtonActionPerformed
        infoWelcomeTextArea.setText("");
}//GEN-LAST:event_refreshTextAreaButtonActionPerformed

    private void helpWelcomeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_helpWelcomeButtonActionPerformed
        /**
         * add the help window in the welcome Panel
         */
        HelpWelcomeSimple helpwindowinWelcomePanel = new HelpWelcomeSimple();
        helpwindowinWelcomePanel.setVisible(true);
}//GEN-LAST:event_helpWelcomeButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton coldStartRadioButton;
    private javax.swing.JButton contributorsButton;
    private javax.swing.JPanel generalOptionsPanel;
    private javax.swing.JPanel graphicWelcomPanel;
    private javax.swing.JButton helpWelcomeButton;
    private javax.swing.JRadioButton hotStartRadioButton;
    private javax.swing.ButtonGroup hotcoldbuttonGroup;
    private javax.swing.JScrollPane infoWelcomeScrollPanel;
    private javax.swing.JTextArea infoWelcomeTextArea;
    private javax.swing.JPanel mainWelcomePanel;
    private javax.swing.JScrollPane mainWelcomeScrollPanel;
    private javax.swing.JRadioButton randomStartRadioButton;
    private javax.swing.JButton refreshTextAreaButton;
    // End of variables declaration//GEN-END:variables

}
