! View file: how the large check_*arg block would be replaced.
! The lists below are intentionally representative and keep the ordering idea:
! group by storage type, then keep a stable readable order within the group.

module simple_parameters_refactor_bindings_view
use simple_parameters_proto_registry, only: param_registry
implicit none

contains

    subroutine parse_inputs(self, cline)
        class(parameters), intent(inout) :: self
        class(cmdline),    intent(inout) :: cline
        type(param_registry) :: reg

        call self%bind_input_char3(reg)
        call reg%apply_cmdline(cline)

        call self%bind_input_character(reg)
        call reg%apply_cmdline(cline)

        call self%bind_input_string(reg)
        call reg%apply_cmdline(cline)

        call self%bind_input_integer(reg)
        call reg%apply_cmdline(cline)

        call self%bind_input_real(reg)
        call reg%apply_cmdline(cline)
    end subroutine parse_inputs

    subroutine bind_input_char3(self, reg)
        class(parameters),   target, intent(inout) :: self
        class(param_registry),       intent(inout) :: reg

        call reg%init('char3')
        call reg%add_char('acf',            self%acf)
        call reg%add_char('append',         self%append)
        call reg%add_char('async',          self%async)
        call reg%add_char('atom_thres',     self%atom_thres)
        call reg%add_char('autoscale',      self%autoscale)
        call reg%add_char('avg',            self%avg)
        call reg%add_char('backgr_subtr',   self%backgr_subtr)
        call reg%add_char('balance',        self%balance)
        call reg%add_char('beamtilt',       self%beamtilt)
        call reg%add_char('bin',            self%bin)
        call reg%add_char('boxes',          self%boxes)
        call reg%add_char('cavg_ini',       self%cavg_ini)
        call reg%add_char('cavg_ini_ext',   self%cavg_ini_ext)
        call reg%add_char('cavgw',          self%cavgw)
        call reg%add_char('center',         self%center)
        call reg%add_char('center_pdb',     self%center_pdb)
        call reg%add_char('chunk',          self%chunk)
        call reg%add_char('classtats',      self%classtats)
        call reg%add_char('clear',          self%clear)
        call reg%add_char('combine_eo',     self%combine_eo)
        call reg%add_char('continue',       self%continue)
        call reg%add_char('ctfstats',       self%ctfstats)
        call reg%add_char('ctfpatch',       self%ctfpatch)
        call reg%add_char('doprint',        self%doprint)
        call reg%add_char('downscale',      self%downscale)
        call reg%add_char('dynreslim',      self%dynreslim)
        call reg%add_char('empty3Dcavgs',   self%empty3Dcavgs)
        call reg%add_char('envfsc',         self%envfsc)
        call reg%add_char('eo_stage',       self%eo_stage)
        call reg%add_char('even',           self%even)
        call reg%add_char('extract',        self%extract)
        call reg%add_char('extractfrommov', self%extractfrommov)
        call reg%add_char('fill_holes',     self%fill_holes)
        call reg%add_char('fillin',         self%fillin)
        call reg%add_char('force_lp_range', self%force_lp_range)
        call reg%add_char('gauref',         self%gauref)
        call reg%add_char('guinier',        self%guinier)
        call reg%add_char('graphene_filt',  self%graphene_filt)
        call reg%add_char('greedy_sampling',self%greedy_sampling)
        call reg%add_char('hist',           self%hist)
        call reg%add_char('icm',            self%icm)
        call reg%add_char('incrreslim',     self%incrreslim)
        call reg%add_char('interactive',    self%interactive)
        call reg%add_char('iterstats',      self%iterstats)
        call reg%add_char('json',           self%json)
        call reg%add_char('keepvol',        self%keepvol)
        call reg%add_char('lam_anneal',     self%lam_anneal)
        call reg%add_char('linethres',      self%linethres)
        call reg%add_char('loc_sdev',       self%loc_sdev)
        call reg%add_char('makemovie',      self%makemovie)
        call reg%add_char('mcpatch',        self%mcpatch)
        call reg%add_char('mcpatch_thres',  self%mcpatch_thres)
        call reg%add_char('mirr',           self%mirr)
        call reg%add_char('mirr_proj',      self%mirr_proj)
        call reg%add_char('mkdir',          self%mkdir)
        call reg%add_char('ml_reg',         self%ml_reg)
        call reg%add_char('ml_reg_chunk',   self%ml_reg_chunk)
        call reg%add_char('ml_reg_pool',    self%ml_reg_pool)
        call reg%add_char('neg',            self%neg)
        call reg%add_char('neigs_per',      self%neigs_per)
        call reg%add_char('noise_norm',     self%noise_norm)
        call reg%add_char('norm',           self%norm)
        call reg%add_char('omit_neg',       self%omit_neg)
        call reg%add_char('outside',        self%outside)
        call reg%add_char('pad',            self%pad)
        call reg%add_char('partition',      self%partition)
        call reg%add_char('pca_img_ori',    self%pca_img_ori)
        call reg%add_char('pca_ori_stk',    self%pca_ori_stk)
        call reg%add_char('phaseplate',     self%phaseplate)
        call reg%add_char('phrand',         self%phrand)
        call reg%add_char('pick_roi',       self%pick_roi)
        call reg%add_char('platonic',       self%platonic)
        call reg%add_char('potts_prior',    self%potts_prior)
        call reg%add_char('postprocess',    self%postprocess)
        call reg%add_char('pre_norm',       self%pre_norm)
        call reg%add_char('print_corrs',    self%print_corrs)
        call reg%add_char('proj_is_class',  self%proj_is_class)
        call reg%add_char('projstats',      self%projstats)
        call reg%add_char('prune',          self%prune)
        call reg%add_char('prob_inpl',      self%prob_inpl)
        call reg%add_char('randomise',      self%randomise)
        call reg%add_char('rank_cavgs',     self%rank_cavgs)
        call reg%add_char('ranked_parts',   self%ranked_parts)
        call reg%add_char('recthres',       self%recthres)
        call reg%add_char('reject_mics',    self%reject_mics)
        call reg%add_char('remap_cls',      self%remap_cls)
        call reg%add_char('remove_chunks',  self%remove_chunks)
        call reg%add_char('reset_boxfiles', self%reset_boxfiles)
        call reg%add_char('restore_cavgs',  self%restore_cavgs)
        call reg%add_char('ring',           self%ring)
        call reg%add_char('roavg',          self%roavg)
        call reg%add_char('script',         self%script)
        call reg%add_char('shbarrier',      self%shbarrier)
        call reg%add_char('sort_asc',       self%sort_asc)
        call reg%add_char('srch_oris',      self%srch_oris)
        call reg%add_char('stream',         self%stream)
        call reg%add_char('stream2d',       self%stream2d)
        call reg%add_char('symrnd',         self%symrnd)
        call reg%add_char('taper_edges',    self%taper_edges)
        call reg%add_char('tester',         self%tester)
        call reg%add_char('tophat',         self%tophat)
        call reg%add_char('trail_rec',      self%trail_rec)
        call reg%add_char('transp_pca',     self%transp_pca)
        call reg%add_char('trsstats',       self%trsstats)
        call reg%add_char('tseries',        self%tseries)
        call reg%add_char('updated',        self%updated)
        call reg%add_char('use_thres',      self%use_thres)
        call reg%add_char('vis',            self%vis)
        call reg%add_char('verbose_exit',   self%verbose_exit)
        call reg%add_char('volrec',         self%volrec)
        call reg%add_char('write_imgarr',   self%write_imgarr)
        call reg%add_char('zero',           self%zero)
    end subroutine bind_input_char3

    subroutine bind_input_character(self, reg)
        class(parameters),   target, intent(inout) :: self
        class(param_registry),       intent(inout) :: reg

        call reg%init('character')
        call reg%add_char('algorithm',      self%algorithm)
        call reg%add_char('angastunit',     self%angastunit)
        call reg%add_char('automatic',      self%automatic)
        call reg%add_char('automsk',        self%automsk)
        call reg%add_char('center_type',    self%center_type)
        call reg%add_char('cls_init',       self%cls_init)
        call reg%add_char('clustinds',      self%clustinds)
        call reg%add_char('clust_crit',     self%clust_crit)
        call reg%add_char('cn_type',        self%cn_type)
        call reg%add_char('ctf',            self%ctf)
        call reg%add_char('detector',       self%detector)
        call reg%add_char('dfunit',         self%dfunit)
        call reg%add_char('element',        self%element)
        call reg%add_char('filter',         self%filter)
        call reg%add_char('filt_mode',      self%filt_mode)
        call reg%add_char('flag',           self%flag)
        call reg%add_char('flipgain',       self%flipgain)
        call reg%add_char('imgkind',        self%imgkind)
        call reg%add_char('inivol',         self%inivol)
        call reg%add_char('import_type',    self%import_type)
        call reg%add_char('kpca_backend',   self%kpca_backend)
        call reg%add_char('kpca_ker',       self%kpca_ker)
        call reg%add_char('mcconvention',   self%mcconvention)
        call reg%add_char('multi_moldiams', self%multi_moldiams)
        call reg%add_char('multivol_mode',  self%multivol_mode)
        call reg%add_char('objfun',         self%objfun)
        call reg%add_char('opt',            self%opt)
        call reg%add_char('oritype',        self%oritype)
        call reg%add_char('pca_mode',       self%pca_mode)
        call reg%add_char('steerable_denoise_mode', self%steerable_denoise_mode)
        call reg%add_char('pcontrast',      self%pcontrast)
        call reg%add_char('pickkind',       self%pickkind)
        call reg%add_char('pgrp',           self%pgrp)
        call reg%add_char('pgrp_start',     self%pgrp_start)
        call reg%add_char('phshiftunit',    self%phshiftunit)
        call reg%add_char('particle_density', self%particle_density)
        call reg%add_char('picker',         self%picker)
        call reg%add_char('plot_key',       self%plot_key)
        call reg%add_char('protocol',       self%protocol)
        call reg%add_char('ptclw',          self%ptclw)
        call reg%add_char('qsys_name',      self%qsys_name)
        call reg%add_char('qsys_partition2D', self%qsys_partition2D)
        call reg%add_char('real_filter',    self%real_filter)
        call reg%add_char('refine',         self%refine)
        call reg%add_char('refine_type',    self%refine_type)
        call reg%add_char('select_flag',    self%select_flag)
        call reg%add_char('sigma_est',      self%sigma_est)
        call reg%add_char('sort',           self%sort)
        call reg%add_char('speckind',       self%speckind)
        call reg%add_char('split_mode',     self%split_mode)
        call reg%add_char('startype',       self%startype)
        call reg%add_char('stats',          self%stats)
        call reg%add_char('tag',            self%tag)
        call reg%add_char('wcrit',          self%wcrit)
    end subroutine bind_input_character

    subroutine bind_input_string(self, reg)
        class(parameters),   target, intent(inout) :: self
        class(param_registry),       intent(inout) :: reg

        call reg%init('string')
        call reg%add_string('boxfile',      self%boxfile, role='file')
        call reg%add_string('boxtab',       self%boxtab, role='file')
        call reg%add_string('ciffile',      self%ciffile, role='file')
        call reg%add_string('class_assignment', self%class_assignment)
        call reg%add_string('classdoc',     self%classdoc, role='file')
        call reg%add_string('deftab',       self%deftab, role='file')
        call reg%add_string('deselfile',    self%deselfile, role='file')
        call reg%add_string('dir',          self%dir, role='dir')
        call reg%add_string('dir_box',      self%dir_box, role='dir')
        call reg%add_string('dir_exec',     self%dir_exec, role='dir')
        call reg%add_string('dir_meta',     self%dir_meta, role='dir')
        call reg%add_string('dir_movies',   self%dir_movies, role='dir')
        call reg%add_string('dir_prev',     self%dir_prev, role='dir')
        call reg%add_string('dir_refine',   self%dir_refine, role='dir')
        call reg%add_string('dir_reject',   self%dir_reject, role='dir')
        call reg%add_string('dir_select',   self%dir_select, role='dir')
        call reg%add_string('dir_target',   self%dir_target, role='dir')
        call reg%add_string('ext',          self%ext, role='format')
        call reg%add_string('fbody',        self%fbody)
        call reg%add_string('filetab',      self%filetab, role='file')
        call reg%add_string('fname',        self%fname, role='file')
        call reg%add_string('frcs',         self%frcs, role='file')
        call reg%add_string('fsc',          self%fsc, role='file')
        call reg%add_string('gainref',      self%gainref, role='file')
        call reg%add_string('import_dir',   self%import_dir, role='dir')
        call reg%add_string('infile',       self%infile, role='file')
        call reg%add_string('infile2',      self%infile2, role='file')
        call reg%add_string('msklist',      self%msklist, role='file')
        call reg%add_string('niceserver',   self%niceserver)
        call reg%add_string('optics_dir',   self%optics_dir, role='dir')
        call reg%add_string('oritab',       self%oritab, role='file')
        call reg%add_string('oritab2',      self%oritab2, role='file')
        call reg%add_string('outdir',       self%outdir)
        call reg%add_string('outfile',      self%outfile, role='file')
        call reg%add_string('outstk',       self%outstk, role='file')
        call reg%add_string('outvol',       self%outvol, role='file')
        call reg%add_string('pdbfile',      self%pdbfile, role='file')
        call reg%add_string('pdbfile2',     self%pdbfile2, role='file')
        call reg%add_string('pdbfiles',     self%pdbfiles, role='file')
        call reg%add_string('pdbout',       self%pdbout, role='file')
        call reg%add_string('pickrefs',     self%pickrefs, role='file')
        call reg%add_string('plaintexttab', self%plaintexttab, role='file')
        call reg%add_string('prg',          self%prg)
        call reg%add_string('projfile',     self%projfile, role='file')
        call reg%add_string('projfile_merged', self%projfile_merged, role='file')
        call reg%add_string('projfile_optics', self%projfile_optics, role='file')
        call reg%add_string('projfile_ref', self%projfile_ref, role='file')
        call reg%add_string('projfile_target', self%projfile_target, role='file')
        call reg%add_string('projname',     self%projname)
        call reg%add_string('refs',         self%refs, role='file')
        call reg%add_string('snapshot',     self%snapshot, role='file')
        call reg%add_string('star_datadir', self%star_datadir, role='dir')
        call reg%add_string('star_mic',     self%star_mic, role='file')
        call reg%add_string('star_model',   self%star_model, role='file')
        call reg%add_string('star_ptcl',    self%star_ptcl, role='file')
        call reg%add_string('starfile',     self%starfile, role='file')
        call reg%add_string('stk',          self%stk, role='file')
        call reg%add_string('stk2',         self%stk2, role='file')
        call reg%add_string('stk3',         self%stk3, role='file')
        call reg%add_string('stk_backgr',   self%stk_backgr, role='file')
        call reg%add_string('stktab',       self%stktab, role='file')
        call reg%add_string('subprojname',  self%subprojname)
        call reg%add_string('verbose_exit_fname', self%verbose_exit_fname)
        call reg%add_string('vol_even',     self%vol_even, role='file')
        call reg%add_string('vol_odd',      self%vol_odd, role='file')
    end subroutine bind_input_string

    subroutine bind_input_integer(self, reg)
        class(parameters),   target, intent(inout) :: self
        class(param_registry),       intent(inout) :: reg

        call reg%init('integer')
        ! Full integer list follows the current flat type and replaces the current
        ! check_iarg wall one-to-one.
        call reg%add_int('angstep',        self%angstep)
        call reg%add_int('binwidth',       self%binwidth)
        call reg%add_int('box',            self%box)
        call reg%add_int('box_crop',       self%box_crop)
        call reg%add_int('box_extract',    self%box_extract)
        call reg%add_int('clip',           self%clip)
        call reg%add_int('clustind',       self%clustind)
        call reg%add_int('cn',             self%cn)
        call reg%add_int('cn_max',         self%cn_max)
        call reg%add_int('cn_min',         self%cn_min)
        call reg%add_int('cn_stop',        self%cn_stop)
        call reg%add_int('cs_thres',       self%cs_thres)
        call reg%add_int('device',         self%device)
        call reg%add_int('edge',           self%edge)
        call reg%add_int('eer_fraction',   self%eer_fraction)
        call reg%add_int('eer_upsampling', self%eer_upsampling)
        call reg%add_int('extr_iter',      self%extr_iter)
        call reg%add_int('extr_lim',       self%extr_lim)
        call reg%add_int('find',           self%find)
        call reg%add_int('gauref_last_stage', self%gauref_last_stage)
        call reg%add_int('nframesgrp',     self%nframesgrp)
        call reg%add_int('fromp',          self%fromp)
        call reg%add_int('fromf',          self%fromf)
        call reg%add_int('grow',           self%grow)
        call reg%add_int('icm_stage',      self%icm_stage)
        call reg%add_int('iptcl',          self%iptcl)
        call reg%add_int('job_memory_per_task2D', self%job_memory_per_task2D)
        call reg%add_int('maxits',         self%maxits)
        call reg%add_int('maxits_glob',    self%maxits_glob)
        call reg%add_int('maxits_between', self%maxits_between)
        call reg%add_int('maxits_sh',      self%maxits_sh)
        call reg%add_int('maxnchunks',     self%maxnchunks)
        call reg%add_int('maxnptcls',      self%maxnptcls)
        call reg%add_int('maxpop',         self%maxpop)
        call reg%add_int('minits',         self%minits)
        call reg%add_int('nboxes_max',     self%nboxes_max)
        call reg%add_int('nchunks',        self%nchunks)
        call reg%add_int('nchunksperset',  self%nchunksperset)
        call reg%add_int('ncls',           self%ncls)
        call reg%add_int('ncls_sub',       self%ncls_sub)
        call reg%add_int('nsubcls_min',    self%nsubcls_min)
        call reg%add_int('nsubcls_max',    self%nsubcls_max)
        call reg%add_int('ncls_start',     self%ncls_start)
        call reg%add_int('ncunits',        self%ncunits)
        call reg%add_int('ndiscrete',      self%ndiscrete)
        call reg%add_int('neigs',          self%neigs)
        call reg%add_int('kpca_nystrom_npts', self%kpca_nystrom_npts)
        call reg%add_int('kpca_nystrom_local_nbrs', self%kpca_nystrom_local_nbrs)
        call reg%add_int('k_nn',           self%k_nn)
        call reg%add_int('steerable_nmodes', self%steerable_nmodes)
        call reg%add_int('newbox',         self%newbox)
        call reg%add_int('nframes',        self%nframes)
        call reg%add_int('ngrow',          self%ngrow)
        call reg%add_int('niceprocid',     self%niceprocid)
        call reg%add_int('ninipick',       self%ninipick)
        call reg%add_int('ninit',          self%ninit)
        call reg%add_int('nits_per_stage', self%nits_per_stage)
        call reg%add_int('nmics',          self%nmics)
        call reg%add_int('nmoldiams',      self%nmoldiams)
        call reg%add_int('nsearch',        self%nsearch)
        call reg%add_int('noris',          self%noris)
        call reg%add_int('nran',           self%nran)
        call reg%add_int('nrefs',          self%nrefs)
        call reg%add_int('nrestarts',      self%nrestarts)
        call reg%add_int('nsample',        self%nsample)
        call reg%add_int('nsample_max',    self%nsample_max)
        call reg%add_int('nsample_start',  self%nsample_start)
        call reg%add_int('nsample_stop',   self%nsample_stop)
        call reg%add_int('nspace',         self%nspace)
        call reg%add_int('nspace_sub',     self%nspace_sub)
        call reg%add_int('nspace_max',     self%nspace_max)
        call reg%add_int('nstages',        self%nstages)
        call reg%add_int('nstates',        self%nstates)
        call reg%add_int('class',          self%class)
        call reg%add_int('nparts',         self%nparts)
        call reg%add_int('nparts_per_part', self%nparts_per_part)
        call reg%add_int('nparts_chunk',   self%nparts_chunk)
        call reg%add_int('nparts_pool',    self%nparts_pool)
        call reg%add_int('npeaks',         self%npeaks)
        call reg%add_int('npeaks_inpl',    self%npeaks_inpl)
        call reg%add_int('npix',           self%npix)
        call reg%add_int('nptcls',         self%nptcls)
        call reg%add_int('nptcls_per_cls', self%nptcls_per_cls)
        call reg%add_int('nptcls_per_subcls', self%nptcls_per_subcls)
        call reg%add_int('nptcls_per_part', self%nptcls_per_part)
        call reg%add_int('nquanta',        self%nquanta)
        call reg%add_int('nthr',           self%nthr)
        call reg%add_int('nthr2D',         self%nthr2D)
        call reg%add_int('nthr_ini3D',     self%nthr_ini3D)
        call reg%add_int('numlen',         self%numlen)
        call reg%add_int('nxpatch',        self%nxpatch)
        call reg%add_int('nypatch',        self%nypatch)
        call reg%add_int('offset',         self%offset)
        call reg%add_int('optics_offset',  self%optics_offset)
        call reg%add_int('part',           self%part)
        call reg%add_int('period',         self%period)
        call reg%add_int('pftsz',          self%pftsz)
        call reg%add_int('pspecsz',        self%pspecsz)
        call reg%add_int('ref_ind',        self%ref_ind)
        call reg%add_int('shift_stage',    self%shift_stage)
        call reg%add_int('split_stage',    self%split_stage)
        call reg%add_int('startit',        self%startit)
        call reg%add_int('stage',          self%stage)
        call reg%add_int('state',          self%state)
        call reg%add_int('stepsz',         self%stepsz)
        call reg%add_int('top',            self%top)
        call reg%add_int('tof',            self%tof)
        call reg%add_int('vol_dim',        self%vol_dim)
        call reg%add_int('which_iter',     self%which_iter)
        call reg%add_int('walltime',       self%walltime)
        call reg%add_int('workers',        self%workers)
        call reg%add_int('worker_nthr',    self%worker_nthr)
        call reg%add_int('xdim',           self%xdim)
        call reg%add_int('xcoord',         self%xcoord)
        call reg%add_int('ycoord',         self%ycoord)
        call reg%add_int('ydim',           self%ydim)
    end subroutine bind_input_integer

    subroutine bind_input_real(self, reg)
        class(parameters),   target, intent(inout) :: self
        class(param_registry),       intent(inout) :: reg

        call reg%init('real')
        ! Same idea as integers: this replaces the full check_rarg block.
        call reg%add_real('amsklp',         self%amsklp)
        call reg%add_real('angerr',         self%angerr)
        call reg%add_real('angthres_mi_proj', self%angthres_mi_proj)
        call reg%add_real('ares',           self%ares)
        call reg%add_real('astigerr',       self%astigerr)
        call reg%add_real('astigthreshold', self%astigthreshold)
        call reg%add_real('astigtol',       self%astigtol)
        call reg%add_real('athres',         self%athres)
        call reg%add_real('beta',           self%beta)
        call reg%add_real('bfac',           self%bfac)
        call reg%add_real('bfacerr',        self%bfacerr)
        call reg%add_real('bw_ratio',       self%bw_ratio)
        call reg%add_real('cenlp',          self%cenlp)
        call reg%add_real('cs',             self%cs)
        call reg%add_real('corr_thres',     self%corr_thres)
        call reg%add_real('ctfresthreshold', self%ctfresthreshold)
        call reg%add_real('defocus',        self%defocus)
        call reg%add_real('dferr',          self%dferr)
        call reg%add_real('dfmax',          self%dfmax)
        call reg%add_real('dfmin',          self%dfmin)
        call reg%add_real('dfsdev',         self%dfsdev)
        call reg%add_real('e1',             self%e1)
        call reg%add_real('e2',             self%e2)
        call reg%add_real('e3',             self%e3)
        call reg%add_real('eps',            self%eps)
        call reg%add_real('extr_init',      self%extr_init)
        call reg%add_real('frac',           self%frac)
        call reg%add_real('fraca',          self%fraca)
        call reg%add_real('fracdeadhot',    self%fracdeadhot)
        call reg%add_real('frac_best',      self%frac_best)
        call reg%add_real('frac_worst',     self%frac_worst)
        call reg%add_real('frac_diam',      self%frac_diam)
        call reg%add_real('fracsrch',       self%fracsrch)
        call reg%add_real('fraction_dose_target', self%fraction_dose_target)
        call reg%add_real('frac_outliers',  self%frac_outliers)
        call reg%add_real('fraczero',       self%fraczero)
        call reg%add_real('ftol',           self%ftol)
        call reg%add_real('gaufreq',        self%gaufreq)
        call reg%add_real('hp',             self%hp)
        call reg%add_real('hp_ctf_estimate', self%hp_ctf_estimate)
        call reg%add_real('kpca_cosine_weight_power', self%kpca_cosine_weight_power)
        call reg%add_real('ppca_kpca_resid_alpha', self%ppca_kpca_resid_alpha)
        call reg%add_real('icefracthreshold', self%icefracthreshold)
        call reg%add_real('kv',             self%kv)
        call reg%add_real('lambda',         self%lambda)
        call reg%add_real('lp',             self%lp)
        call reg%add_real('lp2D',           self%lp2D)
        call reg%add_real('lp_backgr',      self%lp_backgr)
        call reg%add_real('lp_ctf_estimate', self%lp_ctf_estimate)
        call reg%add_real('lp_discrete',    self%lp_discrete)
        call reg%add_real('lpstart_nonuni', self%lpstart_nonuni)
        call reg%add_real('lp_pick',        self%lp_pick)
        call reg%add_real('lplim_crit',     self%lplim_crit)
        call reg%add_real('lpstart',        self%lpstart)
        call reg%add_real('lpstop',         self%lpstop)
        call reg%add_real('lpstart_ini3D',  self%lpstart_ini3D)
        call reg%add_real('lpstop_ini3D',   self%lpstop_ini3D)
        call reg%add_real('lpstop2D',       self%lpstop2D)
        call reg%add_real('lpthres',        self%lpthres)
        call reg%add_real('max_dose',       self%max_dose)
        call reg%add_real('moldiam',        self%moldiam)
        call reg%add_real('moldiam_max',    self%moldiam_max)
        call reg%add_real('moldiam_refine', self%moldiam_refine)
        call reg%add_real('moldiam_ring',   self%moldiam_ring)
        call reg%add_real('msk',            self%msk)
        call reg%add_real('msk_crop',       self%msk_crop)
        call reg%add_real('mskdiam',        self%mskdiam)
        call reg%add_real('mskdiam_detect', self%mskdiam_detect)
        call reg%add_real('ndev',           self%ndev)
        call reg%add_real('ndev2D',         self%ndev2D)
        call reg%add_real('nsig',           self%nsig)
        call reg%add_real('osmpd',          self%osmpd)
        call reg%add_real('overlap',        self%overlap)
        call reg%add_real('phranlp',        self%phranlp)
        call reg%add_real('prob_athres',    self%prob_athres)
        call reg%add_real('rec_athres',     self%rec_athres)
        call reg%add_real('res_target',     self%res_target)
        call reg%add_real('scale',          self%scale)
        call reg%add_real('sherr',          self%sherr)
        call reg%add_real('smpd',           self%smpd)
        call reg%add_real('smpd_crop',      self%smpd_crop)
        call reg%add_real('smpd_downscale', self%smpd_downscale)
        call reg%add_real('smpd_pickrefs',  self%smpd_pickrefs)
        call reg%add_real('smpd_target',    self%smpd_target)
        call reg%add_real('sigma',          self%sigma)
        call reg%add_real('snr',            self%snr)
        call reg%add_real('snr_noise_reg',  self%snr_noise_reg)
        call reg%add_real('tau',            self%tau)
        call reg%add_real('tilt_thres',     self%tilt_thres)
        call reg%add_real('thres',          self%thres)
        call reg%add_real('total_dose',     self%total_dose)
        call reg%add_real('trs',            self%trs)
        call reg%add_real('update_frac',    self%update_frac)
        call reg%add_real('ufrac_trec',     self%ufrac_trec)
        call reg%add_real('width',          self%width)
        call reg%add_real('winsz',          self%winsz)
        call reg%add_real('xsh',            self%xsh)
        call reg%add_real('ysh',            self%ysh)
        call reg%add_real('zsh',            self%zsh)
    end subroutine bind_input_real

end module simple_parameters_refactor_bindings_view
