# Generated by Django 5.2.5 on 2026-02-26 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nice_lite', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobmodel',
            name='preprocessing_heartbeat',
            field=models.IntegerField(default=0),
        ),
    ]
