# Generated by Django 5.2.5 on 2026-03-04 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nice_lite', '0002_alter_jobmodel_preprocessing_heartbeat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobmodel',
            name='master_heartbeat',
            field=models.IntegerField(default=0),
        ),
    ]
