# Generated by Django 5.2.5 on 2025-08-21 08:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DatasetModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=200)),
                ('desc', models.CharField(max_length=200)),
                ('date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='ProjectModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='JobModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=200)),
                ('desc', models.CharField(max_length=200)),
                ('date', models.DateTimeField()),
                ('dset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nice_lite.datasetmodel')),
            ],
        ),
        migrations.AddField(
            model_name='datasetmodel',
            name='proj',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nice_lite.projectmodel'),
        ),
    ]
