# Generated by Django 5.2.5 on 2026-02-26 15:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DatasetModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disp', models.IntegerField(default=0)),
                ('jcnt', models.IntegerField(default=0)),
                ('name', models.CharField(default='', max_length=200)),
                ('desc', models.CharField(default='', max_length=200)),
                ('dirc', models.CharField(default='', max_length=200)),
                ('link', models.CharField(default='', max_length=200)),
                ('user', models.CharField(default='', max_length=50)),
                ('cdat', models.DateTimeField(auto_now_add=True)),
                ('mdat', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='DispatchModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scmd', models.CharField(default='', max_length=200)),
                ('url', models.CharField(default='', max_length=200)),
                ('tplt', models.TextField(default='')),
                ('active', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('date', models.DateTimeField()),
                ('desc', models.CharField(default='', max_length=1024)),
                ('dirc', models.CharField(default='', max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name='JobModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disp', models.IntegerField(default=0)),
                ('name', models.CharField(default='', max_length=200)),
                ('desc', models.CharField(default='', max_length=200)),
                ('dirc', models.CharField(default='', max_length=200)),
                ('cdat', models.DateTimeField()),
                ('args', models.JSONField(default=dict)),
                ('status', models.CharField(default='unknown', max_length=20)),
                ('master_stats', models.JSONField(blank=True, default=dict, null=True)),
                ('master_status', models.CharField(default='unknown', max_length=20)),
                ('master_update', models.JSONField(blank=True, default=dict, null=True)),
                ('master_heartbeat', models.DateTimeField(auto_now_add=True)),
                ('preprocessing_stats', models.JSONField(default=dict)),
                ('preprocessing_status', models.CharField(default='unknown', max_length=20)),
                ('preprocessing_update', models.JSONField(default=dict)),
                ('preprocessing_heartbeat', models.DateTimeField(auto_now_add=True)),
                ('optics_assignment_stats', models.JSONField(default=dict)),
                ('optics_assignment_status', models.CharField(default='unknown', max_length=20)),
                ('optics_assignment_update', models.JSONField(default=dict)),
                ('optics_assignment_heartbeat', models.DateTimeField(auto_now_add=True)),
                ('initial_picking_stats', models.JSONField(default=dict)),
                ('initial_picking_status', models.CharField(default='unknown', max_length=20)),
                ('initial_picking_update', models.JSONField(default=dict)),
                ('initial_picking_heartbeat', models.DateTimeField(auto_now_add=True)),
                ('generate_pickrefs_stats', models.JSONField(default=dict)),
                ('generate_pickrefs_status', models.CharField(default='unknown', max_length=20)),
                ('generate_pickrefs_update', models.JSONField(default=dict)),
                ('generate_pickrefs_heartbeat', models.DateTimeField(auto_now_add=True)),
                ('reference_picking_stats', models.JSONField(default=dict)),
                ('reference_picking_status', models.CharField(default='unknown', max_length=20)),
                ('reference_picking_update', models.JSONField(default=dict)),
                ('reference_picking_heartbeat', models.DateTimeField(auto_now_add=True)),
                ('particle_sieving_stats', models.JSONField(default=dict)),
                ('particle_sieving_status', models.CharField(default='unknown', max_length=20)),
                ('particle_sieving_update', models.JSONField(default=dict)),
                ('particle_sieving_heartbeat', models.DateTimeField(auto_now_add=True)),
                ('classification_2D_stats', models.JSONField(default=dict)),
                ('classification_2D_status', models.CharField(default='unknown', max_length=20)),
                ('classification_2D_update', models.JSONField(default=dict)),
                ('classification_2D_heartbeat', models.DateTimeField(auto_now_add=True)),
                ('particle_sets_stats', models.JSONField(default=dict)),
                ('dset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nice_lite.datasetmodel')),
            ],
        ),
        migrations.AddField(
            model_name='datasetmodel',
            name='proj',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nice_lite.projectmodel'),
        ),
        migrations.CreateModel(
            name='WorkspaceModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disp', models.IntegerField(default=0)),
                ('jcnt', models.IntegerField(default=0)),
                ('name', models.CharField(default='', max_length=200)),
                ('desc', models.CharField(default='', max_length=200)),
                ('dirc', models.CharField(default='', max_length=200)),
                ('link', models.CharField(default='', max_length=200)),
                ('user', models.CharField(default='', max_length=50)),
                ('cdat', models.DateTimeField(auto_now_add=True)),
                ('mdat', models.DateTimeField(auto_now_add=True)),
                ('nstr', models.JSONField(default=dict)),
                ('proj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nice_lite.projectmodel')),
            ],
        ),
        migrations.CreateModel(
            name='JobClassicModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disp', models.IntegerField(default=0)),
                ('prnt', models.IntegerField(default=0)),
                ('name', models.CharField(default='', max_length=200)),
                ('prog', models.CharField(default='', max_length=200)),
                ('desc', models.CharField(default='', max_length=200)),
                ('dirc', models.CharField(default='', max_length=200)),
                ('pckg', models.CharField(default='', max_length=20)),
                ('cdat', models.DateTimeField()),
                ('status', models.CharField(default='unknown', max_length=20)),
                ('heartbeat', models.DateTimeField(auto_now_add=True)),
                ('args', models.JSONField(default=dict)),
                ('update', models.JSONField(default=dict)),
                ('wspc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nice_lite.workspacemodel')),
            ],
        ),
    ]
