# Generated by Django 5.2.5 on 2025-08-21 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nice_lite', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasetmodel',
            name='dirc',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='jobmodel',
            name='dirc',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='datasetmodel',
            name='desc',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='jobmodel',
            name='desc',
            field=models.CharField(default='', max_length=200),
        ),
    ]
