# Generated by Django 5.2.5 on 2026-09-07 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nice_lite', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispatchmodel',
            name='simple_path',
            field=models.CharField(default='', max_length=2048),
        ),
    ]
