# Generated by Django 5.2.5 on 2026-09-11 00:00

from django.db import migrations, models


def backfill_pckg_prog(apps, schema_editor):
    """Copy package/program out of master_stats for already-persisted jobs."""
    JobModel = apps.get_model('nice_lite', 'JobModel')
    for job in JobModel.objects.exclude(master_stats={}):
        metadata = job.master_stats
        if not isinstance(metadata, dict):
            continue
        pckg = metadata.get('package', '')
        prog = metadata.get('program', '')
        if pckg or prog:
            job.pckg = pckg if isinstance(pckg, str) else ''
            job.prog = prog if isinstance(prog, str) else ''
            job.save(update_fields=('pckg', 'prog'))


class Migration(migrations.Migration):

    dependencies = [
        ('nice_lite', '0002_dispatchmodel_simple_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobmodel',
            name='pckg',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='jobmodel',
            name='prog',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.RunPython(backfill_pckg_prog, migrations.RunPython.noop),
    ]
