# Generated by Django 5.2.5 on 2026-09-11 00:00

from django.db import migrations, models


def backfill_parent(apps, schema_editor):
    """Copy parent out of master_stats for already-persisted jobs."""
    JobModel = apps.get_model('nice_lite', 'JobModel')
    for job in JobModel.objects.exclude(master_stats={}):
        metadata = job.master_stats
        if not isinstance(metadata, dict):
            continue
        parent = metadata.get('parent')
        if isinstance(parent, int) and not isinstance(parent, bool) and parent > 0:
            job.parent = parent
            job.save(update_fields=('parent',))


class Migration(migrations.Migration):

    dependencies = [
        ('nice_lite', '0003_jobmodel_pckg_prog'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobmodel',
            name='parent',
            field=models.IntegerField(default=0),
        ),
        migrations.RunPython(backfill_parent, migrations.RunPython.noop),
    ]
