# Generated by Django 5.2.5 on 2025-08-21 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nice_lite', '0003_projectmodel_desc_projectmodel_dirc'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasetmodel',
            name='link',
            field=models.CharField(default='', max_length=200),
        ),
    ]
