# Generated by Django 5.2.5 on 2025-08-21 12:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nice_lite', '0005_remove_datasetmodel_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasetmodel',
            name='cdat',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='datasetmodel',
            name='mdat',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
