# Generated by Django 5.2.5 on 2025-08-21 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nice_lite', '0006_datasetmodel_cdat_datasetmodel_mdat'),
    ]

    operations = [
        migrations.CreateModel(
            name='DispatchModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.TextField(default='')),
            ],
        ),
    ]
