# Generated by Django 5.2.5 on 2025-08-22 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nice_lite', '0010_alter_jobmodel_args'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dispatchmodel',
            old_name='desc',
            new_name='tplt',
        ),
        migrations.AddField(
            model_name='dispatchmodel',
            name='scmd',
            field=models.CharField(default='', max_length=200),
        ),
    ]
