# Generated by Django 5.2.5 on 2025-08-22 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nice_lite', '0012_dispatchmodel_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispatchmodel',
            name='envs',
            field=models.JSONField(default=dict),
        ),
    ]
