# Generated by Django 5.2.5 on 2025-08-22 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nice_lite', '0013_dispatchmodel_envs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dispatchmodel',
            name='envs',
        ),
    ]
