# Generated by Django 5.2.5 on 2025-08-26 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nice_lite', '0014_remove_dispatchmodel_envs'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobmodel',
            name='preprocessing',
            field=models.JSONField(default=dict),
        ),
    ]
