# Generated by Django 5.2.5 on 2025-08-26 15:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nice_lite', '0015_jobmodel_preprocessing'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobmodel',
            old_name='preprocessing',
            new_name='preprocessing_stats',
        ),
        migrations.AddField(
            model_name='jobmodel',
            name='preprocessing_heartbeat',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jobmodel',
            name='preprocessing_status',
            field=models.CharField(default='unknown', max_length=20),
        ),
    ]
