# Generated by Django 5.2.5 on 2025-08-27 11:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nice_lite', '0017_jobmodel_preprocessing_update'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobmodel',
            name='optics_assigment_heartbeat',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jobmodel',
            name='optics_assigment_stats',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='jobmodel',
            name='optics_assigment_status',
            field=models.CharField(default='unknown', max_length=20),
        ),
        migrations.AddField(
            model_name='jobmodel',
            name='optics_assigment_update',
            field=models.JSONField(default=dict),
        ),
    ]
