# Generated by Django 5.2.5 on 2025-08-27 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nice_lite', '0018_jobmodel_optics_assigment_heartbeat_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobmodel',
            old_name='optics_assigment_heartbeat',
            new_name='optics_assignment_heartbeat',
        ),
        migrations.RenameField(
            model_name='jobmodel',
            old_name='optics_assigment_stats',
            new_name='optics_assignment_stats',
        ),
        migrations.RenameField(
            model_name='jobmodel',
            old_name='optics_assigment_status',
            new_name='optics_assignment_status',
        ),
        migrations.RenameField(
            model_name='jobmodel',
            old_name='optics_assigment_update',
            new_name='optics_assignment_update',
        ),
    ]
