# Generated by Django 5.2.5 on 2025-09-05 09:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nice_lite', '0022_jobmodel_particle_sieving_heartbeat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobmodel',
            name='classification_2D_heartbeat',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jobmodel',
            name='classification_2D_stats',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='jobmodel',
            name='classification_2D_status',
            field=models.CharField(default='unknown', max_length=20),
        ),
        migrations.AddField(
            model_name='jobmodel',
            name='classification_2D_update',
            field=models.JSONField(default=dict),
        ),
    ]
