# Generated by Django 5.2.5 on 2025-09-11 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nice_lite', '0025_workspacemodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspacemodel',
            name='nstr',
            field=models.JSONField(default=dict),
        ),
    ]
