# Generated by Django 5.2.5 on 2025-09-12 08:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nice_lite', '0026_workspacemodel_nstr'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobClassicModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=200)),
                ('desc', models.CharField(default='', max_length=200)),
                ('dirc', models.CharField(default='', max_length=200)),
                ('cdat', models.DateTimeField()),
                ('args', models.JSONField(default=dict)),
                ('wspc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nice_lite.workspacemodel')),
            ],
        ),
    ]
