# Generated by Django 5.2.5 on 2025-09-12 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nice_lite', '0027_jobclassicmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobclassicmodel',
            name='disp',
            field=models.IntegerField(default=0),
        ),
    ]
