# Generated by Django 5.2.5 on 2025-09-17 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nice_lite', '0029_jobclassicmodel_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobclassicmodel',
            name='pckg',
            field=models.CharField(default='', max_length=20),
        ),
    ]
