# Generated by Django 5.2.5 on 2025-09-17 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nice_lite', '0030_jobclassicmodel_pckg'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobclassicmodel',
            name='prnt',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='jobclassicmodel',
            name='prog',
            field=models.CharField(default='', max_length=200),
        ),
    ]
