# Generated by Django 5.2.5 on 2025-09-17 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nice_lite', '0031_jobclassicmodel_prnt_jobclassicmodel_prog'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobmodel',
            name='status',
            field=models.CharField(default='unknown', max_length=20),
        ),
    ]
