# Generated by Django 5.2.5 on 2025-09-18 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nice_lite', '0032_jobmodel_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispatchmodel',
            name='url',
            field=models.CharField(default='', max_length=200),
        ),
    ]
