# Generated by Django 5.2.5 on 2025-09-25 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nice_lite', '0033_dispatchmodel_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasetmodel',
            name='disp',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='jobmodel',
            name='disp',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='workspacemodel',
            name='disp',
            field=models.IntegerField(default=0),
        ),
    ]
