/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * LogYamlTestGUI.java
 *
 * Created on Oct 1, 2012, 2:19:25 PM
 */

package org.openmolgrid.common;

/**
 *
 * @author Frederic Bonnet
 */
public class LogYamlTestGUI extends javax.swing.JPanel {

    /** Creates new form LogYamlTestGUI */
    public LogYamlTestGUI() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        logYamlFilenamePanel = new javax.swing.JPanel();
        logYamlfilenameLabel = new javax.swing.JLabel();
        logYamlFilenameTextField = new javax.swing.JTextField();
        changeFilenameButton = new javax.swing.JButton();
        viewFilenameButton = new javax.swing.JButton();
        closeButton = new javax.swing.JButton();
        testYamlFileButton = new javax.swing.JButton();
        logYamlDumperPanel = new javax.swing.JPanel();
        logYamlDumperScrollPane = new javax.swing.JScrollPane();
        logYamlDumperTextArea = new javax.swing.JTextArea();
        refreshTextAreaButton = new javax.swing.JButton();

        logYamlFilenamePanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "log.yaml filename Panel...", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 12), new java.awt.Color(7, 59, 241))); // NOI18N

        logYamlfilenameLabel.setFont(new java.awt.Font("DejaVu Sans", 1, 13)); // NOI18N
        logYamlfilenameLabel.setText("log.yaml file:");

        changeFilenameButton.setText("Change file");
        changeFilenameButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changeFilenameButtonActionPerformed(evt);
            }
        });

        viewFilenameButton.setText("View file");
        viewFilenameButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewFilenameButtonActionPerformed(evt);
            }
        });

        closeButton.setText("Close");
        closeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeButtonActionPerformed(evt);
            }
        });

        testYamlFileButton.setText("Test Yaml file");
        testYamlFileButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                testYamlFileButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout logYamlFilenamePanelLayout = new javax.swing.GroupLayout(logYamlFilenamePanel);
        logYamlFilenamePanel.setLayout(logYamlFilenamePanelLayout);
        logYamlFilenamePanelLayout.setHorizontalGroup(
            logYamlFilenamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(logYamlFilenamePanelLayout.createSequentialGroup()
                .addGroup(logYamlFilenamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(logYamlfilenameLabel)
                    .addComponent(closeButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(logYamlFilenamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, logYamlFilenamePanelLayout.createSequentialGroup()
                        .addComponent(testYamlFileButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(changeFilenameButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(viewFilenameButton))
                    .addComponent(logYamlFilenameTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 255, Short.MAX_VALUE))
                .addContainerGap())
        );
        logYamlFilenamePanelLayout.setVerticalGroup(
            logYamlFilenamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(logYamlFilenamePanelLayout.createSequentialGroup()
                .addGroup(logYamlFilenamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(logYamlfilenameLabel)
                    .addComponent(logYamlFilenameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(logYamlFilenamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(viewFilenameButton)
                    .addComponent(closeButton)
                    .addComponent(changeFilenameButton)
                    .addComponent(testYamlFileButton)))
        );

        logYamlDumperPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "log.yaml dumper check...", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 12), new java.awt.Color(7, 59, 241))); // NOI18N

        logYamlDumperTextArea.setColumns(20);
        logYamlDumperTextArea.setRows(5);
        logYamlDumperScrollPane.setViewportView(logYamlDumperTextArea);

        refreshTextAreaButton.setText("Refresh");

        javax.swing.GroupLayout logYamlDumperPanelLayout = new javax.swing.GroupLayout(logYamlDumperPanel);
        logYamlDumperPanel.setLayout(logYamlDumperPanelLayout);
        logYamlDumperPanelLayout.setHorizontalGroup(
            logYamlDumperPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, logYamlDumperPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(refreshTextAreaButton))
            .addComponent(logYamlDumperScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 375, Short.MAX_VALUE)
        );
        logYamlDumperPanelLayout.setVerticalGroup(
            logYamlDumperPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, logYamlDumperPanelLayout.createSequentialGroup()
                .addComponent(logYamlDumperScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 131, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(refreshTextAreaButton))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(logYamlDumperPanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(logYamlFilenamePanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(logYamlFilenamePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(logYamlDumperPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void closeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_closeButtonActionPerformed

    private void testYamlFileButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_testYamlFileButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_testYamlFileButtonActionPerformed

    private void changeFilenameButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changeFilenameButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_changeFilenameButtonActionPerformed

    private void viewFilenameButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewFilenameButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_viewFilenameButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton changeFilenameButton;
    private javax.swing.JButton closeButton;
    private javax.swing.JPanel logYamlDumperPanel;
    private javax.swing.JScrollPane logYamlDumperScrollPane;
    private javax.swing.JTextArea logYamlDumperTextArea;
    private javax.swing.JPanel logYamlFilenamePanel;
    private javax.swing.JTextField logYamlFilenameTextField;
    private javax.swing.JLabel logYamlfilenameLabel;
    private javax.swing.JButton refreshTextAreaButton;
    private javax.swing.JButton testYamlFileButton;
    private javax.swing.JButton viewFilenameButton;
    // End of variables declaration//GEN-END:variables

}
