# Generated by Django 5.2.5 on 2025-08-22 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nice_lite', '0007_dispatchmodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobmodel',
            old_name='date',
            new_name='cdat',
        ),
    ]
