# Generated by Django 5.2.5 on 2025-08-22 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nice_lite', '0008_rename_date_jobmodel_cdat'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobmodel',
            name='args',
            field=models.JSONField(default=''),
        ),
    ]
