# Generated by Django 5.2.5 on 2025-08-22 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nice_lite', '0011_rename_desc_dispatchmodel_tplt_dispatchmodel_scmd'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispatchmodel',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
