# Generated by Django 5.2.5 on 2025-09-09 11:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nice_lite', '0024_jobmodel_particle_sets_stats'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkspaceModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=200)),
                ('desc', models.CharField(default='', max_length=200)),
                ('dirc', models.CharField(default='', max_length=200)),
                ('link', models.CharField(default='', max_length=200)),
                ('cdat', models.DateTimeField(auto_now_add=True)),
                ('mdat', models.DateTimeField(auto_now_add=True)),
                ('proj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nice_lite.projectmodel')),
            ],
        ),
    ]
