# Generated by Django 5.2.5 on 2025-09-16 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nice_lite', '0028_jobclassicmodel_disp'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobclassicmodel',
            name='status',
            field=models.CharField(default='unknown', max_length=20),
        ),
    ]
