# Generated by Django 5.2.5 on 2026-02-26 15:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nice_lite', '0035_jobclassicmodel_heartbeat_jobclassicmodel_update'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasetmodel',
            name='jcnt',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='datasetmodel',
            name='user',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='jobmodel',
            name='master_heartbeat',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jobmodel',
            name='master_stats',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='jobmodel',
            name='master_status',
            field=models.CharField(default='unknown', max_length=20),
        ),
        migrations.AddField(
            model_name='jobmodel',
            name='master_update',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='workspacemodel',
            name='jcnt',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='workspacemodel',
            name='user',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='projectmodel',
            name='desc',
            field=models.CharField(default='', max_length=1024),
        ),
        migrations.AlterField(
            model_name='projectmodel',
            name='dirc',
            field=models.CharField(default='', max_length=1024),
        ),
    ]
