/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * SimplePrimePanel.java
 *
 * Created on 17/11/2015, 12:07:42 PM
 */

package edu.kit.gridbeans.simpleprime.plugin;

import com.intel.gpe.clients.api.Client;
import com.intel.gpe.gridbeans.plugins.DataSetException;
import com.intel.gpe.gridbeans.plugins.swing.panels.GridBeanPanel;
import com.intel.gpe.util.defaults.preferences.INode;

/**
 *
 * @author Frederic Bonnet
 * @Date 17th of November 2015
 */
public class SimplePrimePanel extends GridBeanPanel {

    /**
	 * Add UID
	 */
	private static final long serialVersionUID = 9030545336915640959L;

	/** Creates new form SimplePrimePanel */
    public SimplePrimePanel(Client client, INode node) {
    	super(client , "SimplePrime", node);
        initComponents();
        try {
        	initTab();
        } catch (DataSetException e) {
        	getClient().showException("error creating SimplePrime panel", e);
        }
    }
    
    private void initTab() throws DataSetException{
		// TODO Auto-generated method stub
        WelcomPrimeJPanel welcomePrimePanel = new WelcomPrimeJPanel(this);
        SimplePrimeJPanel simplePrimePanel = new SimplePrimeJPanel(this);
        PerformancePrimeJPanel performancePrimePanel = new PerformancePrimeJPanel(this);
        
        mainSimplePrimejTabbedPanel.addTab("0. Start here, general options", welcomePrimePanel);
		mainSimplePrimejTabbedPanel.addTab("1. simple_prime2 panel", simplePrimePanel);
        mainSimplePrimejTabbedPanel.addTab("2. Performance panel", performancePrimePanel);
	}

	/** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainSimplePrimejTabbedPanel = new javax.swing.JTabbedPane();

        setLayout(new java.awt.BorderLayout());
        add(mainSimplePrimejTabbedPanel, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane mainSimplePrimejTabbedPanel;
    // End of variables declaration//GEN-END:variables

}
