/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * WelcomPrimeJPanel.java
 *
 * Created on 25/11/2015, 12:56:10 AM
 */

package edu.kit.gridbeans.simpleprime.plugin;

import javax.swing.JPanel;

import com.intel.gpe.gridbeans.plugins.DataSetException;
import com.intel.gpe.gridbeans.plugins.swing.panels.GridBeanPanel;

/**
 *
 * @author Frederic Bonnet
 * @Date 25th of November 2015
 * 
 */
public class WelcomPrimeJPanel extends JPanel {
    private GridBeanPanel parentPanel;
    /**
     * Add UID
     */
    private static final long serialVersionUID = -1680465197055935745L;
    /** Creates new form WelcomPrimeJPanel */
    public WelcomPrimeJPanel(GridBeanPanel parentpanel) throws DataSetException {
        this.parentPanel = parentpanel;
        initComponents();
        initCustomComponents();
        bindComponents();
    }

    private void initCustomComponents() {
        // TODO Auto-generated method stub
       
    }

    private void bindComponents() {
        // TODO Auto-generated method stub
        
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainWelcomePrimeScrollPanel = new javax.swing.JScrollPane();
        mainWelcomePrimePanel = new javax.swing.JPanel();
        graphicWelcomPrimePanel = new javax.swing.JPanel();
        generalOptionsEoRecVolPanel = new javax.swing.JPanel();
        infoWelcomePrimeScrollPanel = new javax.swing.JScrollPane();
        infoWelcomeTextArea = new javax.swing.JTextArea();
        contributorsButton = new javax.swing.JButton();
        refreshTextAreaButton = new javax.swing.JButton();
        helpWelcomePrimeButton = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout());

        graphicWelcomPrimePanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(-16777216,true)));

        javax.swing.GroupLayout graphicWelcomPrimePanelLayout = new javax.swing.GroupLayout(graphicWelcomPrimePanel);
        graphicWelcomPrimePanel.setLayout(graphicWelcomPrimePanelLayout);
        graphicWelcomPrimePanelLayout.setHorizontalGroup(
            graphicWelcomPrimePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 361, Short.MAX_VALUE)
        );
        graphicWelcomPrimePanelLayout.setVerticalGroup(
            graphicWelcomPrimePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 47, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout generalOptionsEoRecVolPanelLayout = new javax.swing.GroupLayout(generalOptionsEoRecVolPanel);
        generalOptionsEoRecVolPanel.setLayout(generalOptionsEoRecVolPanelLayout);
        generalOptionsEoRecVolPanelLayout.setHorizontalGroup(
            generalOptionsEoRecVolPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 364, Short.MAX_VALUE)
        );
        generalOptionsEoRecVolPanelLayout.setVerticalGroup(
            generalOptionsEoRecVolPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 36, Short.MAX_VALUE)
        );

        infoWelcomeTextArea.setColumns(20);
        infoWelcomeTextArea.setRows(5);
        infoWelcomePrimeScrollPanel.setViewportView(infoWelcomeTextArea);

        contributorsButton.setText("Contributors");
        contributorsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contributorsButtonActionPerformed(evt);
            }
        });

        refreshTextAreaButton.setText("Refresh");
        refreshTextAreaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshTextAreaButtonActionPerformed(evt);
            }
        });

        helpWelcomePrimeButton.setText("Help");
        helpWelcomePrimeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                helpWelcomePrimeButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout mainWelcomePrimePanelLayout = new javax.swing.GroupLayout(mainWelcomePrimePanel);
        mainWelcomePrimePanel.setLayout(mainWelcomePrimePanelLayout);
        mainWelcomePrimePanelLayout.setHorizontalGroup(
            mainWelcomePrimePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainWelcomePrimePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(mainWelcomePrimePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(graphicWelcomPrimePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(mainWelcomePrimePanelLayout.createSequentialGroup()
                        .addComponent(contributorsButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(refreshTextAreaButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(helpWelcomePrimeButton))
                    .addComponent(infoWelcomePrimeScrollPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 364, Short.MAX_VALUE)
                    .addComponent(generalOptionsEoRecVolPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(389, Short.MAX_VALUE))
        );
        mainWelcomePrimePanelLayout.setVerticalGroup(
            mainWelcomePrimePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainWelcomePrimePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(graphicWelcomPrimePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(generalOptionsEoRecVolPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(infoWelcomePrimeScrollPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(mainWelcomePrimePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(contributorsButton)
                    .addComponent(refreshTextAreaButton)
                    .addComponent(helpWelcomePrimeButton))
                .addContainerGap(124, Short.MAX_VALUE))
        );

        mainWelcomePrimeScrollPanel.setViewportView(mainWelcomePrimePanel);

        add(mainWelcomePrimeScrollPanel, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void contributorsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contributorsButtonActionPerformed
        /**
         * Add a contributor splash screen
         */
        ContributorSplashScreen contributors = new ContributorSplashScreen();
        contributors.setVisible(true);
}//GEN-LAST:event_contributorsButtonActionPerformed

    private void refreshTextAreaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshTextAreaButtonActionPerformed
        infoWelcomeTextArea.setText("");
}//GEN-LAST:event_refreshTextAreaButtonActionPerformed

    private void helpWelcomePrimeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_helpWelcomePrimeButtonActionPerformed
        /**
         * add the help window in the welcome Panel
         */
        HelpWelcomePrimeSimple helpwindowinWelcomePanel = new HelpWelcomePrimeSimple();
        helpwindowinWelcomePanel.setVisible(true);
}//GEN-LAST:event_helpWelcomePrimeButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton contributorsButton;
    private javax.swing.JPanel generalOptionsEoRecVolPanel;
    private javax.swing.JPanel graphicWelcomPrimePanel;
    private javax.swing.JButton helpWelcomePrimeButton;
    private javax.swing.JScrollPane infoWelcomePrimeScrollPanel;
    private javax.swing.JTextArea infoWelcomeTextArea;
    private javax.swing.JPanel mainWelcomePrimePanel;
    private javax.swing.JScrollPane mainWelcomePrimeScrollPanel;
    private javax.swing.JButton refreshTextAreaButton;
    // End of variables declaration//GEN-END:variables

}
