##
# Print some post install messages for the user
##
message("\n\n")
message("Installation complete.")
message("==========================================================================")
message("Please ensure the following variables are set properly in add2.*rc file:  ")
message("    SIMPLE_EMAIL  SIMPLE_QSYS  SIMPLE_PATH                                ")
message("To use SIMPLE, append the relevant add2.* to your HOME shell rc file:     ")
message(" bash$ cat add2.bashrc >> ~/.bashrc                                       ")
message(" tcsh$ cat add2.tcshrc >> ~/.tcshrc                                       ")

if (${CMAKE_SYSTEM_NAME} MATCHES "Darwin")
	message("Fixing library names with install_name_tool")
#	execute_process(COMMAND install_name_tool -add_rpath ${CMAKE_INSTALL_PREFIX}/lib ${CMAKE_INSTALL_PREFIX}/bin/simple_exec)
#	execute_process(COMMAND install_name_tool -add_rpath ${CMAKE_INSTALL_PREFIX}/lib ${CMAKE_INSTALL_PREFIX}/bin/simple_distr_exec)
endif()
message("==========================================================================")
message("For minimal installation to work correctly add:\n${CMAKE_INSTALL_PREFIX}/bin and\n${CMAKE_INSTALL_PREFIX}/scripts\n to your PATH environment variable.")
if(BUILD_SHARED_LIBS)
message("For shared or dynamic builds: ")
if ("${CMAKE_SYSTEM_NAME}" MATCHES "Darwin")
	message("MacOS users: SHARED LIB: see add2.*rc about appending ${CMAKE_INSTALL_PREFIX}/lib to one of: \n\tLD_LIBRARY_PATH\tDYLD_LIBRARY_PATH or\n\tDYLD_FALLBACK_LIBRARY_PATH or\n\tRPATH ")
else()
	message("SHARED LIB: ${CMAKE_INSTALL_PREFIX}/lib appended LD_LIBRARY_PATH")
endif()
endif()
message("==========================================================================")
if(${CMAKE_Fortran_COMPILER_ID} STREQUAL "Intel")
	message("Intel® Math Kernel Library Link Line Advisor: ")
message("  o Set the INCLUDE, MKLROOT, LD_LIBRARY_PATH, LIBRARY_PATH, CPATH and NLSPATH environment variables in the command shell using one of mklvars script files in the 'bin' subdirectory of the Intel(R) MKL installation directory. Please see also the Intel(R) MKL User Guide.")
message("  o Set the environment variable: MKL_MIC_ENABLE=1, when using Intel® Xeon Phi™ Coprocessor Automatic offload")
message("  o Please be sure that you have used the recommended compiler options for the selected interface layer. Caution: linking Intel(R) MKL libraries with your objects compiled for different interface layer may lead to run-time errors.")
  endif()
message("\n\n")
