/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class JavaCode */

#ifndef _Included_JavaCode
#define _Included_JavaCode
#ifdef __cplusplus
extern "C" {
#endif
#undef JavaCode_MAXSIZE
#define JavaCode_MAXSIZE 10L
/*
 * Class:     JavaCode
 * Method:    sumsquaredc
 * Signature: ([I)I
 */
JNIEXPORT jint JNICALL Java_JavaCode_sumsquaredc
  (JNIEnv *, jobject, jintArray);

#ifdef __cplusplus
}
#endif
#endif
