!@descr: generic command-line parsing for SIMPLE parameters using typed input bindings
submodule(simple_parameters) simple_parameters_parse
implicit none
#include "simple_local_flags.inc"

contains

    module subroutine parse_inputs(self, cline, cntfile, checkupfile)
        class(parameters), intent(inout) :: self
        class(cmdline),    intent(inout) :: cline
        integer,           intent(inout) :: cntfile
        character(len=1),  intent(inout) :: checkupfile(:)
        type(param_registry) :: reg
        call reg%clear()
        call self%bind_input_carg(reg)
        call reg%apply_cmdline(cline)
        call reg%clear()
        call self%bind_input_files(reg)
        call reg%apply_cmdline(cline, cntfile, checkupfile)
        call reg%clear()
        call self%bind_input_dirs(reg)
        call reg%apply_cmdline(cline)
        call reg%clear()
        call self%bind_input_iarg(reg)
        call reg%apply_cmdline(cline)
        call reg%clear()
        call self%bind_input_rarg(reg)
        call reg%apply_cmdline(cline)
    end subroutine parse_inputs

    module subroutine bind_input_carg(self, reg)
        class(parameters),   target, intent(inout) :: self
        class(param_registry),       intent(inout) :: reg
        call reg%add_char('acf', self%acf)
        call reg%add_char('algorithm', self%algorithm)
        call reg%add_char('angastunit', self%angastunit)
        call reg%add_char('append', self%append)
        call reg%add_char('async', self%async)
        call reg%add_char('atom_thres', self%atom_thres)
        call reg%add_char('automsk', self%automsk)
        call reg%add_char('automatic', self%automatic)
        call reg%add_char('autoscale', self%autoscale)
        call reg%add_char('avg', self%avg)
        call reg%add_char('backgr_subtr', self%backgr_subtr)
        call reg%add_char('balance', self%balance)
        call reg%add_char('bin', self%bin)
        call reg%add_char('boxes', self%boxes)
        call reg%add_char('cavg_ini', self%cavg_ini)
        call reg%add_char('cavg_ini_ext', self%cavg_ini_ext)
        call reg%add_char('center', self%center)
        call reg%add_char('center_pdb', self%center_pdb)
        call reg%add_char('center_type', self%center_type)
        call reg%add_char('chunk', self%chunk)
        call reg%add_char('class_assignment', self%class_assignment)
        call reg%add_char('classtats', self%classtats)
        call reg%add_char('clear', self%clear)
        call reg%add_char('cls_init', self%cls_init)
        call reg%add_char('clustinds', self%clustinds)
        call reg%add_char('clust_crit', self%clust_crit)
        call reg%add_char('cn_type', self%cn_type)
        call reg%add_char('combine_eo', self%combine_eo)
        call reg%add_char('continue', self%continue)
        call reg%add_char('ctf', self%ctf)
        call reg%add_char('ctfpatch', self%ctfpatch)
        call reg%add_char('conical_fsc', self%conical_fsc)
        call reg%add_char('ctfstats', self%ctfstats)
        call reg%add_char('detector', self%detector)
        call reg%add_char('dfunit', self%dfunit)
        call reg%add_char('dir_exec', self%dir_exec)
        call reg%add_char('downscale', self%downscale)
        call reg%add_char('doprint', self%doprint)
        call reg%add_char('dynreslim', self%dynreslim)
        call reg%add_char('dw', self%dw)
        call reg%add_char('element', self%element)
        call reg%add_char('envfsc', self%envfsc)
        call reg%add_char('eo_stage', self%eo_stage)
        call reg%add_char('even', self%even)
        call reg%add_char('extract', self%extract)
        call reg%add_char('extractfrommov', self%extractfrommov)
        call reg%add_char('startype', self%startype)
        call reg%add_char('fbody', self%fbody)
        call reg%add_char('fill_holes', self%fill_holes)
        call reg%add_char('fillin', self%fillin)
        call reg%add_char('update_missing', self%update_missing)
        call reg%add_char('filter', self%filter)
        call reg%add_char('flag', self%flag)
        call reg%add_char('flipgain', self%flipgain)
        call reg%add_char('force_lp_range', self%force_lp_range)
        call reg%add_char('gauref', self%gauref)
        call reg%add_char('gen_model', self%gen_model)
        call reg%add_char('graph', self%graph)
        call reg%add_char('guinier', self%guinier)
        call reg%add_char('graphene_filt', self%graphene_filt)
        call reg%add_char('greedy_sampling', self%greedy_sampling)
        call reg%add_char('hist', self%hist)
        call reg%add_char('icm', self%icm)
        call reg%add_char('imgkind', self%imgkind)
        call reg%add_char('incrreslim', self%incrreslim)
        call reg%add_char('interactive', self%interactive)
        call reg%add_char('iterstats', self%iterstats)
        call reg%add_char('json', self%json)
        call reg%add_char('keepvol', self%keepvol)
        call reg%add_char('keys', self%keys)
        call reg%add_char('lam_anneal', self%lam_anneal)
        call reg%add_char('linethres', self%linethres)
        call reg%add_char('loc_sdev', self%loc_sdev)
        call reg%add_char('filt_mode', self%filt_mode)
        call reg%add_char('makemovie', self%makemovie)
        call reg%add_char('mcpatch', self%mcpatch)
        call reg%add_char('mcpatch_thres', self%mcpatch_thres)
        call reg%add_char('mirr', self%mirr)
        call reg%add_char('mirr_proj', self%mirr_proj)
        call reg%add_char('mkdir', self%mkdir)
        call reg%add_char('ml_reg', self%ml_reg)
        call reg%add_char('ml_reg_chunk', self%ml_reg_chunk)
        call reg%add_char('ml_reg_pool', self%ml_reg_pool)
        call reg%add_char('mcconvention', self%mcconvention)
        call reg%add_char('multi_moldiams', self%multi_moldiams)
        call reg%add_char('multivol_mode', self%multivol_mode)
        call reg%add_char('neg', self%neg)
        call reg%add_char('neigs_per', self%neigs_per)
        call reg%add_char('niceserver', self%niceserver)
        call reg%add_char('noise_norm', self%noise_norm)
        call reg%add_char('norm', self%norm)
        call reg%add_char('nu_refine', self%nu_refine)
        call reg%add_char('objfun', self%objfun)
        call reg%add_char('omit_neg', self%omit_neg)
        call reg%add_char('opt', self%opt)
        call reg%add_char('optics_dir', self%optics_dir)
        call reg%add_char('oritype', self%oritype)
        call reg%add_char('outdir', self%outdir)
        call reg%add_char('outside', self%outside)
        call reg%add_char('pad', self%pad)
        call reg%add_char('partition', self%partition)
        call reg%add_char('pca_mode', self%pca_mode)
        call reg%add_char('steering', self%steering)
        call reg%add_char('kpca_backend', self%kpca_backend)
        call reg%add_char('kpca_ker', self%kpca_ker)
        call reg%add_char('pcontrast', self%pcontrast)
        call reg%add_char('pickkind', self%pickkind)
        call reg%add_char('pgrp', self%pgrp)
        call reg%add_char('pgrp_start', self%pgrp_start)
        call reg%add_char('pca_img_ori', self%pca_img_ori)
        call reg%add_char('pca_ori_stk', self%pca_ori_stk)
        call reg%add_char('phaseplate', self%phaseplate)
        call reg%add_char('phrand', self%phrand)
        call reg%add_char('phshiftunit', self%phshiftunit)
        call reg%add_char('pick_roi', self%pick_roi)
        call reg%add_char('particle_density', self%particle_density)
        call reg%add_char('picker', self%picker)
        call reg%add_char('platonic', self%platonic)
        call reg%add_char('plot_key', self%plot_key)
        call reg%add_char('postprocess', self%postprocess)
        call reg%add_char('pre_norm', self%pre_norm)
        call reg%add_char('prg', self%prg)
        call reg%add_char('print_states', self%print_states)
        call reg%add_char('prob_inpl', self%prob_inpl)
        call reg%add_char('prob_neigh_mode', self%prob_neigh_mode)
        call reg%add_char('proj_is_class', self%proj_is_class)
        call reg%add_char('projfile_merged', self%projfile_merged)
        call reg%add_char('projfile_optics', self%projfile_optics)
        call reg%add_char('projname', self%projname)
        call reg%add_char('projstats', self%projstats)
        call reg%add_char('protocol', self%protocol)
        call reg%add_char('prune', self%prune)
        call reg%add_char('qsys_name', self%qsys_name)
        call reg%add_char('qsys_partition2D', self%qsys_partition2D)
        call reg%add_char('quality_mode', self%quality_mode)
        call reg%add_char('quality_model', self%quality_model)
        call reg%add_char('randomise', self%randomise)
        call reg%add_char('rank_cavgs', self%rank_cavgs)
        call reg%add_char('ranked_parts', self%ranked_parts)
        call reg%add_char('real_filter', self%real_filter)
        call reg%add_char('ptcl_src', self%ptcl_src)
        call reg%add_char('recthres', self%recthres)
        call reg%add_char('refine', self%refine)
        call reg%add_char('refine_type', self%refine_type)
        call reg%add_char('reject_mics', self%reject_mics)
        call reg%add_char('remove_chunks', self%remove_chunks)
        call reg%add_char('remap_cls', self%remap_cls)
        call reg%add_char('reset_boxfiles', self%reset_boxfiles)
        call reg%add_char('restore_cavgs', self%restore_cavgs)
        call reg%add_char('ring', self%ring)
        call reg%add_char('roavg', self%roavg)
        call reg%add_char('script', self%script)
        call reg%add_char('select_flag', self%select_flag)
        call reg%add_char('shbarrier', self%shbarrier)
        call reg%add_char('sigma_est', self%sigma_est)
        call reg%add_char('snapshot', self%snapshot)
        call reg%add_char('sort', self%sort)
        call reg%add_char('sort_asc', self%sort_asc)
        call reg%add_char('speckind', self%speckind)
        call reg%add_char('split_mode', self%split_mode)
        call reg%add_char('stats', self%stats)
        call reg%add_char('stream', self%stream)
        call reg%add_char('stream2d', self%stream2d)
        call reg%add_char('subprojname', self%subprojname)
        call reg%add_char('symrnd', self%symrnd)
        call reg%add_char('tag', self%tag)
        call reg%add_char('taper_edges', self%taper_edges)
        call reg%add_char('tester', self%tester)
        call reg%add_char('tophat', self%tophat)
        call reg%add_char('trail_rec', self%trail_rec)
        call reg%add_char('transp_pca', self%transp_pca)
        call reg%add_char('trsstats', self%trsstats)
        call reg%add_char('tseries', self%tseries)
        call reg%add_char('use_thres', self%use_thres)
        call reg%add_char('vis', self%vis)
        call reg%add_char('verbose_exit', self%verbose_exit)
        call reg%add_char('verbose_exit_fname', self%verbose_exit_fname)
        call reg%add_char('volrec', self%volrec)
        call reg%add_char('wcrit', self%wcrit)
        call reg%add_char('worker_priority', self%worker_priority)
        call reg%add_char('worker_server', self%worker_server)
        call reg%add_char('write_imgarr', self%write_imgarr)
        call reg%add_char('write_prior', self%write_prior)
        call reg%add_char('zero', self%zero)
        call reg%add_char('ciffile', self%ciffile)
    end subroutine bind_input_carg

    module subroutine bind_input_files(self, reg)
        class(parameters),   target, intent(inout) :: self
        class(param_registry),       intent(inout) :: reg
        call reg%add_file('boxfile', self%boxfile,'T')
        call reg%add_file('boxtab', self%boxtab,'T')
        call reg%add_file('classdoc', self%classdoc,'T')
        call reg%add_file('deftab', self%deftab,'T', 'O')
        call reg%add_file('deselfile', self%deselfile,'T')
        call reg%add_file('ext', self%ext,notAllowed='T')
        call reg%add_file('filetab', self%filetab,'T')
        call reg%add_file('fname', self%fname)
        call reg%add_file('frcs', self%frcs,'B')
        call reg%add_file('fsc', self%fsc,'B')
        call reg%add_file('gainref', self%gainref)
        call reg%add_file('infile', self%infile,'T')
        call reg%add_file('infile2', self%infile2,'T')
        call reg%add_file('oritab', self%oritab,'T', 'O')
        call reg%add_file('oritab2', self%oritab2,'T', 'O')
        call reg%add_file('outfile', self%outfile,'T', 'O')
        call reg%add_file('outstk', self%outstk,notAllowed='T')
        call reg%add_file('outvol', self%outvol,notAllowed='T')
        call reg%add_file('pdbfile', self%pdbfile)
        call reg%add_file('pdbfile2', self%pdbfile2)
        call reg%add_file('pdbfiles', self%pdbfiles,'T')
        call reg%add_file('pdbout', self%pdbout)
        call reg%add_file('pickrefs', self%pickrefs,notAllowed='T')
        call reg%add_file('plaintexttab', self%plaintexttab,'T')
        call reg%add_file('projfile', self%projfile,'O')
        call reg%add_file('projfile_orig', self%projfile_orig,'O')
        call reg%add_file('projfile_ref', self%projfile_ref,'O')
        call reg%add_file('projfile_target', self%projfile_target,'O')
        call reg%add_file('projtab', self%projtab,'T')
        call reg%add_file('refs', self%refs,notAllowed='T')
        call reg%add_file('starfile', self%starfile,'R')
        call reg%add_file('star_mic', self%star_mic,'R')
        call reg%add_file('star_model', self%star_model,'R')
        call reg%add_file('star_ptcl', self%star_ptcl,'R')
        call reg%add_file('stk', self%stk,notAllowed='T')
        call reg%add_file('stk_den', self%stk_den,notAllowed='T')
        call reg%add_file('stktab', self%stktab,'T')
        call reg%add_file('stktab_den', self%stktab_den,'T')
        call reg%add_file('stk2', self%stk2,notAllowed='T')
        call reg%add_file('stk3', self%stk3,notAllowed='T')
        call reg%add_file('stk_backgr', self%stk_backgr,notAllowed='T')
        call reg%add_file('vol_even', self%vol_even,notAllowed='T')
        call reg%add_file('vol_odd', self%vol_odd,notAllowed='T')
    end subroutine bind_input_files

    module subroutine bind_input_dirs(self, reg)
        class(parameters),   target, intent(inout) :: self
        class(param_registry),       intent(inout) :: reg
        call reg%add_dir('dir', self%dir)
        call reg%add_dir('dir_box', self%dir_box)
        call reg%add_dir('dir_meta', self%dir_meta)
        call reg%add_dir('dir_movies', self%dir_movies)
        call reg%add_dir('dir_prev', self%dir_prev)
        call reg%add_dir('dir_refine', self%dir_refine)
        call reg%add_dir('dir_reject', self%dir_reject)
        call reg%add_dir('dir_select', self%dir_select)
        call reg%add_dir('dir_target', self%dir_target)
        call reg%add_dir('star_datadir', self%star_datadir)
    end subroutine bind_input_dirs

    module subroutine bind_input_iarg(self, reg)
        class(parameters),   target, intent(inout) :: self
        class(param_registry),       intent(inout) :: reg
        call reg%add_int('angstep', self%angstep)
        call reg%add_int('binwidth', self%binwidth)
        call reg%add_int('box', self%box)
        call reg%add_int('box_crop', self%box_crop)
        call reg%add_int('box_extract', self%box_extract)
        call reg%add_int('clip', self%clip)
        call reg%add_int('clustind', self%clustind)
        call reg%add_int('cn', self%cn)
        call reg%add_int('cn_max', self%cn_max)
        call reg%add_int('cn_min', self%cn_min)
        call reg%add_int('cn_stop', self%cn_stop)
        call reg%add_int('cs_thres', self%cs_thres)
        call reg%add_int('device', self%device)
        call reg%add_int('edge', self%edge)
        call reg%add_int('eer_fraction', self%eer_fraction)
        call reg%add_int('eer_upsampling', self%eer_upsampling)
        call reg%add_int('extr_iter', self%extr_iter)
        call reg%add_int('extr_lim', self%extr_lim)
        call reg%add_int('find', self%find)
        call reg%add_int('gauref_last_stage', self%gauref_last_stage)
        call reg%add_int('nframesgrp', self%nframesgrp)
        call reg%add_int('fromp', self%fromp)
        call reg%add_int('fromf', self%fromf)
        call reg%add_int('grow', self%grow)
        call reg%add_int('icm_stage', self%icm_stage)
        call reg%add_int('iptcl', self%iptcl)
        call reg%add_int('job_memory_per_task2D', self%job_memory_per_task2D)
        call reg%add_int('maxits', self%maxits)
        call reg%add_int('maxits_glob', self%maxits_glob)
        call reg%add_int('maxits_between', self%maxits_between)
        call reg%add_int('maxits_sh', self%maxits_sh)
        call reg%add_int('maxnchunks', self%maxnchunks)
        call reg%add_int('maxnptcls', self%maxnptcls)
        call reg%add_int('maxpop', self%maxpop)
        call reg%add_int('minits', self%minits)
        call reg%add_int('nboxes_max', self%nboxes_max)
        call reg%add_int('nchunks', self%nchunks)
        call reg%add_int('nchunksperset', self%nchunksperset)
        call reg%add_int('ncls', self%ncls)
        call reg%add_int('ncls_sub', self%ncls_sub)
        call reg%add_int('nsubcls_min', self%nsubcls_min)
        call reg%add_int('nsubcls_max', self%nsubcls_max)
        call reg%add_int('ncls_start', self%ncls_start)
        call reg%add_int('ncunits', self%ncunits)
        call reg%add_int('ndiscrete', self%ndiscrete)
        call reg%add_int('neigs', self%neigs)
        call reg%add_int('kpca_nystrom_npts', self%kpca_nystrom_npts)
        call reg%add_int('kpca_nystrom_local_nbrs', self%kpca_nystrom_local_nbrs)
        call reg%add_int('k_nn', self%k_nn)
        call reg%add_int('steerable_nmodes', self%steerable_nmodes)
        call reg%add_int('newbox', self%newbox)
        call reg%add_int('nframes', self%nframes)
        call reg%add_int('ngrow', self%ngrow)
        call reg%add_int('niceprocid', self%niceprocid)
        call reg%add_int('nicedispid', self%nicedispid)
        call reg%add_int('ninipick', self%ninipick)
        call reg%add_int('ninit', self%ninit)
        call reg%add_int('nits_per_stage', self%nits_per_stage)
        call reg%add_int('nmics', self%nmics)
        call reg%add_int('nmoldiams', self%nmoldiams)
        call reg%add_int('nsearch', self%nsearch)
        call reg%add_int('noris', self%noris)
        call reg%add_int('nran', self%nran)
        call reg%add_int('nrefs', self%nrefs)
        call reg%add_int('nrestarts', self%nrestarts)
        call reg%add_int('nsample', self%nsample)
        call reg%add_int('nsample_max', self%nsample_max)
        call reg%add_int('nsample_start', self%nsample_start)
        call reg%add_int('nsample_stop', self%nsample_stop)
        call reg%add_int('nspace', self%nspace)
        call reg%add_int('nspace_sub', self%nspace_sub)
        call reg%add_int('nspace_max', self%nspace_max)
        call reg%add_int('nstages', self%nstages)
        call reg%add_int('nstates', self%nstates)
        call reg%add_int('class', self%class)
        call reg%add_int('nparts', self%nparts)
        call reg%add_int('nparts_per_part', self%nparts_per_part)
        call reg%add_int('nparts_chunk', self%nparts_chunk)
        call reg%add_int('nparts_pool', self%nparts_pool)
        call reg%add_int('npeaks', self%npeaks)
        call reg%add_int('npeaks_inpl', self%npeaks_inpl)
        call reg%add_int('npix', self%npix)
        call reg%add_int('nptcls', self%nptcls)
        call reg%add_int('nptcls_per_cls', self%nptcls_per_cls)
        call reg%add_int('nptcls_per_subcls', self%nptcls_per_subcls)
        call reg%add_int('nptcls_per_part', self%nptcls_per_part)
        call reg%add_int('nquanta', self%nquanta)
        call reg%add_int('nthr', self%nthr)
        call reg%add_int('nthr2D', self%nthr2D)
        call reg%add_int('nthr_ini3D', self%nthr_ini3D)
        call reg%add_int('numlen', self%numlen)
        call reg%add_int('nxpatch', self%nxpatch)
        call reg%add_int('nypatch', self%nypatch)
        call reg%add_int('offset', self%offset)
        call reg%add_int('optics_offset', self%optics_offset)
        call reg%add_int('osmpl_fac', self%osmpl_fac)
        call reg%add_int('part', self%part)
        call reg%add_int('period', self%period)
        call reg%add_int('pftsz', self%pftsz)
        call reg%add_int('pspecsz', self%pspecsz)
        call reg%add_int('ref_ind', self%ref_ind)
        call reg%add_int('shift_stage', self%shift_stage)
        call reg%add_int('split_stage', self%split_stage)
        call reg%add_int('startit', self%startit)
        call reg%add_int('stage', self%stage)
        call reg%add_int('state', self%state)
        call reg%add_int('stepsz', self%stepsz)
        call reg%add_int('top', self%top)
        call reg%add_int('tof', self%tof)
        call reg%add_int('vol_dim', self%vol_dim)
        call reg%add_int('which_iter', self%which_iter)
        call reg%add_int('walltime', self%walltime)
        call reg%add_int('workers', self%workers)
        call reg%add_int('worker_nthr', self%worker_nthr)
        call reg%add_int('xdim', self%xdim)
        call reg%add_int('xcoord', self%xcoord)
        call reg%add_int('ycoord', self%ycoord)
        call reg%add_int('ydim', self%ydim)
    end subroutine bind_input_iarg

    module subroutine bind_input_rarg(self, reg)
        class(parameters),   target, intent(inout) :: self
        class(param_registry),       intent(inout) :: reg
        call reg%add_real('amsklp', self%amsklp)
        call reg%add_real('angerr', self%angerr)
        call reg%add_real('angthres_mi_proj', self%angthres_mi_proj)
        call reg%add_real('astigerr', self%astigerr)
        call reg%add_real('astigthreshold', self%astigthreshold)
        call reg%add_real('astigtol', self%astigtol)
        call reg%add_real('athres', self%athres)
        call reg%add_real('beta', self%beta)
        call reg%add_real('bfac', self%bfac)
        call reg%add_real('bfacerr', self%bfacerr)
        call reg%add_real('bw_ratio', self%bw_ratio)
        call reg%add_real('cenlp', self%cenlp)
        call reg%add_real('cs', self%cs)
        call reg%add_real('corr_thres', self%corr_thres)
        call reg%add_real('ctfresthreshold', self%ctfresthreshold)
        call reg%add_real('defocus', self%defocus)
        call reg%add_real('dferr', self%dferr)
        call reg%add_real('dfmax', self%dfmax)
        call reg%add_real('dfmin', self%dfmin)
        call reg%add_real('dfsdev', self%dfsdev)
        call reg%add_real('e1', self%e1)
        call reg%add_real('e2', self%e2)
        call reg%add_real('e3', self%e3)
        call reg%add_real('eps', self%eps)
        call reg%add_real('extr_init', self%extr_init)
        call reg%add_real('fraca', self%fraca)
        call reg%add_real('fracdeadhot', self%fracdeadhot)
        call reg%add_real('frac_best', self%frac_best)
        call reg%add_real('frac_worst', self%frac_worst)
        call reg%add_real('frac_diam', self%frac_diam)
        call reg%add_real('fracsrch', self%fracsrch)
        call reg%add_real('fraction_dose_target', self%fraction_dose_target)
        call reg%add_real('frac_outliers', self%frac_outliers)
        call reg%add_real('fraczero', self%fraczero)
        call reg%add_real('ftol', self%ftol)
        call reg%add_real('gaufreq', self%gaufreq)
        call reg%add_real('hp', self%hp)
        call reg%add_real('hp_ctf_estimate', self%hp_ctf_estimate)
        call reg%add_real('kpca_cosine_weight_power', self%kpca_cosine_weight_power)
        call reg%add_real('ppca_kpca_resid_alpha', self%ppca_kpca_resid_alpha)
        call reg%add_real('icefracthreshold', self%icefracthreshold)
        call reg%add_real('kv', self%kv)
        call reg%add_real('lambda', self%lambda)
        call reg%add_real('lp', self%lp)
        call reg%add_real('lp2D', self%lp2D)
        call reg%add_real('lp_backgr', self%lp_backgr)
        call reg%add_real('lp_ctf_estimate', self%lp_ctf_estimate)
        call reg%add_real('lp_discrete', self%lp_discrete)
        call reg%add_real('lp_pick', self%lp_pick)
        call reg%add_real('lplim_crit', self%lplim_crit)
        call reg%add_real('lpstart', self%lpstart)
        call reg%add_real('lpstop', self%lpstop)
        call reg%add_real('lpstart_ini3D', self%lpstart_ini3D)
        call reg%add_real('lpstop_ini3D', self%lpstop_ini3D)
        call reg%add_real('lpstop2D', self%lpstop2D)
        call reg%add_real('lpthres', self%lpthres)
        call reg%add_real('max_dose', self%max_dose)
        call reg%add_real('moldiam', self%moldiam)
        call reg%add_real('moldiam_max', self%moldiam_max)
        call reg%add_real('moldiam_refine', self%moldiam_refine)
        call reg%add_real('moldiam_ring', self%moldiam_ring)
        call reg%add_real('msk', self%msk)
        call reg%add_real('msk_crop', self%msk_crop)
        call reg%add_real('mskdiam', self%mskdiam)
        call reg%add_real('mskdiam_detect', self%mskdiam_detect)
        call reg%add_real('ndev', self%ndev)
        call reg%add_real('ndev2D', self%ndev2D)
        call reg%add_real('nsig', self%nsig)
        call reg%add_real('osmpd', self%osmpd)
        call reg%add_real('overlap', self%overlap)
        call reg%add_real('phranlp', self%phranlp)
        call reg%add_real('prob_athres', self%prob_athres)
        call reg%add_real('rec_athres', self%rec_athres)
        call reg%add_real('res_target', self%res_target)
        call reg%add_real('res_threshold', self%res_threshold)
        call reg%add_real('scale', self%scale)
        call reg%add_real('sherr', self%sherr)
        call reg%add_real('smpd', self%smpd)
        call reg%add_real('smpd_crop', self%smpd_crop)
        call reg%add_real('smpd_downscale', self%smpd_downscale)
        call reg%add_real('smpd_pickrefs', self%smpd_pickrefs)
        call reg%add_real('smpd_target', self%smpd_target)
        call reg%add_real('sigma', self%sigma)
        call reg%add_real('snr', self%snr)
        call reg%add_real('snr_noise_reg', self%snr_noise_reg)
        call reg%add_real('tau', self%tau)
        call reg%add_real('tilt_thres', self%tilt_thres)
        call reg%add_real('thres', self%thres)
        call reg%add_real('total_dose', self%total_dose)
        call reg%add_real('trs', self%trs)
        call reg%add_real('update_frac', self%update_frac)
        call reg%add_real('ufrac_trec', self%ufrac_trec)
        call reg%add_real('width', self%width)
        call reg%add_real('winsz', self%winsz)
        call reg%add_real('xsh', self%xsh)
        call reg%add_real('ysh', self%ysh)
        call reg%add_real('zsh', self%zsh)
    end subroutine bind_input_rarg

end submodule simple_parameters_parse
