##
# Print some post install messages for the user
##
message("\n\n")
message("Installation complete.")
message("==========================================================================")
message("Please ensure the following variables are set properly.                   ")
message("    SIMPLE_EMAIL  SIMPLE_QSYS  SIMPLE_PATH  SIMPLE_SOURCE_PATH            ")
message("Follow the instructions in README.txt by sourcing add2.bashrc or add2.tcshrc")
message(" or append the relevant add2.*rc to your HOME directory .*rc or .profile  ")
if (${CMAKE_SYSTEM_NAME} MATCHES "Darwin")
	message("Fixing library names with install_name_tool")
#	execute_process(COMMAND install_name_tool -add_rpath ${CMAKE_INSTALL_PREFIX}/lib ${CMAKE_INSTALL_PREFIX}/bin/simple_exec)
#	execute_process(COMMAND install_name_tool -add_rpath ${CMAKE_INSTALL_PREFIX}/lib ${CMAKE_INSTALL_PREFIX}/bin/simple_distr_exec)
endif()
message("For manual installation to work run correctly ${CMAKE_INSTALL_PREFIX}/bin \n and ${CMAKE_INSTALL_PREFIX}/scripts must be added to your PATH environment variable.")
message("For shared or dynamic builds: ")
if ("${CMAKE_SYSTEM_NAME}" MATCHES "Darwin")
	message("Please add ${CMAKE_INSTALL_PREFIX}/lib to  DYLD_FALLBACK_LIBRARY_PATH")
else()
	message("Please add ${CMAKE_INSTALL_PREFIX}/lib to  LD_LIBRARY_PATH")
endif()
message("==========================================================================")
message("\n\n")
