set(PATH $ENV{PATH})
set(LD_LIBRARY_PATH $ENV{LD_LIBRARY_PATH})

IF(NOT ${NICE_FQDN} MATCHES "OFF")
    message("USING FQDN " ${NICE_FQDN})
    set(FQDN ${NICE_FQDN})
ELSE()
    cmake_host_system_information(RESULT FQDN QUERY FQDN)
ENDIF()

set(USER  $ENV{USER})
configure_file(nice_project/wsgi.py.in nice_project/wsgi.py @ONLY)
file(REMOVE nice_project/wsgi.py.in)
configure_file(nice_project/settings_production.py.in nice_project/settings.py @ONLY)
file(REMOVE nice_project/settings_production.py.in)
configure_file(example_templates/slurm.sh.in example_templates/slurm.sh @ONLY)
file(REMOVE example_templates/slurm.sh.in)
configure_file(example_templates/lsf.sh.in example_templates/lsf.sh @ONLY)
file(REMOVE example_templates/lsf.sh.in)
configure_file(example_systemd/simple_nice.service.in example_systemd/simple_nice.service @ONLY)
file(REMOVE example_systemd/simple_nice.service.in)
configure_file(example_proxy/apache_virtualhost_ssl.conf.in example_proxy/apache_virtualhost_ssl.conf @ONLY)
file(REMOVE example_proxy/apache_virtualhost_ssl.conf.in)
configure_file(${SRC_PATH}/nice_local.py.in ${SIMPLE_PATH}/bin/nice_local @ONLY FILE_PERMISSIONS OWNER_READ OWNER_WRITE OWNER_EXECUTE GROUP_READ GROUP_EXECUTE WORLD_READ WORLD_EXECUTE)
