set(PATH $ENV{PATH})
set(LD_LIBRARY_PATH $ENV{LD_LIBRARY_PATH})
cmake_host_system_information(RESULT FQDN QUERY FQDN)
set(USER  $ENV{USER})
configure_file(nice_project/wsgi.py.in nice_project/wsgi.py @ONLY)
configure_file(nice_project/settings.py.in nice_project/settings.py @ONLY)
configure_file(example_templates/slurm.sh.in example_templates/slurm.sh @ONLY)
configure_file(example_systemd/simple_nice.service.in example_systemd/simple_nice.service @ONLY)
configure_file(example_proxy/apache_virtualhost_ssl.conf.in example_proxy/apache_virtualhost_ssl.conf @ONLY)

configure_file(${SRC_PATH}/nice_local.py.in ${SIMPLE_PATH}/nice_local @ONLY FILE_PERMISSIONS OWNER_READ OWNER_WRITE OWNER_EXECUTE GROUP_READ GROUP_EXECUTE WORLD_READ WORLD_EXECUTE)