/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * PerformanceEoVolAssembleJPanel.java
 *
 * Created on 25/11/2015, 9:26:29 PM
 */

package edu.kit.gridbeans.simpleeovolassemble.plugin;

import javax.swing.JPanel;

import com.intel.gpe.gridbeans.plugins.DataSetException;
import com.intel.gpe.gridbeans.plugins.swing.panels.GridBeanPanel;

/**
 *
 * @author frederic
 */
public class PerformanceEoVolAssembleJPanel extends JPanel {
    private GridBeanPanel parentPanel;
    /**
     * Add UID
     */
    private static final long serialVersionUID = -4094706133324348696L;
    /** Creates new form PerformanceEoVolAssembleJPanel */
    public PerformanceEoVolAssembleJPanel(GridBeanPanel parentpanel) throws DataSetException {
        this.parentPanel = parentpanel;
        initComponents();
        initCustomComponents();
        bindComponents();
    }

    private void initCustomComponents() {
        // TODO Auto-generated method stub
        
    }

    private void bindComponents() {
        // TODO Auto-generated method stub
        
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPerformanceEoVolAssembleScrollPanel = new javax.swing.JScrollPane();
        mainPerformanceEoVolAssemblePanel = new javax.swing.JPanel();
        distributionPerformancePanel = new javax.swing.JPanel();
        openMPPanel = new javax.swing.JPanel();
        nthrLabel = new javax.swing.JLabel();
        nthrComboBox = new javax.swing.JComboBox();

        setLayout(new java.awt.BorderLayout());

        distributionPerformancePanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Partition and thread distribution...", 0, 0, null, new java.awt.Color(-16776961,true)));

        openMPPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "OpenMP...", 0, 0, null, new java.awt.Color(-65281,true)));

        nthrLabel.setText("Number of threads nthr:");

        nthrComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16" }));

        javax.swing.GroupLayout openMPPanelLayout = new javax.swing.GroupLayout(openMPPanel);
        openMPPanel.setLayout(openMPPanelLayout);
        openMPPanelLayout.setHorizontalGroup(
            openMPPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(openMPPanelLayout.createSequentialGroup()
                .addComponent(nthrLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nthrComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        openMPPanelLayout.setVerticalGroup(
            openMPPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(openMPPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(openMPPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nthrLabel)
                    .addComponent(nthrComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout distributionPerformancePanelLayout = new javax.swing.GroupLayout(distributionPerformancePanel);
        distributionPerformancePanel.setLayout(distributionPerformancePanelLayout);
        distributionPerformancePanelLayout.setHorizontalGroup(
            distributionPerformancePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(distributionPerformancePanelLayout.createSequentialGroup()
                .addComponent(openMPPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        distributionPerformancePanelLayout.setVerticalGroup(
            distributionPerformancePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(distributionPerformancePanelLayout.createSequentialGroup()
                .addComponent(openMPPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout mainPerformanceEoVolAssemblePanelLayout = new javax.swing.GroupLayout(mainPerformanceEoVolAssemblePanel);
        mainPerformanceEoVolAssemblePanel.setLayout(mainPerformanceEoVolAssemblePanelLayout);
        mainPerformanceEoVolAssemblePanelLayout.setHorizontalGroup(
            mainPerformanceEoVolAssemblePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPerformanceEoVolAssemblePanelLayout.createSequentialGroup()
                .addComponent(distributionPerformancePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(260, Short.MAX_VALUE))
        );
        mainPerformanceEoVolAssemblePanelLayout.setVerticalGroup(
            mainPerformanceEoVolAssemblePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPerformanceEoVolAssemblePanelLayout.createSequentialGroup()
                .addComponent(distributionPerformancePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(252, Short.MAX_VALUE))
        );

        mainPerformanceEoVolAssembleScrollPanel.setViewportView(mainPerformanceEoVolAssemblePanel);

        add(mainPerformanceEoVolAssembleScrollPanel, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel distributionPerformancePanel;
    private javax.swing.JPanel mainPerformanceEoVolAssemblePanel;
    private javax.swing.JScrollPane mainPerformanceEoVolAssembleScrollPanel;
    private javax.swing.JComboBox nthrComboBox;
    private javax.swing.JLabel nthrLabel;
    private javax.swing.JPanel openMPPanel;
    // End of variables declaration//GEN-END:variables

}
