/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * SimpleEoVolAssemblePanel.java
 *
 * Created on 17/11/2015, 1:32:29 PM
 */

package edu.kit.gridbeans.simpleeovolassemble.plugin;

import com.intel.gpe.clients.api.Client;
import com.intel.gpe.gridbeans.plugins.DataSetException;
import com.intel.gpe.gridbeans.plugins.swing.panels.GridBeanPanel;
import com.intel.gpe.util.defaults.preferences.INode;

/**
 *
 * @author Frederic Bonnet
 * @Date 17th of November 2015
 * 
 */
public class SimpleEoVolAssemblePanel extends GridBeanPanel {

    /**
	 * Add UID
	 */
	private static final long serialVersionUID = -2397646353073056400L;


	/** Creates new form SimpleEoVolAssemblePanel */
    public SimpleEoVolAssemblePanel(Client client, INode node) {
    	super(client, "SimpleEoVolAssemble", node);
        initComponents();
        try {
			initTab();
		} catch (DataSetException e) {
			getClient().showException("error creating Simple Eo Volume Assemble Panel", e);
			e.printStackTrace();
		}
    }

    private void initTab() throws DataSetException {
		// TODO Auto-generated method stub
		WelcomeEoVolAssembleJPanel welcomeEoVolAssemblePanel = new WelcomeEoVolAssembleJPanel(this);
		SimpleEoVolAssembleJPanel simpleEoVolAssemblePanel = new SimpleEoVolAssembleJPanel(this);
		PerformanceEoVolAssembleJPanel performanceEoVolAssemblePanel = new PerformanceEoVolAssembleJPanel(this);
		
		mainSimpleEoVolAssemblejTabbedPanel.addTab("0. Welcome eo_VolAssemble panel", welcomeEoVolAssemblePanel);
		mainSimpleEoVolAssemblejTabbedPanel.addTab("1. simple_eo_VolAssemble panel", simpleEoVolAssemblePanel);
		//mainSimpleEoVolAssemblejTabbedPanel.addTab("2. Performance eo_VolAssemble panel", performanceEoVolAssemblePanel);
	}

	/** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainSimpleEoVolAssemblejTabbedPanel = new javax.swing.JTabbedPane();

        setLayout(new java.awt.BorderLayout());
        add(mainSimpleEoVolAssemblejTabbedPanel, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane mainSimpleEoVolAssemblejTabbedPanel;
    // End of variables declaration//GEN-END:variables

}
