/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * SimpleEoVolAssembleJPanel.java
 *
 * Created on 25/11/2015, 7:45:39 PM
 */

package edu.kit.gridbeans.simpleeovolassemble.plugin;

import javax.swing.JPanel;

import com.intel.gpe.gridbeans.plugins.DataSetException;
import com.intel.gpe.gridbeans.plugins.swing.controls.ComboBoxDataControl;
import com.intel.gpe.gridbeans.plugins.swing.panels.GridBeanPanel;
import com.intel.gpe.gridbeans.plugins.translators.StringValueTranslator;
import com.intel.gpe.gridbeans.plugins.validators.DoubleValueValidator;
import com.intel.gpe.gridbeans.plugins.validators.IntegerValueValidator;
import com.intel.gpe.gridbeans.plugins.validators.NotNullValidator;

import edu.kit.gridbeans.simpleeovolassemble.NthrSimpleEoVolAssembleCalculationType;
import edu.kit.gridbeans.simpleeovolassemble.SimpleEoVolAssembleGridBean;

/**
 *
 * @author Frederic Bonnet
 * @Date 25th November 2015
 * 
 */
public class SimpleEoVolAssembleJPanel extends JPanel {
    private GridBeanPanel parentPanel;
    /**
     * Add UID
     */
    private static final long serialVersionUID = -6174841763447243946L;
    /** Creates new form SimpleEoVolAssembleJPanel */
    public SimpleEoVolAssembleJPanel(GridBeanPanel parentpanel) throws DataSetException {
        this.parentPanel = parentpanel;
        initComponents();
        initCustomComponents();
        bindComponents();
    }
    private void initCustomComponents() {
        // TODO Auto-generated method stub
        
    }
    private void bindComponents() throws DataSetException {
        //STK
        parentPanel.linkTextField(SimpleEoVolAssembleGridBean.STK, stackNameTextField);
        parentPanel.setValueTranslator(SimpleEoVolAssembleGridBean.STK, StringValueTranslator.getInstance());
        //--nstates=$NSTATES \              #nstates=<nr of states> 
        parentPanel.linkTextField(SimpleEoVolAssembleGridBean.NSTATES, nstatesTextField);
        parentPanel.setValueTranslator(SimpleEoVolAssembleGridBean.NSTATES, StringValueTranslator.getInstance());
        parentPanel.setValueValidator(SimpleEoVolAssembleGridBean.NSTATES, new IntegerValueValidator());
        //--msk=$MSK \                      #msk=<mask radius(in pixels)> smpd=<sampling distance(in A)>
        parentPanel.linkTextField(SimpleEoVolAssembleGridBean.MSK, mskTextField);
        parentPanel.setValueTranslator(SimpleEoVolAssembleGridBean.MSK, StringValueTranslator.getInstance());
        parentPanel.setValueValidator(SimpleEoVolAssembleGridBean.MSK, new DoubleValueValidator());
        //--mw=$MW \ #[mw=<molecular weight(in kD)>]
        parentPanel.linkTextField(SimpleEoVolAssembleGridBean.MW, mwTextField);
        parentPanel.setValueTranslator(SimpleEoVolAssembleGridBean.MW, StringValueTranslator.getInstance());
        parentPanel.setValueValidator(SimpleEoVolAssembleGridBean.MW, new DoubleValueValidator());
        //--lpstop=$LPSTOP \                #[lpstop=<stay at this low-pass limit(in A)>]
        parentPanel.linkTextField(SimpleEoVolAssembleGridBean.MW, mwTextField);
        parentPanel.setValueTranslator(SimpleEoVolAssembleGridBean.MW, StringValueTranslator.getInstance());
        parentPanel.setValueValidator(SimpleEoVolAssembleGridBean.MW, new DoubleValueValidator());
        //--inner=$INNER \                   #[inner=<inner mask radius(in pixels)>]
        parentPanel.linkTextField(SimpleEoVolAssembleGridBean.INNER, innerTextField);
        parentPanel.setValueTranslator(SimpleEoVolAssembleGridBean.INNER, StringValueTranslator.getInstance());
        parentPanel.setValueValidator(SimpleEoVolAssembleGridBean.INNER, new DoubleValueValidator());
        //--width=$WIDTH \                   #[width=<pixels falloff inner mask{10}>]
        parentPanel.linkTextField(SimpleEoVolAssembleGridBean.WIDTH, widthTextField);
        parentPanel.setValueTranslator(SimpleEoVolAssembleGridBean.WIDTH, StringValueTranslator.getInstance());
        parentPanel.setValueValidator(SimpleEoVolAssembleGridBean.WIDTH, new DoubleValueValidator());
        //--npart=$NPART \                  #npart=<number of partitions to assemble>
        parentPanel.linkTextField(SimpleEoVolAssembleGridBean.NPART, npartTextField);
        parentPanel.setValueTranslator(SimpleEoVolAssembleGridBean.NPART, StringValueTranslator.getInstance());
        parentPanel.setValueValidator(SimpleEoVolAssembleGridBean.NPART, new DoubleValueValidator());
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainSimpleEoVolAssembleScrollPanel = new javax.swing.JScrollPane();
        mainSImpleEoVolAssemblePanel = new javax.swing.JPanel();
        stackDetailsPanel = new javax.swing.JPanel();
        stakNameLabel = new javax.swing.JLabel();
        stackNameTextField = new javax.swing.JTextField();
        browseStkButton = new javax.swing.JButton();
        nstatesLabel = new javax.swing.JLabel();
        nstatesTextField = new javax.swing.JTextField();
        mskLabel = new javax.swing.JLabel();
        mskTextField = new javax.swing.JTextField();
        otherParamsPanel = new javax.swing.JPanel();
        mwLabel = new javax.swing.JLabel();
        mwTextField = new javax.swing.JTextField();
        lpstopLabel = new javax.swing.JLabel();
        lpstopTextField = new javax.swing.JTextField();
        innerLabel = new javax.swing.JLabel();
        innerTextField = new javax.swing.JTextField();
        widthLabel = new javax.swing.JLabel();
        widthTextField = new javax.swing.JTextField();
        distributionPerformancePanel = new javax.swing.JPanel();
        openMPPanel = new javax.swing.JPanel();
        nthrLabel = new javax.swing.JLabel();
        nthrComboBox = new javax.swing.JComboBox();
        nthrRadioButton = new javax.swing.JRadioButton();
        npartLabel = new javax.swing.JLabel();
        npartTextField = new javax.swing.JTextField();

        setLayout(new java.awt.BorderLayout());

        stackDetailsPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Stack and input details..."));

        stakNameLabel.setText("Stk name:");

        browseStkButton.setText("Browse");

        nstatesLabel.setText("nstates:");

        mskLabel.setText("msk:");

        javax.swing.GroupLayout stackDetailsPanelLayout = new javax.swing.GroupLayout(stackDetailsPanel);
        stackDetailsPanel.setLayout(stackDetailsPanelLayout);
        stackDetailsPanelLayout.setHorizontalGroup(
            stackDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(stackDetailsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(stackDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(stackDetailsPanelLayout.createSequentialGroup()
                        .addComponent(stakNameLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(stackNameTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 268, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(browseStkButton))
                    .addGroup(stackDetailsPanelLayout.createSequentialGroup()
                        .addComponent(mskLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(mskTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nstatesLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nstatesTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        stackDetailsPanelLayout.setVerticalGroup(
            stackDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(stackDetailsPanelLayout.createSequentialGroup()
                .addGroup(stackDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(stakNameLabel)
                    .addComponent(stackNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(browseStkButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(stackDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mskTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mskLabel)
                    .addComponent(nstatesLabel)
                    .addComponent(nstatesTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        otherParamsPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Other params..."));

        mwLabel.setText("Molecular weight mw:");

        lpstopLabel.setText("Stay at this Low pass limit lpstop:");

        innerLabel.setText("Inner mask radius inner:");

        widthLabel.setText("pixels falloff width:");

        javax.swing.GroupLayout otherParamsPanelLayout = new javax.swing.GroupLayout(otherParamsPanel);
        otherParamsPanel.setLayout(otherParamsPanelLayout);
        otherParamsPanelLayout.setHorizontalGroup(
            otherParamsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(otherParamsPanelLayout.createSequentialGroup()
                .addGroup(otherParamsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(otherParamsPanelLayout.createSequentialGroup()
                        .addComponent(mwLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(mwTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lpstopLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lpstopTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(otherParamsPanelLayout.createSequentialGroup()
                        .addComponent(innerLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(innerTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(widthLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(widthTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        otherParamsPanelLayout.setVerticalGroup(
            otherParamsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(otherParamsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(otherParamsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mwLabel)
                    .addComponent(mwTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lpstopLabel)
                    .addComponent(lpstopTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(otherParamsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(innerLabel)
                    .addComponent(innerTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(widthTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(widthLabel))
                .addContainerGap())
        );

        distributionPerformancePanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Partition and thread distribution..."));

        openMPPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("OpenMP..."));

        nthrLabel.setText("Number of threads nthr:");

        nthrComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16" }));

        nthrRadioButton.setText("nthr");
        nthrRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nthrRadioButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout openMPPanelLayout = new javax.swing.GroupLayout(openMPPanel);
        openMPPanel.setLayout(openMPPanelLayout);
        openMPPanelLayout.setHorizontalGroup(
            openMPPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(openMPPanelLayout.createSequentialGroup()
                .addComponent(nthrLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nthrComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nthrRadioButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        openMPPanelLayout.setVerticalGroup(
            openMPPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(openMPPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(openMPPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nthrLabel)
                    .addComponent(nthrComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nthrRadioButton))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        npartLabel.setText("npart:");

        javax.swing.GroupLayout distributionPerformancePanelLayout = new javax.swing.GroupLayout(distributionPerformancePanel);
        distributionPerformancePanel.setLayout(distributionPerformancePanelLayout);
        distributionPerformancePanelLayout.setHorizontalGroup(
            distributionPerformancePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, distributionPerformancePanelLayout.createSequentialGroup()
                .addComponent(openMPPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(npartLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(npartTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42))
        );
        distributionPerformancePanelLayout.setVerticalGroup(
            distributionPerformancePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(distributionPerformancePanelLayout.createSequentialGroup()
                .addGroup(distributionPerformancePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(distributionPerformancePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(npartTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(npartLabel))
                    .addComponent(openMPPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout mainSImpleEoVolAssemblePanelLayout = new javax.swing.GroupLayout(mainSImpleEoVolAssemblePanel);
        mainSImpleEoVolAssemblePanel.setLayout(mainSImpleEoVolAssemblePanelLayout);
        mainSImpleEoVolAssemblePanelLayout.setHorizontalGroup(
            mainSImpleEoVolAssemblePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainSImpleEoVolAssemblePanelLayout.createSequentialGroup()
                .addGroup(mainSImpleEoVolAssemblePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(stackDetailsPanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, mainSImpleEoVolAssemblePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(distributionPerformancePanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(otherParamsPanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(406, 406, 406))
        );
        mainSImpleEoVolAssemblePanelLayout.setVerticalGroup(
            mainSImpleEoVolAssemblePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainSImpleEoVolAssemblePanelLayout.createSequentialGroup()
                .addComponent(stackDetailsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(otherParamsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(distributionPerformancePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(182, Short.MAX_VALUE))
        );

        mainSimpleEoVolAssembleScrollPanel.setViewportView(mainSImpleEoVolAssemblePanel);

        add(mainSimpleEoVolAssembleScrollPanel, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void nthrRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nthrRadioButtonActionPerformed
        //Number of hreads
        try {
            ComboBoxDataControl nThrComboBoxDataControl = new ComboBoxDataControl(parentPanel.getClient(), SimpleEoVolAssembleGridBean.NTHR, nthrComboBox);
            nThrComboBoxDataControl.setPossibleValues(NthrSimpleEoVolAssembleCalculationType.getIntegerList());
            parentPanel.linkDataControl(SimpleEoVolAssembleGridBean.NTHR, nThrComboBoxDataControl);
            parentPanel.setValueTranslator(SimpleEoVolAssembleGridBean.NTHR, StringValueTranslator.getInstance());
            parentPanel.setValueValidator(SimpleEoVolAssembleGridBean.NTHR, NotNullValidator.getInstance());
        } catch (DataSetException e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_nthrRadioButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton browseStkButton;
    private javax.swing.JPanel distributionPerformancePanel;
    private javax.swing.JLabel innerLabel;
    private javax.swing.JTextField innerTextField;
    private javax.swing.JLabel lpstopLabel;
    private javax.swing.JTextField lpstopTextField;
    private javax.swing.JPanel mainSImpleEoVolAssemblePanel;
    private javax.swing.JScrollPane mainSimpleEoVolAssembleScrollPanel;
    private javax.swing.JLabel mskLabel;
    private javax.swing.JTextField mskTextField;
    private javax.swing.JLabel mwLabel;
    private javax.swing.JTextField mwTextField;
    private javax.swing.JLabel npartLabel;
    private javax.swing.JTextField npartTextField;
    private javax.swing.JLabel nstatesLabel;
    private javax.swing.JTextField nstatesTextField;
    private javax.swing.JComboBox nthrComboBox;
    private javax.swing.JLabel nthrLabel;
    private javax.swing.JRadioButton nthrRadioButton;
    private javax.swing.JPanel openMPPanel;
    private javax.swing.JPanel otherParamsPanel;
    private javax.swing.JPanel stackDetailsPanel;
    private javax.swing.JTextField stackNameTextField;
    private javax.swing.JLabel stakNameLabel;
    private javax.swing.JLabel widthLabel;
    private javax.swing.JTextField widthTextField;
    // End of variables declaration//GEN-END:variables

}
